"""
title: SitePulse
description: DNS, RDAP, TLS certificate, and HTTP health snapshot for a domain. Uses the Public Suffix List for accurate eTLD+1 detection.
author: Orzed, LLC
version: 1.0.0
required_open_webui_version: 0.5.0
"""

# ────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED BY tools/bundle_owui.py — DO NOT EDIT BY HAND.
# Source of truth: this tool's core/ and owui/_wrapper.py.
# Run `make bundle` (or `python tools/bundle_owui.py <tool>`) to regenerate.
# CI runs `make check-bundle` and fails on drift.
# ────────────────────────────────────────────────────────────────────────────

import httpx
import random
import socket
import ssl
import time
import urllib.parse
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
from datetime import datetime, timezone
from pydantic import BaseModel, Field
from typing import Final
from typing import Generic, Literal, TypeVar

# === core/types.py ===
T = TypeVar("T", bound=BaseModel)

ErrorCode = Literal[
    "INVALID_INPUT",
    "NOT_FOUND",
    "RATE_LIMITED",
    "NETWORK_TIMEOUT",
    "UPSTREAM_ERROR",
    "UNSUPPORTED",
    "PARSE_ERROR",
    "TIMEOUT",
    "CANCELLED",
    "INTERNAL",
]

CheckName = Literal["dns", "rdap", "ssl", "http", "headers"]


class ErrorInfo(BaseModel):
    code: ErrorCode
    message_en: str
    message_tr: str
    hint: str | None = None
    upstream: str | None = None
    retry_after_s: float | None = None


class Result(BaseModel, Generic[T]):
    ok: bool
    data: T | None = None
    error: ErrorInfo | None = None
    meta: dict = Field(default_factory=dict)


class DnsResults(BaseModel):
    a: list[str] = Field(default_factory=list)
    aaaa: list[str] = Field(default_factory=list)
    cname: list[str] = Field(default_factory=list)
    mx: list[str] = Field(default_factory=list)
    txt: list[str] = Field(default_factory=list)
    ns: list[str] = Field(default_factory=list)
    spf_record: str | None = None
    dmarc_record: str | None = None
    note: str | None = None


class SslCert(BaseModel):
    ok: bool
    issuer: str | None = None
    subject: str | None = None
    not_before: datetime | None = None
    not_after: datetime | None = None
    days_until_expiry: int | None = None
    san: list[str] = Field(default_factory=list)
    error: str | None = None


class RdapInfo(BaseModel):
    ok: bool
    registrar: str | None = None
    registered_on: datetime | None = None
    expires_on: datetime | None = None
    name_servers: list[str] = Field(default_factory=list)
    status: list[str] = Field(default_factory=list)
    error: str | None = None


class HttpProbe(BaseModel):
    url: str
    status_code: int | None = None
    final_url: str | None = None
    redirects: int = 0
    response_time_ms: int = 0
    server: str | None = None
    content_type: str | None = None
    hsts: str | None = None
    error: str | None = None


class DomainHealth(BaseModel):
    input: str
    host: str
    registered_domain: str
    dns: DnsResults | None = None
    rdap: RdapInfo | None = None
    ssl: SslCert | None = None
    http: HttpProbe | None = None
    https: HttpProbe | None = None
    issues: list[str] = Field(default_factory=list)

# === core/i18n.py ===
STRINGS: Final[dict[str, dict[str, str]]] = {
    "en": {
        "title": "SitePulse",
        "section.dns": "DNS",
        "section.rdap": "Domain Registration (RDAP)",
        "section.ssl": "TLS Certificate",
        "section.http": "HTTP",
        "section.https": "HTTPS",
        "section.issues": "Issues",
        "label.host": "Host",
        "label.registered_domain": "Registered domain",
        "label.no_records": "no records",
        "label.expires_in": "Expires in",
        "label.days": "days",
        "label.registrar": "Registrar",
        "label.registered_on": "Registered on",
        "label.expires_on": "Expires on",
        "label.name_servers": "Name servers",
        "label.no_data": "no data",
        "error.empty_input": "Domain or URL is required.",
        "error.invalid_input": "Could not parse a valid hostname from the input.",
        "issue.no_a_records": "Domain has no A or AAAA records.",
        "issue.cert_expired": "TLS certificate is expired.",
        "issue.cert_expiring_soon": "TLS certificate expires in {days} days.",
        "issue.https_unreachable": "HTTPS endpoint is unreachable.",
        "issue.no_hsts": "HSTS header is missing.",
        "issue.no_dmarc": "No DMARC record found.",
        "issue.no_spf": "No SPF record found.",
        "note.audit": "For page-level SEO/AI signals see pagesignal.",
    },
    "tr": {
        "title": "SitePulse",
        "section.dns": "DNS",
        "section.rdap": "Alan Adı Kaydı (RDAP)",
        "section.ssl": "TLS Sertifikası",
        "section.http": "HTTP",
        "section.https": "HTTPS",
        "section.issues": "Bulgular",
        "label.host": "Host",
        "label.registered_domain": "Kayıtlı alan",
        "label.no_records": "kayıt yok",
        "label.expires_in": "Süresi",
        "label.days": "gün",
        "label.registrar": "Tescil eden",
        "label.registered_on": "Tescil tarihi",
        "label.expires_on": "Son geçerlilik",
        "label.name_servers": "Ad sunucuları",
        "label.no_data": "veri yok",
        "error.empty_input": "Alan adı veya URL zorunlu.",
        "error.invalid_input": "Girdiden geçerli bir host adı çıkarılamadı.",
        "issue.no_a_records": "Alan adının A/AAAA kaydı yok.",
        "issue.cert_expired": "TLS sertifikası süresi dolmuş.",
        "issue.cert_expiring_soon": "TLS sertifikasının süresi {days} gün içinde dolacak.",
        "issue.https_unreachable": "HTTPS uç noktasına erişilemiyor.",
        "issue.no_hsts": "HSTS başlığı yok.",
        "issue.no_dmarc": "DMARC kaydı bulunamadı.",
        "issue.no_spf": "SPF kaydı bulunamadı.",
        "note.audit": "Sayfa düzeyinde SEO/AI sinyalleri için pagesignal'i kullanın.",
    },
}

SUPPORTED: Final[tuple[str, ...]] = ("en", "tr")
DEFAULT: Final[str] = "en"


def normalize_lang(lang: str | None) -> str:
    if not lang:
        return DEFAULT
    base = lang.lower().split("-")[0]
    return base if base in SUPPORTED else DEFAULT


def t(key: str, lang: str = DEFAULT, **kwargs: object) -> str:
    lang = normalize_lang(lang)
    table = STRINGS.get(lang) or STRINGS[DEFAULT]
    template = table.get(key) or STRINGS[DEFAULT].get(key) or key
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError):
        return template

# === core/domain.py ===
def normalize_host(input_str: str) -> str | None:
    """Strip schemes, ports, paths, and lowercase. Returns None if nothing usable."""
    if not input_str:
        return None
    raw = input_str.strip().rstrip("/")
    if "://" in raw:
        try:
            parsed = urllib.parse.urlparse(raw)
            host = parsed.hostname or ""
        except ValueError:
            return None
    else:
        host = raw
    host = host.split("/")[0].split("@")[-1].split(":")[0].strip(".")
    if not host or " " in host:
        return None
    return host.lower()


def registered_domain(host: str) -> str:
    """Return the registered domain (eTLD+1) for a host using tldextract.

    Falls back to the dotted-pair if tldextract is unavailable or the host
    looks like an IP/raw token.
    """
    if not host:
        return host
    try:
        import tldextract

        ext = tldextract.extract(host)
        if ext.domain and ext.suffix:
            return f"{ext.domain}.{ext.suffix}"
        return ext.domain or host
    except Exception:
        parts = host.split(".")
        if len(parts) >= 2:
            return ".".join(parts[-2:])
        return host

# === core/http.py ===
class RateLimited(Exception):
    def __init__(self, retry_after: float | None = None) -> None:
        self.retry_after = retry_after


class NetworkTimeout(Exception):
    pass


class UpstreamError(Exception):
    def __init__(self, status: int, body: str) -> None:
        self.status = status
        self.body = body


def build_client(
    timeout: float = 6.0, user_agent: str = "orzed-sitepulse/1.0"
) -> httpx.Client:
    return httpx.Client(
        timeout=timeout,
        headers={"User-Agent": user_agent},
        follow_redirects=True,
    )


def get_with_retry(
    client: httpx.Client,
    url: str,
    *,
    headers: dict | None = None,
    params: dict | None = None,
    max_attempts: int = 2,
    base_delay: float = 0.4,
) -> httpx.Response:
    last_exc: Exception | None = None
    for attempt in range(max_attempts):
        try:
            r = client.get(url, params=params, headers=headers)
        except httpx.TimeoutException:
            last_exc = NetworkTimeout()
        except httpx.RequestError as e:
            last_exc = e
        else:
            if r.status_code == 429:
                ra = r.headers.get("Retry-After")
                last_exc = RateLimited(retry_after=float(ra) if ra else None)
            elif r.status_code in (408, 500, 502, 503, 504):
                last_exc = UpstreamError(r.status_code, r.text[:300])
            else:
                return r

        if attempt < max_attempts - 1:
            sleep_s = base_delay * (2**attempt) + random.uniform(0, base_delay)
            if isinstance(last_exc, RateLimited) and last_exc.retry_after:
                sleep_s = max(sleep_s, last_exc.retry_after)
            time.sleep(sleep_s)

    if last_exc is not None:
        raise last_exc
    raise UpstreamError(0, "no attempts")

# === core/dns.py ===
DOH_ENDPOINT = "https://cloudflare-dns.com/dns-query"


def _fetch(client, host: str, record_type: str) -> list[str]:
    try:
        r = get_with_retry(
            client,
            DOH_ENDPOINT,
            params={"name": host, "type": record_type},
            headers={"Accept": "application/dns-json"},
        )
    except UpstreamError:
        return []
    except Exception:
        return []
    if r.status_code != 200:
        return []
    try:
        data = r.json()
    except ValueError:
        return []
    out = []
    for ans in data.get("Answer") or []:
        d = ans.get("data")
        if d:
            out.append(str(d).strip().rstrip("."))
    return out


def fetch_all(client, host: str) -> DnsResults:
    a = _fetch(client, host, "A")
    aaaa = _fetch(client, host, "AAAA")
    cname = _fetch(client, host, "CNAME")
    mx_raw = _fetch(client, host, "MX")
    txt_raw = _fetch(client, host, "TXT")
    ns = _fetch(client, host, "NS")

    mx = [m for m in mx_raw if m]
    txt = [t.strip('"') for t in txt_raw if t]

    spf = next((t for t in txt if t.lower().startswith("v=spf1")), None)

    dmarc_records = _fetch(client, f"_dmarc.{host}", "TXT")
    dmarc = next(
        (t.strip('"') for t in dmarc_records if t.strip('"').lower().startswith("v=dmarc1")),
        None,
    )

    return DnsResults(
        a=a, aaaa=aaaa, cname=cname, mx=mx, txt=txt, ns=ns,
        spf_record=spf, dmarc_record=dmarc,
    )

# === core/ssl_check.py ===
def fetch_cert(host: str, port: int = 443, timeout: float = 5.0) -> SslCert:
    try:
        ctx = ssl.create_default_context()
        with socket.create_connection((host, port), timeout=timeout) as sock:
            with ctx.wrap_socket(sock, server_hostname=host) as ssock:
                der = ssock.getpeercert(binary_form=True)
    except Exception as exc:
        return SslCert(ok=False, error=f"{type(exc).__name__}: {exc}")

    try:
        from cryptography import x509
        from cryptography.x509.oid import NameOID

        cert = x509.load_der_x509_certificate(der)
        issuer_attrs = cert.issuer.get_attributes_for_oid(NameOID.COMMON_NAME)
        subject_attrs = cert.subject.get_attributes_for_oid(NameOID.COMMON_NAME)
        not_before = cert.not_valid_before_utc.replace(tzinfo=timezone.utc) if hasattr(cert, "not_valid_before_utc") else cert.not_valid_before
        not_after = cert.not_valid_after_utc.replace(tzinfo=timezone.utc) if hasattr(cert, "not_valid_after_utc") else cert.not_valid_after
        # Strip any pre-existing tzinfo for the timedelta math then compare in UTC.
        now = datetime.now(timezone.utc)
        days_until = int((not_after - now).total_seconds() // 86400) if not_after else None
        san: list[str] = []
        try:
            ext = cert.extensions.get_extension_for_class(x509.SubjectAlternativeName)
            san = [str(name) for name in ext.value.get_values_for_type(x509.DNSName)]
        except Exception:
            pass
        return SslCert(
            ok=True,
            issuer=issuer_attrs[0].value if issuer_attrs else None,
            subject=subject_attrs[0].value if subject_attrs else None,
            not_before=not_before,
            not_after=not_after,
            days_until_expiry=days_until,
            san=san,
        )
    except Exception as exc:
        return SslCert(ok=False, error=f"parse: {type(exc).__name__}: {exc}")

# === core/rdap.py ===
RDAP_BOOTSTRAP = "https://rdap.org/domain"


def _parse_iso(value: str | None) -> datetime | None:
    if not value:
        return None
    try:
        # rdap.org returns ISO-8601 with Z; fromisoformat in 3.11+ accepts that.
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None


def fetch(client, registered: str) -> RdapInfo:
    if not registered:
        return RdapInfo(ok=False, error="no domain")
    try:
        r = get_with_retry(
            client,
            f"{RDAP_BOOTSTRAP}/{registered}",
            headers={"Accept": "application/rdap+json, application/json"},
        )
    except UpstreamError as exc:
        return RdapInfo(ok=False, error=f"upstream {exc.status}")
    except Exception as exc:
        return RdapInfo(ok=False, error=f"{type(exc).__name__}: {exc}")
    if r.status_code != 200:
        return RdapInfo(ok=False, error=f"http {r.status_code}")
    try:
        data = r.json()
    except ValueError:
        return RdapInfo(ok=False, error="parse")

    registrar = None
    for entity in data.get("entities") or []:
        roles = [r.lower() for r in (entity.get("roles") or [])]
        if "registrar" not in roles:
            continue
        vcard = entity.get("vcardArray")
        if isinstance(vcard, list) and len(vcard) > 1:
            for tag in vcard[1]:
                if isinstance(tag, list) and tag and tag[0] == "fn" and len(tag) >= 4:
                    registrar = tag[3]
                    break

    registered_on = None
    expires_on = None
    for ev in data.get("events") or []:
        action = (ev.get("eventAction") or "").lower()
        date = _parse_iso(ev.get("eventDate"))
        if action == "registration":
            registered_on = date
        elif action in ("expiration", "expires"):
            expires_on = date

    name_servers: list[str] = []
    for ns in data.get("nameservers") or []:
        if isinstance(ns, dict):
            name = ns.get("ldhName") or ns.get("unicodeName")
            if name:
                name_servers.append(name)

    return RdapInfo(
        ok=True,
        registrar=registrar,
        registered_on=registered_on,
        expires_on=expires_on,
        name_servers=name_servers,
        status=list(data.get("status") or []),
    )

# === core/checks.py ===
ALL_CHECKS = ("dns", "rdap", "ssl", "http")


def _err(code: str, lang: str, en_key: str) -> ErrorInfo:
    return ErrorInfo(
        code=code,
        message_en=t(en_key, "en"),
        message_tr=t(en_key, "tr"),
    )


def _http_probe(client, scheme: str, host: str) -> HttpProbe:
    url = f"{scheme}://{host}/"
    started = time.monotonic()
    try:
        r = get_with_retry(client, url)
    except Exception as exc:
        return HttpProbe(url=url, error=f"{type(exc).__name__}: {exc}")
    elapsed_ms = int((time.monotonic() - started) * 1000)
    return HttpProbe(
        url=url,
        status_code=r.status_code,
        final_url=str(r.url),
        redirects=len(r.history),
        response_time_ms=elapsed_ms,
        server=r.headers.get("server"),
        content_type=r.headers.get("content-type"),
        hsts=r.headers.get("strict-transport-security"),
    )


def inspect(
    domain: str,
    checks: list[str] | None = None,
    *,
    language: str = "en",
    timeout_seconds: float = 6.0,
) -> Result[DomainHealth]:
    lang = normalize_lang(language)

    if not domain:
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.empty_input"))
    host = normalize_host(domain)
    if not host:
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.invalid_input"))
    reg = registered_domain(host)

    requested = list(dict.fromkeys(checks or list(ALL_CHECKS)))
    invalid = [c for c in requested if c not in ALL_CHECKS]
    if invalid:
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.invalid_input"))

    client = build_client(timeout=timeout_seconds)
    try:
        results: dict[str, object] = {}

        with ThreadPoolExecutor(max_workers=6) as pool:
            futures = {}
            if "dns" in requested:
                futures["dns"] = pool.submit(dns_mod.fetch_all, client, host)
            if "rdap" in requested:
                futures["rdap"] = pool.submit(rdap_mod.fetch, client, reg)
            if "ssl" in requested:
                futures["ssl"] = pool.submit(ssl_check.fetch_cert, host)
            if "http" in requested:
                futures["http"] = pool.submit(_http_probe, client, "http", host)
                futures["https"] = pool.submit(_http_probe, client, "https", host)

            for key, fut in futures.items():
                try:
                    results[key] = fut.result(timeout=timeout_seconds + 5)
                except Exception as exc:
                    results[key] = exc

        issues: list[str] = []
        dns_obj = results.get("dns")
        if dns_obj is not None and not isinstance(dns_obj, Exception):
            if not dns_obj.a and not dns_obj.aaaa:
                issues.append(t("issue.no_a_records", lang))
            if not dns_obj.spf_record:
                issues.append(t("issue.no_spf", lang))
            if not dns_obj.dmarc_record:
                issues.append(t("issue.no_dmarc", lang))

        ssl_obj = results.get("ssl")
        if ssl_obj is not None and not isinstance(ssl_obj, Exception) and ssl_obj.ok:
            if ssl_obj.days_until_expiry is not None:
                if ssl_obj.days_until_expiry < 0:
                    issues.append(t("issue.cert_expired", lang))
                elif ssl_obj.days_until_expiry < 14:
                    issues.append(t("issue.cert_expiring_soon", lang, days=ssl_obj.days_until_expiry))

        https_obj = results.get("https")
        if https_obj is not None and not isinstance(https_obj, Exception):
            if https_obj.error or (https_obj.status_code and https_obj.status_code >= 500):
                issues.append(t("issue.https_unreachable", lang))
            elif not https_obj.hsts:
                issues.append(t("issue.no_hsts", lang))

        health = DomainHealth(
            input=domain,
            host=host,
            registered_domain=reg,
            dns=dns_obj if not isinstance(dns_obj, Exception) else None,
            rdap=results.get("rdap") if not isinstance(results.get("rdap"), Exception) else None,
            ssl=ssl_obj if not isinstance(ssl_obj, Exception) else None,
            http=results.get("http") if not isinstance(results.get("http"), Exception) else None,
            https=https_obj if not isinstance(https_obj, Exception) else None,
            issues=issues,
        )
        return Result(ok=True, data=health, meta={"host": host, "registered_domain": reg})
    finally:
        client.close()

# === core/render.py ===
def to_markdown(result: Result[DomainHealth], lang: str = "en") -> str:
    if not result.ok or result.data is None:
        if result.error is None:
            return f"**Error**: unknown failure (lang={lang})"
        msg = result.error.message_tr if lang == "tr" else result.error.message_en
        return f"**Error** ({result.error.code}): {msg}"

    h = result.data
    parts: list[str] = [
        f"# {t('title', lang)}",
        "",
        f"**{t('label.host', lang)}**: `{h.host}`  •  "
        f"**{t('label.registered_domain', lang)}**: `{h.registered_domain}`",
    ]

    if h.dns:
        parts += [
            "",
            f"## {t('section.dns', lang)}",
            f"- A: {', '.join(f'`{x}`' for x in h.dns.a) or t('label.no_records', lang)}",
            f"- AAAA: {', '.join(f'`{x}`' for x in h.dns.aaaa) or t('label.no_records', lang)}",
            f"- MX: {', '.join(f'`{x}`' for x in h.dns.mx) or t('label.no_records', lang)}",
            f"- NS: {', '.join(f'`{x}`' for x in h.dns.ns) or t('label.no_records', lang)}",
            f"- SPF: `{h.dns.spf_record or '—'}`",
            f"- DMARC: `{h.dns.dmarc_record or '—'}`",
        ]

    if h.rdap and h.rdap.ok:
        parts += [
            "",
            f"## {t('section.rdap', lang)}",
            f"- **{t('label.registrar', lang)}**: {h.rdap.registrar or '—'}",
            f"- **{t('label.registered_on', lang)}**: "
            f"`{h.rdap.registered_on.isoformat() if h.rdap.registered_on else '—'}`",
            f"- **{t('label.expires_on', lang)}**: "
            f"`{h.rdap.expires_on.isoformat() if h.rdap.expires_on else '—'}`",
            f"- **{t('label.name_servers', lang)}**: "
            f"{', '.join(f'`{n}`' for n in h.rdap.name_servers) or '—'}",
        ]

    if h.ssl:
        if h.ssl.ok:
            expiry_line = (
                f"`{h.ssl.not_after.isoformat()}`"
                if h.ssl.not_after else "—"
            )
            parts += [
                "",
                f"## {t('section.ssl', lang)}",
                f"- Issuer: `{h.ssl.issuer or '—'}`",
                f"- Subject: `{h.ssl.subject or '—'}`",
                f"- {t('label.expires_on', lang)}: {expiry_line}  "
                f"({t('label.expires_in', lang)} `{h.ssl.days_until_expiry}` "
                f"{t('label.days', lang)})",
            ]
        else:
            parts += [
                "",
                f"## {t('section.ssl', lang)}",
                f"- ❌ {h.ssl.error}",
            ]

    if h.https:
        parts += [
            "",
            f"## {t('section.https', lang)}",
            f"- {h.https.url} → "
            f"`{h.https.status_code or '?'}` "
            + (f"({h.https.response_time_ms} ms)" if h.https.response_time_ms else "")
            + (f" via `{h.https.server}`" if h.https.server else ""),
        ]
        if h.https.error:
            parts.append(f"- ❌ {h.https.error}")
        elif h.https.hsts:
            parts.append(f"- HSTS: `{h.https.hsts}`")
    if h.http:
        parts += [
            "",
            f"## {t('section.http', lang)}",
            f"- {h.http.url} → `{h.http.status_code or '?'}`",
        ]

    parts += ["", f"## {t('section.issues', lang)}"]
    if h.issues:
        parts.extend(f"- ⚠︎ {i}" for i in h.issues)
    else:
        parts.append("_no issues_")

    parts += ["", f"_{t('note.audit', lang)}_"]
    return "\n".join(parts)

# === owui/_wrapper.py ===
class Tools:
    class Valves(BaseModel):
        DEFAULT_LANGUAGE: str = Field(
            default="en",
            description="Output language. 'en' or 'tr'.",
        )
        TIMEOUT_SECONDS: float = Field(
            default=6.0,
            description="Per-check timeout. The whole inspect runs checks in parallel.",
        )

    def __init__(self):
        self.valves = self.Valves()
        self.citation = False

    def _lang(self, language: str | None) -> str:
        return (language or self.valves.DEFAULT_LANGUAGE or "en").strip()

    def inspect(
        self,
        domain: str,
        checks: list[str] | None = None,
        language: str | None = None,
    ) -> str:
        """
        Snapshot a domain: DNS, RDAP, TLS, HTTP/HTTPS.

        Use when: "DNS records of X" / "SSL sertifikası" / "kim kayıt ettirmiş"
        / "https çalışıyor mu". Skip for page content audits (pagesignal),
        WHOIS history, port scans, or general connectivity questions.
        """
        lang = self._lang(language)
        result = inspect(
            domain,
            checks=checks,
            language=lang,
            timeout_seconds=self.valves.TIMEOUT_SECONDS,
        )
        return to_markdown(result, lang=lang)

