"""
title: PaperForge
description: Synthesize a conversation's decisions, abandoned ideas, and current state into a flowing document. Outputs Markdown (Obsidian-friendly), HTML, DOCX, or PDF.
author: Orzed, LLC
version: 1.0.0
required_open_webui_version: 0.5.0
"""

# ────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED BY tools/bundle_owui.py - DO NOT EDIT BY HAND.
# Source of truth: this tool's core/ and owui/_wrapper.py.
# Run `make bundle` (or `python tools/bundle_owui.py <tool>`) to regenerate.
# CI runs `make check-bundle` and fails on drift.
# ────────────────────────────────────────────────────────────────────────────

import html
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from pydantic import BaseModel, Field
from typing import Final
from typing import Generic, Literal, TypeVar

# === core/types.py ===
T = TypeVar("T", bound=BaseModel)

ErrorCode = Literal[
    "INVALID_INPUT",
    "NOT_FOUND",
    "RATE_LIMITED",
    "NETWORK_TIMEOUT",
    "UPSTREAM_ERROR",
    "UNSUPPORTED",
    "PARSE_ERROR",
    "TIMEOUT",
    "CANCELLED",
    "INTERNAL",
]

DocumentFormat = Literal["md", "html", "docx", "pdf"]


class ErrorInfo(BaseModel):
    code: ErrorCode
    message_en: str
    message_tr: str
    hint: str | None = None
    upstream: str | None = None
    retry_after_s: float | None = None


class Result(BaseModel, Generic[T]):
    ok: bool
    data: T | None = None
    error: ErrorInfo | None = None
    meta: dict = Field(default_factory=dict)


class Section(BaseModel):
    """One section of the document body. Supports nesting for progressive depth."""

    heading: str
    content: str = Field(
        default="",
        description="Markdown-formatted prose. Aim for flowing paragraphs, not bullet dumps.",
    )
    children: list["Section"] = Field(default_factory=list)


class Decision(BaseModel):
    """An explicit decision worth preserving - what was chosen, why, what was rejected."""

    title: str
    chose: str = Field(description="The choice that was made.")
    why: str = Field(description="The rationale, in one or two sentences.")
    rejected: list[str] = Field(
        default_factory=list,
        description="Alternatives considered and the reason they were rejected.",
    )
    when: str | None = Field(
        default=None,
        description="Optional ISO date or human-readable phase marker (e.g. 'Wave 2').",
    )


class DocumentArtifact(BaseModel):
    """The output of a successful create_document call."""

    title: str
    format: DocumentFormat
    file_path: str
    byte_length: int
    sections_count: int
    decisions_count: int
    open_questions_count: int
    next_steps_count: int
    preview_md: str = Field(
        description="Always the markdown rendition, regardless of file format - for inspection."
    )

# === core/i18n.py ===
STRINGS: Final[dict[str, dict[str, str]]] = {
    "en": {
        "title": "PaperForge",
        "section.summary": "Summary",
        "section.context": "Context",
        "section.decisions": "Key decisions",
        "section.open_questions": "Open questions",
        "section.next_steps": "Next steps",
        "section.body": "Details",
        "label.project": "Project",
        "label.created": "Created",
        "label.format": "Format",
        "label.file_path": "File saved to",
        "label.size": "Size",
        "label.sections": "Sections",
        "label.decisions": "Decisions",
        "label.questions": "Open questions",
        "label.steps": "Next steps",
        "label.tags": "Tags",
        "decision.chose": "Chose",
        "decision.why": "Why",
        "decision.rejected": "Rejected",
        "decision.when": "When",
        "footer.note": (
            "This document was synthesized by an AI agent through paperforge. "
            "Edit it freely - Markdown is portable and Obsidian-friendly."
        ),
        "error.empty_title": (
            "title is required - synthesize one from the user's request, "
            "do not use placeholders like 'Untitled'."
        ),
        "error.empty_summary": (
            "summary could not be derived from sections - provide a summary "
            "or at least one section with non-empty content."
        ),
        "error.no_content": (
            "Provide either a `body` string (simplest) or a `sections` list with content. "
            "The tool will not fabricate content from nothing."
        ),
        "error.invalid_format": "format must be one of: md, html, docx, pdf.",
        "error.write_failed": "Failed to write the document file.",
        "error.docx_missing": "python-docx is not installed.",
        "error.pdf_missing": "weasyprint (or another PDF engine) is not available.",
        "hint.install_docx": "Install with `pip install python-docx`.",
        "hint.install_pdf": (
            "Install with `pip install weasyprint`. On Linux, weasyprint also "
            "needs Cairo/Pango: `sudo apt install libpango-1.0-0 libpangoft2-1.0-0`."
        ),
    },
    "tr": {
        "title": "PaperForge",
        "section.summary": "Özet",
        "section.context": "Bağlam",
        "section.decisions": "Önemli kararlar",
        "section.open_questions": "Açık sorular",
        "section.next_steps": "Sonraki adımlar",
        "section.body": "Detaylar",
        "label.project": "Proje",
        "label.created": "Oluşturulma",
        "label.format": "Biçim",
        "label.file_path": "Dosya konumu",
        "label.size": "Boyut",
        "label.sections": "Bölüm",
        "label.decisions": "Karar",
        "label.questions": "Açık soru",
        "label.steps": "Sonraki adım",
        "label.tags": "Etiketler",
        "decision.chose": "Seçilen",
        "decision.why": "Neden",
        "decision.rejected": "Vazgeçilen",
        "decision.when": "Ne zaman",
        "footer.note": (
            "Bu doküman bir AI agent tarafından paperforge üzerinden sentezlendi. "
            "Serbestçe düzenleyin - Markdown taşınabilir ve Obsidian uyumludur."
        ),
        "error.empty_title": (
            "title zorunlu - kullanıcının isteğinden gerçek bir başlık türet, "
            "'Untitled' gibi yer-tutucu kullanma."
        ),
        "error.empty_summary": (
            "summary bölümlerden türetilemedi - bir summary gir veya içerikli "
            "en az bir bölüm sağla."
        ),
        "error.no_content": (
            "Ya bir `body` stringi (en basit yol) ya da içerikli bir `sections` listesi gir. "
            "Araç boştan içerik uydurmaz."
        ),
        "error.invalid_format": "format şunlardan biri olmalı: md, html, docx, pdf.",
        "error.write_failed": "Dosya yazma başarısız oldu.",
        "error.docx_missing": "python-docx yüklü değil.",
        "error.pdf_missing": "weasyprint (veya başka bir PDF motoru) bulunamadı.",
        "hint.install_docx": "Kurulum: `pip install python-docx`.",
        "hint.install_pdf": (
            "Kurulum: `pip install weasyprint`. Linux'ta Cairo/Pango da gerekir: "
            "`sudo apt install libpango-1.0-0 libpangoft2-1.0-0`."
        ),
    },
}

SUPPORTED: Final[tuple[str, ...]] = ("en", "tr")
DEFAULT: Final[str] = "en"


def normalize_lang(lang: str | None) -> str:
    if not lang:
        return DEFAULT
    base = lang.lower().split("-")[0]
    return base if base in SUPPORTED else DEFAULT


def t(key: str, lang: str = DEFAULT, **kwargs: object) -> str:
    lang = normalize_lang(lang)
    table = STRINGS.get(lang) or STRINGS[DEFAULT]
    template = table.get(key) or STRINGS[DEFAULT].get(key) or key
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError):
        return template

# === core/md_writer.py ===
def _yaml_frontmatter(
    title: str,
    project: str | None,
    tags: list[str],
    created: datetime,
    source: str | None,
    language: str,
) -> str:
    lines = ["---"]
    # YAML strings are conservative - quote anything containing special chars.
    def yq(s: str) -> str:
        if not s:
            return '""'
        if any(c in s for c in [':', '#', '"', "'", '[', ']', '{', '}', ',', '&', '*', '!', '|', '>', '%', '@', '`']):
            escaped = s.replace('"', '\\"')
            return f'"{escaped}"'
        return s

    lines.append(f"title: {yq(title)}")
    if project:
        lines.append(f"project: {yq(project)}")
    lines.append(f"created: {created.isoformat()}")
    lines.append(f"language: {language}")
    if source:
        lines.append(f"source: {yq(source)}")
    if tags:
        lines.append("tags:")
        for tag in tags:
            lines.append(f"  - {yq(tag)}")
    lines.append("---")
    return "\n".join(lines)


def _render_section(section: Section, depth: int) -> str:
    """Render a section header at depth+2 (so top-level body sections are H2)."""
    level = min(6, depth + 2)
    parts = [f"{'#' * level} {section.heading}"]
    if section.content.strip():
        parts.append("")
        parts.append(section.content.strip())
    for child in section.children:
        parts.append("")
        parts.append(_render_section(child, depth + 1))
    return "\n".join(parts)


def _render_decisions(decisions: list[Decision], lang: str) -> str:
    if not decisions:
        return ""
    parts = [f"## {t('section.decisions', lang)}", ""]
    for d in decisions:
        parts.append(f"### {d.title}" + (f" - _{d.when}_" if d.when else ""))
        parts.append("")
        parts.append(f"**{t('decision.chose', lang)}**: {d.chose}")
        parts.append("")
        parts.append(f"**{t('decision.why', lang)}**: {d.why}")
        if d.rejected:
            parts.append("")
            parts.append(f"**{t('decision.rejected', lang)}**:")
            for r in d.rejected:
                parts.append(f"- {r}")
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def _render_bullets(heading: str, items: list[str]) -> str:
    if not items:
        return ""
    parts = [f"## {heading}", ""]
    for item in items:
        parts.append(f"- {item}")
    return "\n".join(parts) + "\n"


def render_markdown(
    *,
    title: str,
    summary: str,
    sections: list[Section],
    project: str | None,
    decisions: list[Decision],
    open_questions: list[str],
    next_steps: list[str],
    tags: list[str],
    source: str | None,
    language: str,
    created: datetime | None = None,
) -> str:
    """Assemble a flowing markdown document with progressive depth.

    Layout:
        YAML frontmatter
        # Title
        TL;DR (summary, plain prose)
        ## Summary section heading is implicit - the summary sits right under the title
        Body sections (each `Section` becomes ## with optional ###/#### children)
        ## Key decisions   (only if any)
        ## Open questions  (only if any)
        ## Next steps      (only if any)
        Footer note
    """
    created = created or datetime.now(timezone.utc).replace(microsecond=0)
    parts: list[str] = [
        _yaml_frontmatter(title, project, tags, created, source, language),
        "",
        f"# {title}",
        "",
        f"> {summary.strip()}",
        "",
    ]

    # Body sections - flowing prose by design. Reader scans the H2s, drills into
    # H3/H4 if interested. Top-level Section -> H2.
    for section in sections:
        parts.append(_render_section(section, depth=0))
        parts.append("")

    decision_block = _render_decisions(decisions, language)
    if decision_block:
        parts.append(decision_block)

    open_q_block = _render_bullets(t("section.open_questions", language), open_questions)
    if open_q_block:
        parts.append(open_q_block)

    steps_block = _render_bullets(t("section.next_steps", language), next_steps)
    if steps_block:
        parts.append(steps_block)

    parts.append("---")
    parts.append("")
    parts.append(f"_{t('footer.note', language)}_")
    parts.append("")
    return "\n".join(parts)

# === core/html_writer.py ===
def _escape_block(md: str) -> str:
    """Very small markdown→HTML - handles headings, bullet lists, paragraphs, and bold/italic.

    For full-featured rendering, install `markdown` and use `_with_markdown_lib` below.
    """
    out_lines: list[str] = []
    in_list = False
    for raw_line in md.splitlines():
        line = raw_line.rstrip()
        if not line.strip():
            if in_list:
                out_lines.append("</ul>")
                in_list = False
            out_lines.append("")
            continue
        # Headings
        m = 0
        while m < len(line) and line[m] == "#":
            m += 1
        if m and m <= 6 and line[m : m + 1] == " ":
            if in_list:
                out_lines.append("</ul>")
                in_list = False
            out_lines.append(f"<h{m}>{html.escape(line[m + 1 :].strip())}</h{m}>")
            continue
        # Bullets
        if line.lstrip().startswith(("- ", "* ")):
            if not in_list:
                out_lines.append("<ul>")
                in_list = True
            text = line.lstrip()[2:]
            out_lines.append(f"<li>{_inline(text)}</li>")
            continue
        # Blockquote
        if line.startswith(">"):
            if in_list:
                out_lines.append("</ul>")
                in_list = False
            out_lines.append(f"<blockquote>{_inline(line[1:].strip())}</blockquote>")
            continue
        # Horizontal rule
        if line.strip() == "---":
            if in_list:
                out_lines.append("</ul>")
                in_list = False
            out_lines.append("<hr>")
            continue
        # Plain paragraph
        if in_list:
            out_lines.append("</ul>")
            in_list = False
        out_lines.append(f"<p>{_inline(line)}</p>")

    if in_list:
        out_lines.append("</ul>")
    return "\n".join(out_lines)


def _inline(text: str) -> str:
    """Inline markdown: **bold**, *italic*, `code`, [link](url)."""
    import re

    s = html.escape(text)
    s = re.sub(r"\*\*([^\*]+)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"(?<!\w)\*([^\*]+)\*(?!\w)", r"<em>\1</em>", s)
    s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
    s = re.sub(
        r"\[([^\]]+)\]\(([^)]+)\)",
        lambda m: f'<a href="{html.escape(m.group(2))}">{m.group(1)}</a>',
        s,
    )
    return s


_HTML_TEMPLATE = """<!doctype html>
<html lang="{lang}">
<head>
  <meta charset="utf-8">
  <title>{title}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {{
      max-width: 760px; margin: 40px auto; padding: 0 20px;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      color: #1d1d1f; line-height: 1.6;
    }}
    h1 {{ font-size: 32px; margin: 0 0 8px; }}
    h2 {{ font-size: 22px; margin: 28px 0 8px; border-bottom: 1px solid #e5e5e7; padding-bottom: 6px; }}
    h3 {{ font-size: 17px; margin: 20px 0 6px; }}
    h4 {{ font-size: 15px; margin: 16px 0 4px; }}
    blockquote {{ border-left: 3px solid #ffb084; margin: 8px 0 14px; padding: 4px 12px; color: #444; background: #fff8f3; border-radius: 0 6px 6px 0; }}
    code {{ background: #f4f4f5; padding: 1px 4px; border-radius: 4px; font-family: ui-monospace, "Cascadia Code", Menlo, monospace; }}
    a {{ color: #d4651a; text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    hr {{ border: 0; border-top: 1px solid #e5e5e7; margin: 28px 0; }}
    .pf-meta {{ color: #6e6e73; font-size: 13px; margin-bottom: 16px; }}
    ul {{ padding-left: 22px; }}
    li {{ margin: 4px 0; }}
  </style>
</head>
<body>
{body}
</body>
</html>
"""


def render_html(
    markdown_source: str, *, title: str, language: str = "en", meta_line: str | None = None
) -> str:
    # Strip the YAML frontmatter; HTML doesn't need it.
    lines = markdown_source.splitlines()
    if lines and lines[0].strip() == "---":
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                lines = lines[i + 1 :]
                break
    body_md = "\n".join(lines)
    body_html = _escape_block(body_md)
    if meta_line:
        body_html = f'<p class="pf-meta">{html.escape(meta_line)}</p>\n' + body_html
    return _HTML_TEMPLATE.format(
        lang=html.escape(language), title=html.escape(title), body=body_html
    )

# === core/docx_writer.py ===
def write_docx(markdown_source: str, *, output_path: Path, title: str) -> bool:
    try:
        from docx import Document
        from docx.shared import Pt
    except ImportError:
        return False

    doc = Document()
    # Slightly better default body font.
    style = doc.styles["Normal"]
    style.font.size = Pt(11)

    lines = markdown_source.splitlines()
    # Strip YAML frontmatter - docx readers don't care.
    if lines and lines[0].strip() == "---":
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                lines = lines[i + 1 :]
                break

    paragraph_buffer: list[str] = []

    def flush_paragraph():
        if not paragraph_buffer:
            return
        text = " ".join(paragraph_buffer).strip()
        if text:
            doc.add_paragraph(_strip_inline(text))
        paragraph_buffer.clear()

    for raw in lines:
        line = raw.rstrip()
        stripped = line.strip()
        if not stripped:
            flush_paragraph()
            continue
        # Headings
        m = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if m:
            flush_paragraph()
            level = len(m.group(1))
            doc.add_heading(_strip_inline(m.group(2)), level=min(level, 4))
            continue
        # Bullet
        if stripped.startswith(("- ", "* ")):
            flush_paragraph()
            doc.add_paragraph(_strip_inline(stripped[2:]), style="List Bullet")
            continue
        # Blockquote
        if stripped.startswith(">"):
            flush_paragraph()
            quote = doc.add_paragraph(_strip_inline(stripped[1:].strip()))
            quote.style = doc.styles["Intense Quote"] if "Intense Quote" in [s.name for s in doc.styles] else doc.styles["Normal"]
            continue
        # Horizontal rule
        if stripped == "---":
            flush_paragraph()
            doc.add_paragraph("─" * 40)
            continue
        paragraph_buffer.append(stripped)
    flush_paragraph()

    doc.save(str(output_path))
    return True


_INLINE_PATTERNS = [
    (re.compile(r"\*\*([^\*]+)\*\*"), r"\1"),
    (re.compile(r"(?<!\w)\*([^\*]+)\*(?!\w)"), r"\1"),
    (re.compile(r"`([^`]+)`"), r"\1"),
    (re.compile(r"\[([^\]]+)\]\([^)]+\)"), r"\1"),
]


def _strip_inline(text: str) -> str:
    """Remove markdown inline markers; docx body is plain runs.

    A richer renderer with bold/italic runs is left for v2 - most users edit
    the docx in Word and re-bold things to taste anyway.
    """
    out = text
    for pattern, repl in _INLINE_PATTERNS:
        out = pattern.sub(repl, out)
    return out

# === core/pdf_writer.py ===
def write_pdf(
    markdown_source: str,
    *,
    output_path: Path,
    title: str,
    language: str = "en",
    meta_line: str | None = None,
) -> bool:
    try:
        import weasyprint
    except ImportError:
        return False
    except Exception:
        return False

    html_doc = render_html(
        markdown_source, title=title, language=language, meta_line=meta_line
    )
    try:
        weasyprint.HTML(string=html_doc).write_pdf(str(output_path))
        return True
    except Exception:
        return False

# === core/build.py ===
def default_output_dir() -> Path:
    """Resolve the default output directory.

    Order: PAPERFORGE_OUTPUT_DIR env → ~/Documents/orzed-mcp/paperforge → ./paperforge-out.
    """
    env = os.getenv("PAPERFORGE_OUTPUT_DIR")
    if env:
        return Path(env).expanduser().resolve()
    home = Path.home()
    documents = home / "Documents"
    if documents.is_dir():
        return (documents / "orzed-mcp" / "paperforge").resolve()
    return Path.cwd() / "paperforge-out"


def _slugify(text: str) -> str:
    slug = re.sub(r"[^\w\s-]", "", text, flags=re.UNICODE).strip().lower()
    slug = re.sub(r"[\s_-]+", "-", slug)
    return slug.strip("-") or "document"


def _err(code: str, lang: str, en_key: str, *, hint_key: str | None = None) -> ErrorInfo:
    return ErrorInfo(
        code=code,
        message_en=t(en_key, "en"),
        message_tr=t(en_key, "tr"),
        hint=t(hint_key, lang) if hint_key else None,
    )


_SUMMARY_MAX_CHARS = 280
_SENTENCE_SPLIT = re.compile(r"(?<=[.!?])\s+")


def _has_content(section: Section) -> bool:
    if section.content.strip():
        return True
    return any(_has_content(child) for child in section.children)


def _derive_summary(sections: list[Section]) -> str:
    """Pull the first 1-2 sentences (or up to ~280 chars) from the first section with content."""
    for section in sections:
        text = section.content.strip()
        if not text:
            for child in section.children:
                text = child.content.strip()
                if text:
                    break
        if not text:
            continue
        sentences = [s for s in _SENTENCE_SPLIT.split(text) if s.strip()]
        picked = " ".join(sentences[:2]).strip() or text
        if len(picked) > _SUMMARY_MAX_CHARS:
            cut = picked[: _SUMMARY_MAX_CHARS - 3].rsplit(" ", 1)[0]
            picked = cut + "..."
        return picked
    return ""


def create_document(
    *,
    title: str,
    summary: str | None = None,
    sections: list[Section] | list[dict] | None = None,
    body: str | None = None,
    format: DocumentFormat = "md",
    project: str | None = None,
    decisions: list[Decision] | list[dict] | None = None,
    open_questions: list[str] | None = None,
    next_steps: list[str] | None = None,
    tags: list[str] | None = None,
    source: str | None = None,
    output_dir: str | Path | None = None,
    filename: str | None = None,
    language: str = "en",
) -> Result[DocumentArtifact]:
    """Build and write a document.

    `title` is mandatory. Provide either:
      - `sections`: an ordered list of {heading, content, children?} for structured docs, or
      - `body`: a single chunk of markdown prose for the simplest case (wrapped as one section).
    `summary` is optional; when omitted, the tool derives a 1-2 sentence summary from
    the first section that has content. Genuinely empty input (no sections, no body)
    is rejected with INVALID_INPUT - the tool will not fabricate content from nothing.
    """
    lang = normalize_lang(language)

    if not title or not title.strip():
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.empty_title"))

    section_models: list[Section] = []
    if sections:
        section_models = [Section.model_validate(s) for s in sections]
    elif body and body.strip():
        section_models = [Section(heading=title.strip(), content=body.strip())]

    if not section_models or not any(_has_content(s) for s in section_models):
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.no_content"))

    summary_clean = (summary or "").strip()
    if not summary_clean:
        summary_clean = _derive_summary(section_models)
    if not summary_clean:
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.empty_summary"))
    summary = summary_clean

    decision_models = [Decision.model_validate(d) for d in (decisions or [])]
    open_q = [q.strip() for q in (open_questions or []) if q and q.strip()]
    steps = [s.strip() for s in (next_steps or []) if s and s.strip()]
    tag_list = [tag.strip() for tag in (tags or []) if tag and tag.strip()]

    if format not in ("md", "html", "docx", "pdf"):
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.invalid_format"))

    created = datetime.now(timezone.utc).replace(microsecond=0)
    md_source = render_markdown(
        title=title,
        summary=summary,
        sections=section_models,
        project=project,
        decisions=decision_models,
        open_questions=open_q,
        next_steps=steps,
        tags=tag_list,
        source=source,
        language=lang,
        created=created,
    )

    out_dir = Path(output_dir).expanduser().resolve() if output_dir else default_output_dir()
    out_dir.mkdir(parents=True, exist_ok=True)
    base = filename or f"{created.strftime('%Y%m%d-%H%M%S')}-{_slugify(title)}"
    target = out_dir / f"{base}.{format}"

    try:
        if format == "md":
            target.write_text(md_source, encoding="utf-8")
        elif format == "html":
            html_str = render_html(
                md_source,
                title=title,
                language=lang,
                meta_line=(f"{project} · {created.isoformat()}" if project else created.isoformat()),
            )
            target.write_text(html_str, encoding="utf-8")
        elif format == "docx":
            ok = write_docx(md_source, output_path=target, title=title)
            if not ok:
                return Result(
                    ok=False,
                    error=_err(
                        "UNSUPPORTED",
                        lang,
                        "error.docx_missing",
                        hint_key="hint.install_docx",
                    ),
                    meta={"format": format},
                )
        elif format == "pdf":
            ok = write_pdf(
                md_source,
                output_path=target,
                title=title,
                language=lang,
                meta_line=(f"{project} · {created.isoformat()}" if project else created.isoformat()),
            )
            if not ok:
                return Result(
                    ok=False,
                    error=_err(
                        "UNSUPPORTED",
                        lang,
                        "error.pdf_missing",
                        hint_key="hint.install_pdf",
                    ),
                    meta={"format": format},
                )
    except OSError as exc:
        return Result(
            ok=False,
            error=_err("INTERNAL", lang, "error.write_failed"),
            meta={"detail": str(exc)},
        )

    artifact = DocumentArtifact(
        title=title,
        format=format,
        file_path=str(target),
        byte_length=target.stat().st_size,
        sections_count=len(section_models),
        decisions_count=len(decision_models),
        open_questions_count=len(open_q),
        next_steps_count=len(steps),
        preview_md=md_source,
    )
    return Result(
        ok=True,
        data=artifact,
        meta={
            "output_dir": str(out_dir),
            "filename": target.name,
            "created": created.isoformat(),
        },
    )

# === core/render.py ===
def to_markdown(result: Result[DocumentArtifact], lang: str = "en") -> str:
    if not result.ok or result.data is None:
        if result.error is None:
            return f"**Error**: unknown failure (lang={lang})"
        msg = result.error.message_tr if lang == "tr" else result.error.message_en
        body = f"**Error** ({result.error.code}): {msg}"
        if result.error.hint:
            body += f"\n\n_Hint: {result.error.hint}_"
        return body

    a = result.data
    parts = [
        f"# {t('title', lang)} - `{a.format}`",
        "",
        f"**{a.title}**",
        "",
        f"- **{t('label.file_path', lang)}**: `{a.file_path}`",
        f"- **{t('label.size', lang)}**: `{a.byte_length}` bytes",
        f"- **{t('label.sections', lang)}**: {a.sections_count}  •  "
        f"**{t('label.decisions', lang)}**: {a.decisions_count}  •  "
        f"**{t('label.questions', lang)}**: {a.open_questions_count}  •  "
        f"**{t('label.steps', lang)}**: {a.next_steps_count}",
        "",
        "---",
        "",
        a.preview_md,
    ]
    return "\n".join(parts)

# === owui/_wrapper.py ===
class Tools:
    class Valves(BaseModel):
        DEFAULT_LANGUAGE: str = Field(
            default="en",
            description="Output language. 'en' or 'tr'.",
        )
        DEFAULT_FORMAT: str = Field(
            default="md",
            description="Default output format if the LLM doesn't specify (md/html/docx/pdf).",
        )
        DEFAULT_PROJECT: str = Field(
            default="",
            description="Optional project tag used when the caller doesn't pass `project`.",
        )
        OUTPUT_DIR: str = Field(
            default="",
            description=(
                "Override the save directory. Empty falls back to "
                "PAPERFORGE_OUTPUT_DIR env, then ~/Documents/orzed-mcp/paperforge."
            ),
        )

    def __init__(self):
        self.valves = self.Valves()
        self.citation = False

    def _lang(self, language):
        return (language or self.valves.DEFAULT_LANGUAGE or "en").strip()

    def create_document(
        self,
        title: str,
        body: str | None = None,
        summary: str | None = None,
        sections: list[dict] | None = None,
        format: str | None = None,
        project: str | None = None,
        decisions: list[dict] | None = None,
        open_questions: list[str] | None = None,
        next_steps: list[str] | None = None,
        tags: list[str] | None = None,
        source: str | None = None,
        filename: str | None = None,
        language: str | None = None,
    ) -> str:
        """
        Create and save a document file - markdown, HTML, DOCX, or PDF.

        Simplest call: `title` plus `body` (one markdown chunk). For richer docs
        pass structured `sections`, `decisions`, `open_questions`, `next_steps`.
        Synthesize a real title from the user's request; "Untitled" stubs are refused.

        When to use:
        - "save this as a doc"     / "bunu doküman yap"
        - "create a markdown file" / "md dosyası oluştur"
        - "export to PDF / docx"   / "PDF / docx olarak kaydet"
        - User wants a downloadable, shareable, or Obsidian-importable file.

        When NOT to use:
        - User just wants an inline summary in chat
        - User asks for a QR code, flight search, news brief - those tools save themselves

        :param title: REQUIRED. Synthesize from the request - no "Untitled" stubs.
        :param body: OPTIONAL. The whole doc body as one markdown string (simplest).
        :param summary: OPTIONAL. Derived from first section's content if omitted.
        :param sections: OPTIONAL list of {heading, content, children?} for structured docs.
        :param format: 'md' (default), 'html', 'docx', or 'pdf'.
        :param decisions: OPTIONAL list of {title, chose, why, rejected?, when?}.
        """
        lang = self._lang(language)
        fmt = format or self.valves.DEFAULT_FORMAT or "md"
        result = create_document(
            title=title,
            body=body,
            summary=summary,
            sections=sections,
            format=fmt,
            project=project or (self.valves.DEFAULT_PROJECT or None),
            decisions=decisions,
            open_questions=open_questions,
            next_steps=next_steps,
            tags=tags,
            source=source,
            output_dir=(self.valves.OUTPUT_DIR or None),
            filename=filename,
            language=lang,
        )
        return to_markdown(result, lang=lang)

