"""
title: SignalBrief
description: Aggregate, dedupe, and score recent news from a curated set of RSS/Atom feeds. Token-level keyword matching, recency boost, and per-source weighting.
author: Orzed, LLC
version: 1.0.0
required_open_webui_version: 0.5.0
"""

# ────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED BY tools/bundle_owui.py — DO NOT EDIT BY HAND.
# Source of truth: this tool's core/ and owui/_wrapper.py.
# Run `make bundle` (or `python tools/bundle_owui.py <tool>`) to regenerate.
# CI runs `make check-bundle` and fails on drift.
# ────────────────────────────────────────────────────────────────────────────

import httpx
import re
import xml.etree.ElementTree as ET
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
from datetime import datetime, timedelta, timezone
from datetime import datetime, timezone
from email.utils import parsedate_to_datetime
from pydantic import BaseModel, Field
from typing import Final
from typing import Generic, Literal, TypeVar

# === core/types.py ===
T = TypeVar("T", bound=BaseModel)

ErrorCode = Literal[
    "INVALID_INPUT",
    "NOT_FOUND",
    "RATE_LIMITED",
    "NETWORK_TIMEOUT",
    "UPSTREAM_ERROR",
    "UNSUPPORTED",
    "PARSE_ERROR",
    "TIMEOUT",
    "CANCELLED",
    "INTERNAL",
]


class ErrorInfo(BaseModel):
    code: ErrorCode
    message_en: str
    message_tr: str
    hint: str | None = None
    upstream: str | None = None
    retry_after_s: float | None = None


class Result(BaseModel, Generic[T]):
    ok: bool
    data: T | None = None
    error: ErrorInfo | None = None
    meta: dict = Field(default_factory=dict)


class NewsItem(BaseModel):
    title: str
    link: str | None = None
    summary: str | None = None
    source: str
    published: datetime | None = None
    score: int = 0
    matched_keywords: list[str] = Field(default_factory=list)


class SourceFailure(BaseModel):
    name: str
    url: str
    error: str


class NewsBrief(BaseModel):
    items: list[NewsItem]
    sources_used: list[str]
    failed_sources: list[SourceFailure] = Field(default_factory=list)
    keywords: list[str]
    hours_back: int


class SourceInfo(BaseModel):
    name: str
    url: str
    language: str | None = None


class SourceCatalog(BaseModel):
    sources: list[SourceInfo]

# === core/i18n.py ===
STRINGS: Final[dict[str, dict[str, str]]] = {
    "en": {
        "title": "SignalBrief",
        "label.window": "Window",
        "label.hours_back": "hours back",
        "label.sources": "Sources",
        "label.keywords": "Keywords",
        "label.failed": "Failed sources",
        "label.no_items": "No matching items.",
        "error.empty_keywords": "No keywords resolved (after filtering).",
        "error.empty_sources": "No source feeds resolved (after filtering).",
        "error.invalid_hours": "hours_back must be 1-336.",
        "hint.lower_min_score": "Lower min_score, widen hours_back, or add more keywords.",
        "note.brief": "Items are scored by token-level matches and recency. Subtitle: source name.",
    },
    "tr": {
        "title": "SignalBrief",
        "label.window": "Pencere",
        "label.hours_back": "saat önce",
        "label.sources": "Kaynaklar",
        "label.keywords": "Anahtar kelimeler",
        "label.failed": "Başarısız kaynaklar",
        "label.no_items": "Eşleşen öğe yok.",
        "error.empty_keywords": "Süzme sonrası anahtar kelime kalmadı.",
        "error.empty_sources": "Süzme sonrası kaynak kalmadı.",
        "error.invalid_hours": "hours_back 1-336 aralığında olmalı.",
        "hint.lower_min_score": "min_score'u düşür, hours_back'i genişlet veya daha fazla kelime ekle.",
        "note.brief": "Öğeler token düzeyi eşleşmeler ve tazeliğe göre puanlanır.",
    },
}

SUPPORTED: Final[tuple[str, ...]] = ("en", "tr")
DEFAULT: Final[str] = "en"


def normalize_lang(lang: str | None) -> str:
    if not lang:
        return DEFAULT
    base = lang.lower().split("-")[0]
    return base if base in SUPPORTED else DEFAULT


def t(key: str, lang: str = DEFAULT, **kwargs: object) -> str:
    lang = normalize_lang(lang)
    table = STRINGS.get(lang) or STRINGS[DEFAULT]
    template = table.get(key) or STRINGS[DEFAULT].get(key) or key
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError):
        return template

# === core/sources.py ===
DEFAULT_SOURCES: list[dict[str, str | None]] = [
    {"name": "Hacker News (top)", "url": "https://news.ycombinator.com/rss", "language": "en"},
    {"name": "TechCrunch", "url": "https://techcrunch.com/feed/", "language": "en"},
    {"name": "MIT Tech Review", "url": "https://www.technologyreview.com/feed/", "language": "en"},
    {"name": "arXiv cs.AI", "url": "https://export.arxiv.org/rss/cs.AI", "language": "en"},
    {"name": "BBC World", "url": "http://feeds.bbci.co.uk/news/world/rss.xml", "language": "en"},
    {"name": "NPR Tech", "url": "https://feeds.npr.org/1019/rss.xml", "language": "en"},
    {"name": "The Guardian Tech", "url": "https://www.theguardian.com/uk/technology/rss", "language": "en"},
    {"name": "Al Jazeera", "url": "https://www.aljazeera.com/xml/rss/all.xml", "language": "en"},
    {"name": "Euronews", "url": "https://www.euronews.com/rss?level=theme&name=news", "language": "en"},
    {"name": "ShiftDelete", "url": "https://shiftdelete.net/feed", "language": "tr"},
    {"name": "DonanımHaber", "url": "https://www.donanimhaber.com/rss/tum/", "language": "tr"},
    {"name": "Webrazzi", "url": "https://webrazzi.com/feed/", "language": "tr"},
]

DEFAULT_KEYWORDS: list[str] = [
    "ai", "llm", "machine learning", "deep learning", "neural network",
    "openai", "anthropic", "google", "deepmind", "mistral", "huggingface",
    "model", "agent", "robotics",
    "saas", "startup", "venture", "ipo", "acquisition", "funding",
]

# Editable source-boost map. Match is case-insensitive substring on the source name.
SOURCE_BOOSTS: dict[str, int] = {
    "openai": 1,
    "anthropic": 1,
    "deepmind": 1,
    "mit tech review": 1,
    "arxiv": 1,
    "hacker news": 1,
    "techcrunch": 1,
}


def boost_for(source_name: str) -> int:
    lower = (source_name or "").lower()
    for key, val in SOURCE_BOOSTS.items():
        if key in lower:
            return val
    return 0


def dedupe_sources(sources: list[dict]) -> list[dict]:
    seen = set()
    out = []
    for src in sources:
        url = (src.get("url") or "").strip().lower()
        if not url or url in seen:
            continue
        seen.add(url)
        out.append(src)
    return out

# === core/tokens.py ===
WORD_RE = re.compile(r"\w+", re.UNICODE)


def tokenize(text: str) -> list[str]:
    if not text:
        return []
    return [m.group(0).lower() for m in WORD_RE.finditer(text)]


def keyword_matches(haystack_tokens: list[str], keyword: str) -> int:
    """Count occurrences of `keyword` (potentially multi-word) in tokenized haystack.

    Multi-word keywords match adjacent token runs.
    """
    kw_tokens = tokenize(keyword)
    if not kw_tokens:
        return 0
    if len(kw_tokens) == 1:
        target = kw_tokens[0]
        return sum(1 for tok in haystack_tokens if tok == target)
    n = len(kw_tokens)
    count = 0
    for i in range(len(haystack_tokens) - n + 1):
        if haystack_tokens[i : i + n] == kw_tokens:
            count += 1
    return count

# === core/feed.py ===
NAMESPACES = {
    "atom": "http://www.w3.org/2005/Atom",
    "content": "http://purl.org/rss/1.0/modules/content/",
    "dc": "http://purl.org/dc/elements/1.1/",
    "media": "http://search.yahoo.com/mrss/",
}

HTML_TAG_RE = re.compile(r"<[^>]+>")
WS_RE = re.compile(r"\s+")


def _strip_html(text: str | None) -> str:
    if not text:
        return ""
    return WS_RE.sub(" ", HTML_TAG_RE.sub(" ", text)).strip()


def _parse_date(raw: str | None) -> datetime | None:
    if not raw:
        return None
    raw = raw.strip()
    try:
        dt = parsedate_to_datetime(raw)
        if dt and dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt
    except (TypeError, ValueError):
        pass
    try:
        return datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError:
        return None


def _findtext(element, *paths) -> str | None:
    for path in paths:
        value = element.findtext(path, namespaces=NAMESPACES)
        if value:
            return value.strip()
    return None


def _find(element, *paths):
    for path in paths:
        e = element.find(path, namespaces=NAMESPACES)
        if e is not None:
            return e
    return None


def parse_feed(content: str) -> list[dict]:
    """Parse an RSS 2.0 or Atom 1.0 feed. Returns a list of item dicts."""
    try:
        root = ET.fromstring(content)
    except ET.ParseError:
        return []

    out: list[dict] = []
    items = root.findall(".//item") or root.findall(".//atom:entry", NAMESPACES)
    for item in items:
        title = _findtext(item, "title", "atom:title")
        link = _findtext(item, "link", "atom:link")
        if not link:
            link_e = _find(item, "atom:link")
            if link_e is not None:
                link = link_e.attrib.get("href")
        summary = _strip_html(
            _findtext(item, "description", "summary", "atom:summary", "content:encoded")
        )
        published = _parse_date(
            _findtext(item, "pubDate", "atom:published", "atom:updated", "dc:date")
        )
        guid = _findtext(item, "guid", "atom:id") or link
        if not title and not link:
            continue
        out.append(
            {
                "title": (title or "").strip(),
                "link": (link or "").strip() or None,
                "summary": summary or None,
                "published": published,
                "guid": (guid or "").strip(),
            }
        )
    return out


def fetch_feed_text(client: httpx.Client, url: str) -> str:
    """Fetch a URL and decode using declared charset → charset-normalizer fallback."""
    r = client.get(url)
    r.raise_for_status()
    raw = r.content or b""
    declared = r.encoding
    if declared:
        try:
            return raw.decode(declared, errors="replace")
        except (LookupError, UnicodeDecodeError):
            pass
    try:
        from charset_normalizer import from_bytes

        result = from_bytes(raw).best()
        if result:
            return str(result)
    except Exception:
        pass
    return raw.decode("utf-8", errors="replace")

# === core/brief.py ===
def _err(code: str, lang: str, en_key: str, *, hint_key: str | None = None) -> ErrorInfo:
    return ErrorInfo(
        code=code,
        message_en=t(en_key, "en"),
        message_tr=t(en_key, "tr"),
        hint=t(hint_key, lang) if hint_key else None,
    )


def _resolve_sources(custom: list[dict] | None) -> list[dict]:
    if custom:
        cleaned = [s for s in custom if isinstance(s, dict) and s.get("url")]
        return dedupe_sources(cleaned)
    return dedupe_sources(DEFAULT_SOURCES)


def _resolve_keywords(custom: list[str] | None) -> list[str]:
    if custom:
        return [k.strip() for k in custom if k and k.strip()]
    return list(DEFAULT_KEYWORDS)


def _score(item: dict, source_name: str, keyword_tokens: dict[str, list[str]]) -> tuple[int, list[str]]:
    title = item.get("title") or ""
    summary = item.get("summary") or ""
    haystack_title = tokenize(title)
    haystack_full = tokenize(title + " " + summary)
    score = 0
    matched: list[str] = []
    for kw, kw_toks in keyword_tokens.items():
        if not kw_toks:
            continue
        title_hits = keyword_matches(haystack_title, kw)
        body_hits = keyword_matches(haystack_full, kw) - title_hits
        local = title_hits * 5 + body_hits
        if local > 0:
            score += local
            matched.append(kw)

    pub = item.get("published")
    if isinstance(pub, datetime):
        now = datetime.now(timezone.utc)
        try:
            age = now - pub
            if age <= timedelta(hours=12):
                score += 3
            elif age <= timedelta(hours=24):
                score += 2
            elif age <= timedelta(hours=72):
                score += 1
        except TypeError:
            pass

    score += boost_for(source_name)
    return score, matched


def _fetch_one(client: httpx.Client, source: dict) -> tuple[dict, list[dict] | None, str | None]:
    try:
        text = fetch_feed_text(client, source["url"])
        items = parse_feed(text)
        return source, items, None
    except Exception as exc:
        return source, None, f"{type(exc).__name__}: {exc}"


def list_sources(*, language: str = "en") -> Result[SourceCatalog]:
    catalog = SourceCatalog(
        sources=[
            SourceInfo(
                name=str(src["name"]),
                url=str(src["url"]),
                language=src.get("language"),
            )
            for src in dedupe_sources(DEFAULT_SOURCES)
        ]
    )
    return Result(ok=True, data=catalog, meta={"count": len(catalog.sources)})


def collect(
    topics: list[str] | None = None,
    sources: list[dict] | None = None,
    hours: int = 24,
    max_per_source: int = 10,
    min_score: int = 2,
    *,
    language: str = "en",
    client=None,
) -> Result[NewsBrief]:
    lang = normalize_lang(language)
    if hours < 1 or hours > 336:
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.invalid_hours"))

    keywords = _resolve_keywords(topics)
    feeds = _resolve_sources(sources)
    if not keywords:
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.empty_keywords"))
    if not feeds:
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.empty_sources"))

    keyword_tokens = {kw: tokenize(kw) for kw in keywords}
    cutoff = datetime.now(timezone.utc) - timedelta(hours=hours)

    own_client = client is None
    if client is None:
        client = httpx.Client(
            timeout=8.0,
            follow_redirects=True,
            headers={"User-Agent": "orzed-signalbrief/1.0"},
        )

    aggregate: list[NewsItem] = []
    failures: list[SourceFailure] = []
    sources_used: list[str] = []
    seen_keys: set[str] = set()

    try:
        with ThreadPoolExecutor(max_workers=min(8, len(feeds))) as pool:
            futures = [pool.submit(_fetch_one, client, src) for src in feeds]
            for fut in futures:
                src, items, error = fut.result()
                src_name = str(src.get("name") or src.get("url"))
                if error:
                    failures.append(
                        SourceFailure(
                            name=src_name,
                            url=str(src.get("url") or ""),
                            error=error,
                        )
                    )
                    continue
                sources_used.append(src_name)
                items_for_source = 0
                for raw in items or []:
                    pub = raw.get("published")
                    if isinstance(pub, datetime) and pub < cutoff:
                        continue
                    key = (raw.get("link") or raw.get("guid") or raw.get("title") or "").strip().lower()
                    if not key or key in seen_keys:
                        continue
                    seen_keys.add(key)
                    score, matched = _score(raw, src_name, keyword_tokens)
                    if score < min_score:
                        continue
                    aggregate.append(
                        NewsItem(
                            title=raw.get("title") or "(untitled)",
                            link=raw.get("link"),
                            summary=raw.get("summary"),
                            source=src_name,
                            published=pub if isinstance(pub, datetime) else None,
                            score=score,
                            matched_keywords=matched,
                        )
                    )
                    items_for_source += 1
                    if items_for_source >= max_per_source:
                        break
    finally:
        if own_client:
            client.close()

    aggregate.sort(key=lambda n: (-n.score, n.title))
    brief = NewsBrief(
        items=aggregate,
        sources_used=sources_used,
        failed_sources=failures,
        keywords=keywords,
        hours_back=hours,
    )
    return Result(
        ok=True,
        data=brief,
        meta={
            "item_count": len(aggregate),
            "sources_ok": len(sources_used),
            "sources_failed": len(failures),
        },
    )

# === core/render.py ===
def to_markdown(result: Result, lang: str = "en") -> str:
    if not result.ok or result.data is None:
        if result.error is None:
            return f"**Error**: unknown failure (lang={lang})"
        msg = result.error.message_tr if lang == "tr" else result.error.message_en
        body = f"**Error** ({result.error.code}): {msg}"
        if result.error.hint:
            body += f"\n\n_Hint: {result.error.hint}_"
        return body

    data = result.data
    if isinstance(data, NewsBrief):
        return _render_brief(data, lang)
    if isinstance(data, SourceCatalog):
        return _render_catalog(data, lang)
    return f"**Result**: {data}"


def _render_brief(brief: NewsBrief, lang: str) -> str:
    parts: list[str] = [
        f"# {t('title', lang)}",
        "",
        f"**{t('label.window', lang)}**: `{brief.hours_back}` {t('label.hours_back', lang)}",
        f"**{t('label.sources', lang)}**: {len(brief.sources_used)}  •  "
        f"**{t('label.keywords', lang)}**: "
        f"{', '.join(f'`{k}`' for k in brief.keywords[:8])}"
        + (" …" if len(brief.keywords) > 8 else ""),
    ]
    if not brief.items:
        parts += ["", f"_{t('label.no_items', lang)}_"]
    else:
        parts.append("")
        for item in brief.items:
            line = f"- **[{item.title}]({item.link or '#'})** · _{item.source}_ · score `{item.score}`"
            if item.matched_keywords:
                line += " · " + ", ".join(f"`{k}`" for k in item.matched_keywords)
            parts.append(line)
            if item.summary:
                snippet = item.summary[:200] + ("…" if len(item.summary) > 200 else "")
                parts.append(f"  {snippet}")

    if brief.failed_sources:
        parts += [
            "",
            f"**{t('label.failed', lang)}**: " + ", ".join(
                f"`{f.name}` ({f.error})" for f in brief.failed_sources[:6]
            ),
        ]
    parts += ["", f"_{t('note.brief', lang)}_"]
    return "\n".join(parts)


def _render_catalog(cat: SourceCatalog, lang: str) -> str:
    parts = [f"# {t('title', lang)} — {t('label.sources', lang)}", ""]
    for src in cat.sources:
        suffix = f" · `{src.language}`" if src.language else ""
        parts.append(f"- **{src.name}** — `{src.url}`{suffix}")
    return "\n".join(parts)

# === owui/_wrapper.py ===
class Tools:
    class Valves(BaseModel):
        DEFAULT_LANGUAGE: str = Field(
            default="en",
            description="Output language. 'en' or 'tr'.",
        )
        DEFAULT_HOURS: int = Field(default=24, description="Default recency window (hours).")
        DEFAULT_MIN_SCORE: int = Field(default=2, description="Drop items below this score.")
        DEFAULT_MAX_PER_SOURCE: int = Field(default=10, description="Cap items kept per source.")

    def __init__(self):
        self.valves = self.Valves()
        self.citation = False

    def _lang(self, language: str | None) -> str:
        return (language or self.valves.DEFAULT_LANGUAGE or "en").strip()

    def collect(
        self,
        topics: list[str] | None = None,
        sources: list[dict] | None = None,
        hours: int | None = None,
        max_per_source: int | None = None,
        min_score: int | None = None,
        language: str | None = None,
    ) -> str:
        """Collect a scored news brief from RSS / Atom feeds.

        Use when: "AI haberleri özetle" / "tech news today" / "scan funding
        headlines". Skip for specific-article summaries (use pagesignal),
        Web search, real-time alerts, stock prices, or non-news topics.
        """
        lang = self._lang(language)
        result = collect(
            topics=topics,
            sources=sources,
            hours=hours if hours is not None else self.valves.DEFAULT_HOURS,
            max_per_source=max_per_source
            if max_per_source is not None
            else self.valves.DEFAULT_MAX_PER_SOURCE,
            min_score=min_score if min_score is not None else self.valves.DEFAULT_MIN_SCORE,
            language=lang,
        )
        return to_markdown(result, lang=lang)

    def list_sources(self, language: str | None = None) -> str:
        """Show the built-in default RSS / Atom source catalog.

        Use when: "what news sources do you cover" / "hangi kaynakları
        tarıyorsun". Skip if the user wants actual news - use `collect` instead.
        """
        lang = self._lang(language)
        return to_markdown(list_sources(language=lang), lang=lang)

