"""
title: AskUser
description: Interactive question prompt — single-select, multi-select, or free-text. Renders a polished animated overlay with keyboard navigation, focus trap, search filter for long lists, and respects prefers-reduced-motion.
author: Orzed, LLC
version: 1.0.0
required_open_webui_version: 0.5.0
"""

# ────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED BY tools/bundle_owui.py — DO NOT EDIT BY HAND.
# Source of truth: this tool's core/ and owui/_wrapper.py.
# Run `make bundle` (or `python tools/bundle_owui.py <tool>`) to regenerate.
# CI runs `make check-bundle` and fails on drift.
# ────────────────────────────────────────────────────────────────────────────

import json
from pydantic import BaseModel, Field
from typing import Any
from typing import Final
from typing import Generic, Literal, TypeVar
from typing import Literal

# === core/types.py ===
T = TypeVar("T", bound=BaseModel)

ErrorCode = Literal[
    "INVALID_INPUT",
    "NOT_FOUND",
    "RATE_LIMITED",
    "NETWORK_TIMEOUT",
    "UPSTREAM_ERROR",
    "UNSUPPORTED",
    "PARSE_ERROR",
    "TIMEOUT",
    "CANCELLED",
    "INTERNAL",
]

AskMode = Literal["single", "multi", "free_text"]
AnswerType = Literal["select", "custom", "skip", "timeout", "cancelled"]


class ErrorInfo(BaseModel):
    code: ErrorCode
    message_en: str
    message_tr: str
    hint: str | None = None
    upstream: str | None = None
    retry_after_s: float | None = None


class Result(BaseModel, Generic[T]):
    ok: bool
    data: T | None = None
    error: ErrorInfo | None = None
    meta: dict = Field(default_factory=dict)


class Option(BaseModel):
    label: str
    description: str | None = None
    value: str | None = None  # defaults to label


class Question(BaseModel):
    """Type-checked container; `validate_question` enforces business rules.

    Pydantic stays type-only here so business errors flow through
    `Result(ok=False, error=...)` rather than raising ValidationError at
    construction time.
    """

    prompt: str
    options: list[Option] = Field(default_factory=list)
    mode: AskMode = "single"
    allow_custom: bool = True
    required: bool = False
    min_select: int | None = None
    max_select: int | None = None
    timeout_s: float = 300.0
    accent: str = "#E8713A"


class Answer(BaseModel):
    type: AnswerType
    indices: list[int] = Field(default_factory=list)
    values: list[str] = Field(default_factory=list)
    custom_text: str | None = None
    elapsed_ms: int = 0

# === core/i18n.py ===
STRINGS: Final[dict[str, dict[str, str]]] = {
    "en": {
        "title": "AskUser",
        "label.skip": "Skip",
        "label.cancel": "Cancel",
        "label.confirm": "Confirm",
        "label.search": "Search options…",
        "label.custom_input": "Or type a custom answer…",
        "label.no_answer": "User did not provide an answer.",
        "label.user_selected": "User selected",
        "label.user_typed": "User typed",
        "label.cancelled": "User cancelled.",
        "label.timeout": "Question timed out.",
        "label.no_display": "Cannot open a browser in this environment (no display).",
        "error.empty_prompt": "prompt is required.",
        "error.invalid_mode": "mode must be 'single', 'multi', or 'free_text'.",
        "error.options_required": "At least one option is required for select/multi modes.",
        "error.too_many_options": "options exceeds the 200-item limit.",
        "error.min_max": "min_select must be ≤ max_select and ≤ option count.",
        "error.invalid_timeout": "timeout_s must be in (0, 1800].",
        "error.no_display": (
            "No display detected; the askuser tool cannot open a browser. "
            "Run from a desktop session, or use askuser inside Open WebUI."
        ),
        "error.csrf": "CSRF token mismatch.",
        "hint.set_display": "Run from a session with $DISPLAY (Linux) or a normal desktop user.",
    },
    "tr": {
        "title": "AskUser",
        "label.skip": "Atla",
        "label.cancel": "İptal",
        "label.confirm": "Onayla",
        "label.search": "Seçenekleri ara…",
        "label.custom_input": "Veya kendi yanıtınızı yazın…",
        "label.no_answer": "Kullanıcı bir yanıt vermedi.",
        "label.user_selected": "Kullanıcı seçti",
        "label.user_typed": "Kullanıcı yazdı",
        "label.cancelled": "Kullanıcı iptal etti.",
        "label.timeout": "Soru zaman aşımına uğradı.",
        "label.no_display": "Bu ortamda tarayıcı açılamadı (ekran yok).",
        "error.empty_prompt": "prompt zorunlu.",
        "error.invalid_mode": "mode 'single', 'multi' veya 'free_text' olmalı.",
        "error.options_required": "select/multi modları için en az bir seçenek gerekli.",
        "error.too_many_options": "options 200 öğe sınırını aşıyor.",
        "error.min_max": "min_select ≤ max_select ve ≤ seçenek sayısı olmalı.",
        "error.invalid_timeout": "timeout_s (0, 1800] aralığında olmalı.",
        "error.no_display": (
            "Ekran bulunamadı; askuser tarayıcı açamaz. Masaüstü oturumundan "
            "çalıştırın veya Open WebUI içinde kullanın."
        ),
        "error.csrf": "CSRF token eşleşmiyor.",
        "hint.set_display": "Linux'ta $DISPLAY tanımlı bir oturum veya normal masaüstü kullanıcısı kullanın.",
    },
}

SUPPORTED: Final[tuple[str, ...]] = ("en", "tr")
DEFAULT: Final[str] = "en"


def normalize_lang(lang: str | None) -> str:
    if not lang:
        return DEFAULT
    base = lang.lower().split("-")[0]
    return base if base in SUPPORTED else DEFAULT


def t(key: str, lang: str = DEFAULT, **kwargs: object) -> str:
    lang = normalize_lang(lang)
    table = STRINGS.get(lang) or STRINGS[DEFAULT]
    template = table.get(key) or STRINGS[DEFAULT].get(key) or key
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError):
        return template

# === core/validate.py ===
def _err(en_key: str, lang: str) -> ErrorInfo:
    return ErrorInfo(
        code="INVALID_INPUT",
        message_en=t(en_key, "en"),
        message_tr=t(en_key, "tr"),
    )


def validate_question(q: Question, *, language: str = "en") -> ErrorInfo | None:
    lang = normalize_lang(language)
    if not q.prompt or not q.prompt.strip():
        return _err("error.empty_prompt", lang)
    if q.mode not in ("single", "multi", "free_text"):
        return _err("error.invalid_mode", lang)
    if q.mode in ("single", "multi") and not q.options:
        return _err("error.options_required", lang)
    if len(q.options) > 200:
        return _err("error.too_many_options", lang)
    if q.mode == "multi":
        if q.min_select is not None and q.max_select is not None:
            if q.min_select > q.max_select:
                return _err("error.min_max", lang)
        if q.min_select is not None and q.min_select > len(q.options):
            return _err("error.min_max", lang)
        if q.max_select is not None and q.max_select > len(q.options):
            return _err("error.min_max", lang)
    if q.timeout_s <= 0 or q.timeout_s > 1800:
        return _err("error.invalid_timeout", lang)
    return None

# === core/overlay.py ===
Mode = Literal["owui", "localhost"]


_BASE_CSS = """
* { box-sizing: border-box; }
:host, html, body { margin: 0; padding: 0; }
.au-backdrop {
  position: fixed; inset: 0; z-index: 99999;
  background: rgba(15, 17, 22, 0.78);
  display: flex; align-items: center; justify-content: center;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  color: #e5e9f0;
  animation: au-fade 0.18s ease-out;
}
@media (prefers-reduced-motion: reduce) {
  .au-backdrop, .au-card, .au-option { animation: none !important; transition: none !important; }
}
@keyframes au-fade { from { opacity: 0; } to { opacity: 1; } }
.au-card {
  background: #1e1e2e; border-radius: 14px; padding: 20px 22px 18px;
  width: min(560px, calc(100vw - 24px));
  max-height: 90vh; display: flex; flex-direction: column;
  box-shadow: 0 12px 40px rgba(0, 0, 0, 0.55);
  border: 1px solid rgba(205, 214, 244, 0.08);
  animation: au-pop 0.22s cubic-bezier(0.21, 1.02, 0.73, 1) both;
}
@keyframes au-pop { from { transform: translateY(8px) scale(0.98); opacity: 0; } to { transform: none; opacity: 1; } }
.au-prompt { font-size: 16px; line-height: 1.45; margin: 0 0 12px; font-weight: 500; }
.au-search {
  width: 100%; padding: 8px 10px; border-radius: 8px; border: 1px solid #45475a;
  background: #181825; color: inherit; font-size: 14px; margin: 0 0 10px;
}
.au-search::placeholder { color: #a6adc8; opacity: 0.85; }
.au-options { overflow-y: auto; max-height: 50vh; padding-right: 4px; margin: 0; padding-left: 0; list-style: none; }
.au-option {
  padding: 10px 12px; border-radius: 10px; cursor: pointer; min-height: 44px;
  display: flex; flex-direction: column; gap: 2px;
  background: #181825; margin-bottom: 6px;
  border: 1px solid transparent;
  transition: background-color 0.12s;
}
.au-option:hover, .au-option.au-focus { background: #313244; }
.au-option.au-selected { border-color: var(--au-accent); background: rgba(232, 113, 58, 0.12); }
.au-option-label { font-size: 14px; }
.au-option-desc { font-size: 12px; color: #a6adc8; }
.au-option-key { float: right; font-size: 11px; color: #a6adc8; opacity: 0.8; }
.au-custom { margin-top: 12px; }
.au-custom textarea {
  width: 100%; min-height: 64px; resize: vertical; padding: 8px 10px;
  border-radius: 8px; border: 1px solid #45475a; background: #181825; color: inherit;
  font-family: inherit; font-size: 14px;
}
.au-actions { display: flex; gap: 8px; justify-content: space-between; align-items: center; margin-top: 12px; }
.au-meta { font-size: 12px; color: #a6adc8; }
.au-btn {
  border: 0; padding: 9px 14px; border-radius: 8px; cursor: pointer;
  font-size: 14px; min-height: 36px; font-weight: 500;
}
.au-btn-primary { background: var(--au-accent); color: #1e1e2e; }
.au-btn-primary[disabled] { opacity: 0.4; cursor: not-allowed; }
.au-btn-ghost { background: transparent; color: #cdd6f4; }
.au-btn-ghost:hover { background: #313244; }
.au-warning { background: #f9e2af; color: #1e1e2e; padding: 6px 8px; border-radius: 8px; font-size: 12px; margin-bottom: 8px; }
@media (max-width: 640px) {
  .au-backdrop { align-items: flex-end; }
  .au-card { width: 100vw; max-height: 92vh; border-radius: 14px 14px 0 0; }
}
"""


def _js_payload(question: Question, lang: str, mode: Mode, csrf_token: str = "") -> str:
    options_payload = [
        {"label": o.label, "description": o.description, "value": o.value or o.label}
        for o in question.options
    ]
    config = {
        "prompt": question.prompt,
        "options": options_payload,
        "mode": question.mode,
        "allow_custom": question.allow_custom,
        "required": question.required,
        "min_select": question.min_select,
        "max_select": question.max_select,
        "timeout_s": question.timeout_s,
        "labels": {
            "skip": t("label.skip", lang),
            "cancel": t("label.cancel", lang),
            "confirm": t("label.confirm", lang),
            "search": t("label.search", lang),
            "custom_input": t("label.custom_input", lang),
        },
        "accent": question.accent,
        "csrf_token": csrf_token if mode == "localhost" else "",
    }
    return json.dumps(config, ensure_ascii=False)


_OVERLAY_JS_BODY = r"""
return (function() {
  return new Promise(function(resolve) {
    var CFG = __CONFIG__;
    var TRANSPORT = '__TRANSPORT__';

    var existing = document.getElementById('orzed-askuser-root');
    if (existing) existing.remove();

    var root = document.createElement('div');
    root.id = 'orzed-askuser-root';
    root.className = 'au-backdrop';
    root.style.setProperty('--au-accent', CFG.accent || '#E8713A');
    root.setAttribute('role', 'dialog');
    root.setAttribute('aria-modal', 'true');

    var card = document.createElement('div');
    card.className = 'au-card';
    root.appendChild(card);

    var promptEl = document.createElement('h2');
    promptEl.className = 'au-prompt';
    promptEl.id = 'au-prompt-id';
    promptEl.textContent = CFG.prompt;
    card.setAttribute('aria-labelledby', 'au-prompt-id');
    card.appendChild(promptEl);

    var elapsedStart = Date.now();
    var selected = new Set();
    var focusIdx = 0;
    var customInput = null;

    var optionsList = document.createElement('ul');
    optionsList.className = 'au-options';
    optionsList.setAttribute('role', CFG.mode === 'multi' ? 'listbox' : 'radiogroup');
    optionsList.setAttribute('aria-multiselectable', CFG.mode === 'multi' ? 'true' : 'false');
    card.appendChild(optionsList);

    var search = null;
    if (CFG.options && CFG.options.length > 10) {
      search = document.createElement('input');
      search.type = 'search';
      search.className = 'au-search';
      search.placeholder = CFG.labels.search;
      search.setAttribute('aria-label', CFG.labels.search);
      card.insertBefore(search, optionsList);
      search.addEventListener('input', renderOptions);
    }

    function visibleOptions() {
      var q = (search && search.value || '').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');
      if (!q) return CFG.options.map(function(o, i) { return { o: o, i: i }; });
      return CFG.options.map(function(o, i) { return { o: o, i: i }; }).filter(function(p) {
        var hay = (p.o.label + ' ' + (p.o.description || '')).toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');
        return hay.indexOf(q) !== -1;
      });
    }

    function renderOptions() {
      optionsList.innerHTML = '';
      var visible = visibleOptions();
      visible.forEach(function(pair, vIdx) {
        var li = document.createElement('li');
        li.className = 'au-option';
        li.tabIndex = -1;
        li.setAttribute('role', CFG.mode === 'multi' ? 'option' : 'radio');
        if (selected.has(pair.i)) {
          li.classList.add('au-selected');
          li.setAttribute('aria-selected', 'true');
        }
        if (vIdx === focusIdx) li.classList.add('au-focus');

        var lblEl = document.createElement('div');
        lblEl.className = 'au-option-label';
        lblEl.textContent = pair.o.label;
        if (vIdx < 9) {
          var key = document.createElement('span');
          key.className = 'au-option-key';
          key.textContent = String(vIdx + 1);
          lblEl.appendChild(key);
        }
        li.appendChild(lblEl);

        if (pair.o.description) {
          var desc = document.createElement('div');
          desc.className = 'au-option-desc';
          desc.textContent = pair.o.description;
          li.appendChild(desc);
        }
        li.addEventListener('click', function() { onPick(pair.i); });
        optionsList.appendChild(li);
      });
      updateConfirmEnabled();
    }

    var actions = document.createElement('div');
    actions.className = 'au-actions';
    var meta = document.createElement('span');
    meta.className = 'au-meta';
    actions.appendChild(meta);

    var btnGroup = document.createElement('div');
    btnGroup.style.display = 'flex';
    btnGroup.style.gap = '8px';

    var btnSkip = null;
    if (!CFG.required) {
      btnSkip = document.createElement('button');
      btnSkip.className = 'au-btn au-btn-ghost';
      btnSkip.textContent = CFG.labels.skip;
      btnSkip.addEventListener('click', function() { finish('skip'); });
      btnGroup.appendChild(btnSkip);
    }
    var btnCancel = document.createElement('button');
    btnCancel.className = 'au-btn au-btn-ghost';
    btnCancel.textContent = CFG.labels.cancel;
    btnCancel.addEventListener('click', function() { finish('cancelled'); });
    btnGroup.appendChild(btnCancel);

    var btnConfirm = document.createElement('button');
    btnConfirm.className = 'au-btn au-btn-primary';
    btnConfirm.textContent = CFG.labels.confirm;
    btnConfirm.addEventListener('click', function() { confirmSelection(); });
    btnGroup.appendChild(btnConfirm);

    actions.appendChild(btnGroup);
    card.appendChild(actions);

    if (CFG.mode === 'free_text' || CFG.allow_custom) {
      customInput = document.createElement('div');
      customInput.className = 'au-custom';
      var ta = document.createElement('textarea');
      ta.placeholder = CFG.labels.custom_input;
      ta.setAttribute('aria-label', CFG.labels.custom_input);
      customInput.appendChild(ta);
      customInput._ta = ta;
      card.insertBefore(customInput, actions);
    }

    function onPick(idx) {
      if (CFG.mode === 'single') {
        selected.clear(); selected.add(idx); confirmSelection();
        return;
      }
      if (CFG.mode === 'multi') {
        if (selected.has(idx)) selected.delete(idx); else selected.add(idx);
        renderOptions();
      }
    }

    function updateConfirmEnabled() {
      if (CFG.mode === 'free_text') {
        btnConfirm.disabled = false;
        return;
      }
      var ok = true;
      if (CFG.mode === 'multi') {
        var n = selected.size;
        if (CFG.min_select && n < CFG.min_select) ok = false;
        if (CFG.max_select && n > CFG.max_select) ok = false;
        if (n === 0 && !(customInput && customInput._ta && customInput._ta.value.trim())) ok = false;
        meta.textContent = n + (CFG.min_select ? ' / ≥' + CFG.min_select : '') +
          (CFG.max_select ? ' (max ' + CFG.max_select + ')' : '');
      } else {
        ok = selected.size > 0 || !!(customInput && customInput._ta && customInput._ta.value.trim());
      }
      btnConfirm.disabled = !ok;
    }

    function confirmSelection() {
      var customText = customInput && customInput._ta ? customInput._ta.value.trim() : '';
      if (CFG.mode === 'free_text' || (selected.size === 0 && customText)) {
        if (!customText) { return; }
        finish('custom', { custom_text: customText });
        return;
      }
      var indices = Array.from(selected).sort(function(a, b) { return a - b; });
      var values = indices.map(function(i) { return CFG.options[i].value; });
      finish('select', { indices: indices, values: values });
    }

    function finish(type, extra) {
      extra = extra || {};
      var elapsed_ms = Date.now() - elapsedStart;
      var answer = Object.assign({ type: type, indices: [], values: [], custom_text: null, elapsed_ms: elapsed_ms }, extra);
      cleanup();
      if (TRANSPORT === 'localhost') {
        fetch('/answer', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'X-Token': CFG.csrf_token },
          body: JSON.stringify(answer),
        }).finally(function() {
          document.body.innerHTML = '<p style="font-family: sans-serif; padding: 24px; color: #cdd6f4; background: #1e1e2e; min-height: 100vh; margin: 0;">You can close this tab.</p>';
        });
      }
      resolve(answer);
    }

    function cleanup() {
      document.removeEventListener('keydown', onKey);
      if (timer) clearTimeout(timer);
      try { root.remove(); } catch (e) {}
    }

    function onKey(e) {
      if (e.key === 'Escape') {
        e.preventDefault();
        if (CFG.required) {
          card.animate([{ transform: 'translateX(-4px)' }, { transform: 'translateX(4px)' }, { transform: 'none' }], { duration: 180 });
        } else { finish('skip'); }
        return;
      }
      if (e.key === 'Enter' && (e.target.tagName !== 'TEXTAREA')) {
        e.preventDefault(); confirmSelection(); return;
      }
      if (e.key >= '1' && e.key <= '9') {
        var n = parseInt(e.key, 10) - 1;
        var visible = visibleOptions();
        if (n < visible.length) { e.preventDefault(); onPick(visible[n].i); }
        return;
      }
      if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
        e.preventDefault();
        var visible = visibleOptions();
        if (!visible.length) return;
        focusIdx = (focusIdx + (e.key === 'ArrowDown' ? 1 : -1) + visible.length) % visible.length;
        renderOptions();
        // Tab to keep focus within the modal.
      }
      if (e.key === 'Tab') {
        // simple focus trap between buttons + textarea + search
        var focusables = Array.prototype.slice.call(card.querySelectorAll('button, textarea, input'));
        var first = focusables[0]; var last = focusables[focusables.length - 1];
        if (!first) return;
        if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
        else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
      }
    }

    document.addEventListener('keydown', onKey);
    document.body.appendChild(root);
    renderOptions();
    if (customInput && customInput._ta) {
      customInput._ta.addEventListener('input', updateConfirmEnabled);
    }

    var timer = setTimeout(function() { finish('timeout'); }, Math.max(1, CFG.timeout_s) * 1000);
    setTimeout(function() {
      if (search) search.focus();
      else btnConfirm.focus();
    }, 50);
  });
})();
"""


_LOCALHOST_BOOTSTRAP = "// localhost mode — promise return is unused; transport is the fetch above."


def build_overlay_js(question: Question, *, language: str = "en", mode: Mode = "owui",
                      csrf_token: str = "") -> str:
    """Build the IIFE returning a Promise<Answer>. For OWUI mode."""
    config = _js_payload(question, language, mode, csrf_token)
    js = _OVERLAY_JS_BODY.replace("__CONFIG__", config).replace("__TRANSPORT__", mode)
    return js


def build_localhost_html(question: Question, *, language: str = "en", csrf_token: str) -> str:
    """Wrap the overlay JS in a standalone HTML page for the MCP localhost server."""
    js = build_overlay_js(question, language=language, mode="localhost", csrf_token=csrf_token)
    title = t("title", language)
    # The IIFE returns a Promise we ignore in localhost mode (transport is fetch).
    # We still execute it for the side-effect of rendering the overlay.
    return f"""<!doctype html>
<html lang="{language}">
<head>
  <meta charset="utf-8">
  <title>{title}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>{_BASE_CSS}</style>
</head>
<body>
  <script>
  (function() {{
    {js}
  }})();
  </script>
</body>
</html>"""


def build_owui_overlay_call(question: Question, *, language: str = "en") -> str:
    """OWUI hosts inject CSS via a separate channel, but our JS injects its own
    `<style>` element so we don't depend on that. This wraps the IIFE for OWUI's
    `__event_call__({"type":"execute","data":{"code":"..."}})` runtime.
    """
    js = build_overlay_js(question, language=language, mode="owui")
    style_inject = (
        "var s=document.createElement('style');"
        f"s.textContent={json.dumps(_BASE_CSS)};"
        "document.head.appendChild(s);"
    )
    return f"{style_inject}\n{js}"

# === core/render.py ===
def to_markdown(result: Result[Answer], lang: str = "en", question: Question | None = None) -> str:
    if not result.ok or result.data is None:
        if result.error is None:
            return f"**Error**: unknown failure (lang={lang})"
        msg = result.error.message_tr if lang == "tr" else result.error.message_en
        body = f"**Error** ({result.error.code}): {msg}"
        if result.error.hint:
            body += f"\n\n_Hint: {result.error.hint}_"
        return body

    a = result.data
    if a.type == "skip":
        return f"_{t('label.no_answer', lang)}_"
    if a.type == "cancelled":
        return f"_{t('label.cancelled', lang)}_"
    if a.type == "timeout":
        return f"_{t('label.timeout', lang)}_"
    if a.type == "custom":
        return f"**{t('label.user_typed', lang)}**: {a.custom_text}"
    if a.type == "select":
        items = ", ".join(f"`{v}`" for v in a.values)
        return f"**{t('label.user_selected', lang)}**: {items}"
    return str(a)

# === owui/_wrapper.py ===
class Tools:
    class Valves(BaseModel):
        DEFAULT_LANGUAGE: str = Field(
            default="en",
            description="Output language. 'en' or 'tr'.",
        )
        ACCENT_COLOR: str = Field(
            default="#E8713A",
            description="Hex color used for selected/confirm buttons.",
        )

    def __init__(self):
        self.valves = self.Valves()
        self.citation = False

    def _lang(self, language):
        return (language or self.valves.DEFAULT_LANGUAGE or "en").strip()

    async def ask_user_question(
        self,
        prompt: str,
        options: list[dict] | None = None,
        mode: str = "single",
        allow_custom: bool = True,
        required: bool = False,
        min_select: int | None = None,
        max_select: int | None = None,
        timeout_s: float = 300.0,
        language: str | None = None,
        __event_call__=None,
        **_unused: Any,
    ) -> str:
        """
        Ask the user an interactive question. YOU decide when to call this.

        Use when: you need the user to pick between multiple valid approaches,
        the request is ambiguous and you'd otherwise guess, or you need a
        specific input (key, format, choice) before proceeding.

        Skip for: trivial yes/no confirmations, obvious choices from context,
        displaying information (this asks, doesn't show), or when the user
        already answered in their last message.

        Modes: 'single' / 'multi' / 'free_text'.
        """
        lang = self._lang(language)
        opt_models = [Option(**o) for o in (options or [])]
        question = Question(
            prompt=prompt,
            options=opt_models,
            mode=mode,
            allow_custom=allow_custom,
            required=required,
            min_select=min_select,
            max_select=max_select,
            timeout_s=timeout_s,
            accent=self.valves.ACCENT_COLOR,
        )
        err = validate_question(question, language=lang)
        if err is not None:
            return to_markdown(Result(ok=False, error=err), lang=lang)

        if __event_call__ is None:
            return to_markdown(
                Result(
                    ok=False,
                    error=ErrorInfo(
                        code="UNSUPPORTED",
                        message_en="OWUI __event_call__ channel not available.",
                        message_tr="OWUI __event_call__ kanalı kullanılamıyor.",
                    ),
                ),
                lang=lang,
            )

        js = build_owui_overlay_call(question, language=lang)
        try:
            payload = await __event_call__({"type": "execute", "data": {"code": js}})
        except Exception as exc:
            return to_markdown(
                Result(
                    ok=False,
                    error=ErrorInfo(
                        code="INTERNAL",
                        message_en=f"event_call failed: {exc.__class__.__name__}",
                        message_tr=f"event_call hatası: {exc.__class__.__name__}",
                    ),
                ),
                lang=lang,
            )

        # OWUI may pass the resolved Promise value as a JSON string or raw dict.
        if isinstance(payload, str):
            try:
                payload = json.loads(payload)
            except (TypeError, ValueError):
                return f"**{t('label.user_typed', lang)}**: {payload}"
        if not isinstance(payload, dict):
            return to_markdown(
                Result(
                    ok=True,
                    data=Answer(type="skip"),
                ),
                lang=lang,
            )

        ans = Answer(
            type=payload.get("type", "skip"),
            indices=payload.get("indices") or [],
            values=payload.get("values") or [],
            custom_text=payload.get("custom_text"),
            elapsed_ms=int(payload.get("elapsed_ms", 0)),
        )
        return to_markdown(Result(ok=True, data=ans), lang=lang)

