"""
title: CurrencyPulse
description: Multi-source FX rates, conversion, and time-series with locale-aware formatting. Provider chain: Frankfurter → exchangerate.host → OXR (optional key) → TCMB (TRY).
author: Orzed, LLC
version: 1.0.0
required_open_webui_version: 0.5.0
"""

# ────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED BY tools/bundle_owui.py - DO NOT EDIT BY HAND.
# Source of truth: this tool's core/ and owui/_wrapper.py.
# Run `make bundle` (or `python tools/bundle_owui.py <tool>`) to regenerate.
# CI runs `make check-bundle` and fails on drift.
# ────────────────────────────────────────────────────────────────────────────

import httpx
import math
import os
import random
import time
from collections.abc import Iterable
from datetime import date as Date
from pydantic import BaseModel, Field
from typing import Final
from typing import Generic, Literal, TypeVar
from xml.etree import ElementTree as ET

# === core/types.py ===
T = TypeVar("T", bound=BaseModel)

ErrorCode = Literal[
    "INVALID_INPUT",
    "NOT_FOUND",
    "RATE_LIMITED",
    "NETWORK_TIMEOUT",
    "UPSTREAM_ERROR",
    "UNSUPPORTED",
    "PARSE_ERROR",
    "TIMEOUT",
    "CANCELLED",
    "INTERNAL",
]


class ErrorInfo(BaseModel):
    code: ErrorCode
    message_en: str
    message_tr: str
    hint: str | None = None
    upstream: str | None = None
    retry_after_s: float | None = None


class Result(BaseModel, Generic[T]):
    ok: bool
    data: T | None = None
    error: ErrorInfo | None = None
    meta: dict = Field(default_factory=dict)


class Rate(BaseModel):
    base: str
    quote: str
    value: float = Field(description="Decimal rate, base→quote.")
    on_date: Date
    source: str = Field(description="Provider name: frankfurter|exchangerate_host|oxr|tcmb.")


class Conversion(BaseModel):
    base: str
    quote: str
    amount: float
    rate: float
    converted: float
    on_date: Date
    source: str


class SnapshotEntry(BaseModel):
    quote: str
    rate: float
    name: str | None = None


class Snapshot(BaseModel):
    base: str
    on_date: Date
    rates: list[SnapshotEntry]
    source: str


class TimeSeriesPoint(BaseModel):
    on_date: Date
    rate: float


class TimeSeries(BaseModel):
    base: str
    quote: str
    start: Date
    end: Date
    points: list[TimeSeriesPoint]
    source: str

# === core/i18n.py ===
STRINGS: Final[dict[str, dict[str, str]]] = {
    "en": {
        "title.rate": "Rate",
        "title.convert": "Conversion",
        "title.snapshot": "FX Snapshot",
        "title.timeseries": "Time Series",
        "label.base": "Base",
        "label.quote": "Quote",
        "label.amount": "Amount",
        "label.rate": "Rate",
        "label.converted": "Converted",
        "label.on_date": "Date",
        "label.source": "Source",
        "label.no_data": "No data points.",
        "error.invalid_currency": "Unknown currency code: {code}.",
        "error.same_currency": "Base and quote currencies are the same.",
        "error.crypto_not_supported": "Cryptocurrency codes are not supported by this tool.",
        "error.no_provider": "No provider could fulfil the request for {base}/{quote}.",
        "error.invalid_amount": "Amount must be a finite, non-negative number.",
        "error.invalid_date": "Invalid date. Use YYYY-MM-DD or leave blank for the latest.",
        "error.start_after_end": "start date is after end date.",
        "error.range_too_large": "Date range exceeds 366 days.",
        "error.network": "Could not reach any FX provider.",
        "hint.try_different_pair": "Try a major pair (USD, EUR, GBP, JPY) and check the date.",
        "hint.set_oxr_key": "Set FLIGHTHUNTER_OXR_APP_ID for broader currency support.",  # cross-tool fallback hint not used
        "hint.set_oxr_app_id": "Set CURRENCYPULSE_OXR_APP_ID env var for OXR fallback coverage.",
        "note.rate": "Rates are indicative; do not use as a settlement quote.",
    },
    "tr": {
        "title.rate": "Kur",
        "title.convert": "Dönüşüm",
        "title.snapshot": "Kur Tablosu",
        "title.timeseries": "Zaman Serisi",
        "label.base": "Baz",
        "label.quote": "Karşı",
        "label.amount": "Miktar",
        "label.rate": "Kur",
        "label.converted": "Dönüşmüş",
        "label.on_date": "Tarih",
        "label.source": "Kaynak",
        "label.no_data": "Veri noktası yok.",
        "error.invalid_currency": "Bilinmeyen para kodu: {code}.",
        "error.same_currency": "Baz ve karşı para aynı.",
        "error.crypto_not_supported": "Kripto kodları bu araçta desteklenmiyor.",
        "error.no_provider": "{base}/{quote} için hiçbir sağlayıcı veri sunamadı.",
        "error.invalid_amount": "Miktar sonlu ve negatif olmayan bir sayı olmalı.",
        "error.invalid_date": "Geçersiz tarih. YYYY-MM-DD biçimi kullanın veya boş bırakın.",
        "error.start_after_end": "Başlangıç tarihi bitiş tarihinden büyük.",
        "error.range_too_large": "Tarih aralığı 366 günü aşıyor.",
        "error.network": "Hiçbir FX sağlayıcısına ulaşılamadı.",
        "hint.try_different_pair": "Ana paritelere (USD, EUR, GBP, JPY) ve tarihe bakın.",
        "hint.set_oxr_key": "Geniş kapsama için FLIGHTHUNTER_OXR_APP_ID girin.",
        "hint.set_oxr_app_id": "OXR fallback kapsaması için CURRENCYPULSE_OXR_APP_ID env değişkenini ayarlayın.",
        "note.rate": "Kurlar gösterge niteliğindedir; takas işlemine esas alınamaz.",
    },
}

SUPPORTED: Final[tuple[str, ...]] = ("en", "tr")
DEFAULT: Final[str] = "en"


def normalize_lang(lang: str | None) -> str:
    if not lang:
        return DEFAULT
    base = lang.lower().split("-")[0]
    return base if base in SUPPORTED else DEFAULT


def t(key: str, lang: str = DEFAULT, **kwargs: object) -> str:
    lang = normalize_lang(lang)
    table = STRINGS.get(lang) or STRINGS[DEFAULT]
    template = table.get(key) or STRINGS[DEFAULT].get(key) or key
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError):
        return template

# === core/iso4217.py ===
CURRENCIES: Final[frozenset[str]] = frozenset(
    {
        "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN",
        "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BRL",
        "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHF", "CLP", "CNY",
        "COP", "CRC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP",
        "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD",
        "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR",
        "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF",
        "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL",
        "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR",
        "MVR", "MWK", "MXN", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR",
        "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR",
        "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD",
        "SHP", "SLE", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB",
        "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX",
        "USD", "UYU", "UZS", "VES", "VND", "VUV", "WST", "XAF", "XCD", "XOF",
        "XPF", "YER", "ZAR", "ZMW",
    }
)

# Common deprecated codes mapped to their successors. Returned via meta.note.
DEPRECATED_REPLACEMENTS: Final[dict[str, str]] = {
    "HRK": "EUR",
    "EEK": "EUR",
    "LTL": "EUR",
    "LVL": "EUR",
    "VEF": "VES",
    "MRO": "MRU",
    "STD": "STN",
    "BYR": "BYN",
    "CYP": "EUR",
    "MTL": "EUR",
    "SKK": "EUR",
    "SIT": "EUR",
    "TRL": "TRY",
}

CRYPTO_CODES: Final[frozenset[str]] = frozenset(
    {"BTC", "ETH", "USDT", "USDC", "BNB", "XRP", "ADA", "SOL", "DOGE", "TRX", "DOT"}
)

# Sensible default symbols list - broader than the legacy Western-only set,
# covers Asia, LATAM, MENA, Africa.
DEFAULT_SYMBOLS: Final[tuple[str, ...]] = (
    "USD", "EUR", "GBP", "JPY", "CHF", "CAD", "AUD",
    "CNY", "INR", "BRL", "MXN", "ZAR", "AED", "SAR",
    "TRY", "RUB", "KRW", "SGD", "HKD", "THB",
)


def normalize_code(code: str) -> str:
    return (code or "").strip().upper()


def is_supported(code: str) -> bool:
    return normalize_code(code) in CURRENCIES


def is_crypto(code: str) -> bool:
    return normalize_code(code) in CRYPTO_CODES


def deprecated_replacement(code: str) -> str | None:
    return DEPRECATED_REPLACEMENTS.get(normalize_code(code))

# === core/http.py ===
class RateLimited(Exception):
    def __init__(self, retry_after: float | None = None) -> None:
        self.retry_after = retry_after


class NetworkTimeout(Exception):
    pass


class UpstreamError(Exception):
    def __init__(self, status: int, body: str) -> None:
        self.status = status
        self.body = body


def build_client(
    timeout: float = 10.0, user_agent: str = "orzed-mcp-essentials/1.0"
) -> httpx.Client:
    return httpx.Client(
        timeout=timeout,
        headers={"User-Agent": user_agent, "Accept": "application/json"},
        follow_redirects=True,
    )


def get_json_with_retry(
    client: httpx.Client,
    url: str,
    *,
    params: dict | None = None,
    max_attempts: int = 3,
    base_delay: float = 0.5,
) -> dict:
    """GET ``url`` with retries on transient failures. Raises typed exceptions."""
    last_exc: Exception | None = None
    for attempt in range(max_attempts):
        try:
            r = client.get(url, params=params)
        except httpx.TimeoutException:
            last_exc = NetworkTimeout()
        except httpx.RequestError as e:
            last_exc = e
        else:
            if r.status_code == 429:
                ra = r.headers.get("Retry-After")
                last_exc = RateLimited(retry_after=float(ra) if ra else None)
            elif r.status_code in (408, 500, 502, 503, 504):
                last_exc = UpstreamError(r.status_code, r.text[:500])
            elif r.is_success:
                return r.json()
            else:
                raise UpstreamError(r.status_code, r.text[:500])

        if attempt < max_attempts - 1:
            sleep_s = base_delay * (2**attempt) + random.uniform(0, base_delay)
            if isinstance(last_exc, RateLimited) and last_exc.retry_after:
                sleep_s = max(sleep_s, last_exc.retry_after)
            time.sleep(sleep_s)

    if last_exc is not None:
        raise last_exc
    raise UpstreamError(0, "no attempts succeeded")


def get_text_with_retry(
    client: httpx.Client,
    url: str,
    *,
    params: dict | None = None,
    max_attempts: int = 3,
    base_delay: float = 0.5,
) -> str:
    """Same as get_json_with_retry but returns response text (for XML feeds)."""
    last_exc: Exception | None = None
    for attempt in range(max_attempts):
        try:
            r = client.get(url, params=params)
        except httpx.TimeoutException:
            last_exc = NetworkTimeout()
        except httpx.RequestError as e:
            last_exc = e
        else:
            if r.status_code == 429:
                ra = r.headers.get("Retry-After")
                last_exc = RateLimited(retry_after=float(ra) if ra else None)
            elif r.status_code in (408, 500, 502, 503, 504):
                last_exc = UpstreamError(r.status_code, r.text[:500])
            elif r.is_success:
                return r.text
            else:
                raise UpstreamError(r.status_code, r.text[:500])

        if attempt < max_attempts - 1:
            sleep_s = base_delay * (2**attempt) + random.uniform(0, base_delay)
            if isinstance(last_exc, RateLimited) and last_exc.retry_after:
                sleep_s = max(sleep_s, last_exc.retry_after)
            time.sleep(sleep_s)

    if last_exc is not None:
        raise last_exc
    raise UpstreamError(0, "no attempts succeeded")

# === core/providers.py ===
FRANKFURTER_BASE = "https://api.frankfurter.dev/v1"
EXCHANGERATE_HOST_BASE = "https://api.exchangerate.host"
OXR_BASE = "https://openexchangerates.org/api"
TCMB_TODAY = "https://www.tcmb.gov.tr/kurlar/today.xml"
TCMB_HISTORY = "https://www.tcmb.gov.tr/kurlar/{ymd}.xml"  # ymd format YYYY/YYYYMM/YYYYMMDD

_FRANKFURTER_SUPPORTED: frozenset[str] | None = None


def _frankfurter_currencies(client) -> frozenset[str]:
    global _FRANKFURTER_SUPPORTED
    if _FRANKFURTER_SUPPORTED is not None:
        return _FRANKFURTER_SUPPORTED
    try:
        data = get_json_with_retry(client, f"{FRANKFURTER_BASE}/currencies", max_attempts=2)
        _FRANKFURTER_SUPPORTED = frozenset(data.keys())
    except Exception:
        # Conservative fallback based on Frankfurter's published list.
        _FRANKFURTER_SUPPORTED = frozenset(
            {
                "AUD", "BGN", "BRL", "CAD", "CHF", "CNY", "CZK", "DKK", "EUR", "GBP",
                "HKD", "HUF", "IDR", "ILS", "INR", "ISK", "JPY", "KRW", "MXN", "MYR",
                "NOK", "NZD", "PHP", "PLN", "RON", "SEK", "SGD", "THB", "TRY", "USD",
                "ZAR",
            }
        )
    return _FRANKFURTER_SUPPORTED


# ──────────────────────────────────────────────────────────────────────────────
# Frankfurter
# ──────────────────────────────────────────────────────────────────────────────
class FrankfurterProvider:
    name = "frankfurter"

    def __init__(self, client) -> None:
        self.client = client

    def supports(self, base: str, quote: str, on_date: Date | None = None) -> bool:
        cur = _frankfurter_currencies(self.client)
        return base in cur and quote in cur

    def rate(self, base: str, quote: str, on_date: Date | None = None) -> dict:
        path = on_date.isoformat() if on_date else "latest"
        url = f"{FRANKFURTER_BASE}/{path}"
        data = get_json_with_retry(self.client, url, params={"base": base, "symbols": quote})
        rates = data.get("rates") or {}
        if quote not in rates:
            raise ValueError(f"frankfurter: missing rate for {quote}")
        return {
            "value": float(rates[quote]),
            "on_date": Date.fromisoformat(data.get("date") or path),
        }

    def snapshot(self, base: str, symbols: list[str]) -> dict:
        url = f"{FRANKFURTER_BASE}/latest"
        data = get_json_with_retry(
            self.client, url, params={"base": base, "symbols": ",".join(symbols)}
        )
        return {
            "on_date": Date.fromisoformat(data.get("date")),
            "rates": {k: float(v) for k, v in (data.get("rates") or {}).items()},
        }

    def timeseries(self, base: str, quote: str, start: Date, end: Date) -> list[dict]:
        url = f"{FRANKFURTER_BASE}/{start.isoformat()}..{end.isoformat()}"
        data = get_json_with_retry(self.client, url, params={"base": base, "symbols": quote})
        out = []
        for d_str, rates in (data.get("rates") or {}).items():
            if quote in rates:
                out.append({"on_date": Date.fromisoformat(d_str), "rate": float(rates[quote])})
        return sorted(out, key=lambda p: p["on_date"])


# ──────────────────────────────────────────────────────────────────────────────
# exchangerate.host
# ──────────────────────────────────────────────────────────────────────────────
class ExchangerateHostProvider:
    name = "exchangerate_host"

    def __init__(self, client) -> None:
        self.client = client

    def supports(self, base: str, quote: str, on_date: Date | None = None) -> bool:
        # exchangerate.host claims most ISO 4217 codes; we let our list gate it.
        return is_supported(base) and is_supported(quote)

    def rate(self, base: str, quote: str, on_date: Date | None = None) -> dict:
        path = on_date.isoformat() if on_date else "latest"
        url = f"{EXCHANGERATE_HOST_BASE}/{path}"
        data = get_json_with_retry(
            self.client, url, params={"base": base, "symbols": quote}
        )
        rates = data.get("rates") or {}
        if quote not in rates:
            raise ValueError(f"exchangerate.host: missing rate for {quote}")
        return {
            "value": float(rates[quote]),
            "on_date": Date.fromisoformat(data.get("date") or path),
        }

    def snapshot(self, base: str, symbols: list[str]) -> dict:
        url = f"{EXCHANGERATE_HOST_BASE}/latest"
        data = get_json_with_retry(
            self.client, url, params={"base": base, "symbols": ",".join(symbols)}
        )
        return {
            "on_date": Date.fromisoformat(data.get("date") or Date.today().isoformat()),
            "rates": {k: float(v) for k, v in (data.get("rates") or {}).items()},
        }

    def timeseries(self, base: str, quote: str, start: Date, end: Date) -> list[dict]:
        url = f"{EXCHANGERATE_HOST_BASE}/timeseries"
        data = get_json_with_retry(
            self.client,
            url,
            params={
                "base": base,
                "symbols": quote,
                "start_date": start.isoformat(),
                "end_date": end.isoformat(),
            },
        )
        out = []
        for d_str, rates in (data.get("rates") or {}).items():
            if quote in rates:
                out.append({"on_date": Date.fromisoformat(d_str), "rate": float(rates[quote])})
        return sorted(out, key=lambda p: p["on_date"])


# ──────────────────────────────────────────────────────────────────────────────
# OpenExchangeRates (optional, requires APP_ID)
# ──────────────────────────────────────────────────────────────────────────────
class OXRProvider:
    name = "oxr"

    def __init__(self, client, app_id: str | None) -> None:
        self.client = client
        self.app_id = app_id

    def is_configured(self) -> bool:
        return bool(self.app_id)

    def supports(self, base: str, quote: str, on_date: Date | None = None) -> bool:
        return self.is_configured() and is_supported(base) and is_supported(quote)

    def _fetch(self, path: str, params: dict | None = None) -> dict:
        merged = dict(params or {})
        merged["app_id"] = self.app_id
        return get_json_with_retry(self.client, f"{OXR_BASE}/{path}", params=merged)

    def _convert_via_usd(self, base: str, quote: str, on_date: Date | None) -> dict:
        # OXR free tier requires USD as base; do cross via USD.
        path = (
            f"historical/{on_date.isoformat()}.json" if on_date else "latest.json"
        )
        data = self._fetch(path, {"symbols": ",".join({base, quote})})
        rates = data.get("rates") or {}
        if base not in rates or quote not in rates:
            raise ValueError(f"oxr: missing rate for {base} or {quote}")
        # USD->base = rates[base], USD->quote = rates[quote]; base->quote = quote/base
        value = float(rates[quote]) / float(rates[base])
        ts = data.get("timestamp")
        on = Date.fromtimestamp(ts) if ts else (on_date or Date.today())
        return {"value": value, "on_date": on}

    def rate(self, base: str, quote: str, on_date: Date | None = None) -> dict:
        return self._convert_via_usd(base, quote, on_date)

    def snapshot(self, base: str, symbols: list[str]) -> dict:
        data = self._fetch("latest.json", {"symbols": ",".join({base, *symbols})})
        rates = data.get("rates") or {}
        if base not in rates:
            raise ValueError(f"oxr: missing base rate for {base}")
        usd_to_base = float(rates[base])
        out = {}
        for sym in symbols:
            if sym in rates:
                out[sym] = float(rates[sym]) / usd_to_base
        ts = data.get("timestamp")
        on = Date.fromtimestamp(ts) if ts else Date.today()
        return {"on_date": on, "rates": out}

    def timeseries(self, base: str, quote: str, start: Date, end: Date) -> list[dict]:
        # OXR time-series is per-day; we don't fan out hundreds of calls. Caller falls back.
        raise ValueError("oxr: time-series not implemented (free tier rate-limit)")


# ──────────────────────────────────────────────────────────────────────────────
# TCMB (Turkish Central Bank, TRY-anchored)
# ──────────────────────────────────────────────────────────────────────────────
class TCMBProvider:
    name = "tcmb"

    def __init__(self, client) -> None:
        self.client = client

    def supports(self, base: str, quote: str, on_date: Date | None = None) -> bool:
        return base == "TRY" or quote == "TRY"

    def _fetch_xml(self, on_date: Date | None) -> dict[str, dict[str, float]]:
        if on_date is None:
            url = TCMB_TODAY
        else:
            ymd = on_date.strftime("%Y%m/%d%m%Y")  # https://www.tcmb.gov.tr/kurlar/202310/05102023.xml
            url = f"https://www.tcmb.gov.tr/kurlar/{ymd}.xml"
        text = get_text_with_retry(self.client, url, max_attempts=2)
        root = ET.fromstring(text)
        out: dict[str, dict[str, float]] = {}
        for cur in root.findall("Currency"):
            code = (cur.attrib.get("CurrencyCode") or "").upper()
            if not code:
                continue
            unit = float(cur.findtext("Unit") or "1")
            forex_buy = cur.findtext("ForexBuying") or ""
            forex_sell = cur.findtext("ForexSelling") or ""
            try:
                buy = float(forex_buy) / unit if forex_buy.strip() else None
                sell = float(forex_sell) / unit if forex_sell.strip() else None
            except ValueError:
                continue
            if buy is None and sell is None:
                continue
            mid = (buy + sell) / 2 if (buy and sell) else (buy or sell)
            out[code] = {"buy": buy or 0.0, "sell": sell or 0.0, "mid": mid or 0.0}
        return out

    def rate(self, base: str, quote: str, on_date: Date | None = None) -> dict:
        rates = self._fetch_xml(on_date)
        on = on_date or Date.today()
        if base == "TRY" and quote in rates:
            return {"value": 1.0 / rates[quote]["mid"], "on_date": on}
        if quote == "TRY" and base in rates:
            return {"value": rates[base]["mid"], "on_date": on}
        if base in rates and quote in rates:
            # Cross via TRY mid rates.
            return {"value": rates[base]["mid"] / rates[quote]["mid"], "on_date": on}
        raise ValueError(f"tcmb: missing rate for {base}->{quote}")

    def snapshot(self, base: str, symbols: list[str]) -> dict:
        rates = self._fetch_xml(None)
        on = Date.today()
        out = {}
        if base == "TRY":
            for sym in symbols:
                if sym == "TRY":
                    out["TRY"] = 1.0
                elif sym in rates:
                    out[sym] = 1.0 / rates[sym]["mid"]
        else:
            if base not in rates:
                raise ValueError(f"tcmb: snapshot base {base} unsupported")
            base_to_try = rates[base]["mid"]
            for sym in symbols:
                if sym == "TRY":
                    out["TRY"] = base_to_try
                elif sym in rates:
                    out[sym] = base_to_try / rates[sym]["mid"]
        return {"on_date": on, "rates": out}

    def timeseries(self, base: str, quote: str, start: Date, end: Date) -> list[dict]:
        # TCMB requires per-day fetches; not feasible at scale. Caller falls back.
        raise ValueError("tcmb: time-series not implemented")


# ──────────────────────────────────────────────────────────────────────────────
# Provider registry
# ──────────────────────────────────────────────────────────────────────────────
def build_providers(client, oxr_app_id: str | None = None) -> list:
    return [
        FrankfurterProvider(client),
        ExchangerateHostProvider(client),
        OXRProvider(client, oxr_app_id),
        TCMBProvider(client),
    ]


def env_oxr_app_id() -> str | None:
    return os.getenv("CURRENCYPULSE_OXR_APP_ID") or None


__all__ = [
    "FrankfurterProvider",
    "ExchangerateHostProvider",
    "OXRProvider",
    "TCMBProvider",
    "build_providers",
    "env_oxr_app_id",
    "NetworkTimeout",
    "RateLimited",
    "UpstreamError",
]

# === core/fx.py ===
_CACHE_TTL_SECONDS = 300
_cache: dict[tuple, tuple[float, object]] = {}


def _err(
    code: str,
    lang: str,
    en_key: str,
    *,
    fmt: dict | None = None,
    hint_key: str | None = None,
    upstream: str | None = None,
) -> ErrorInfo:
    fmt = fmt or {}
    return ErrorInfo(
        code=code,
        message_en=t(en_key, "en", **fmt),
        message_tr=t(en_key, "tr", **fmt),
        hint=t(hint_key, lang, **fmt) if hint_key else None,
        upstream=upstream,
    )


def _validate_pair(base: str, quote: str, lang: str) -> ErrorInfo | None:
    base_n = normalize_code(base)
    quote_n = normalize_code(quote)
    if not base_n or not quote_n:
        return _err("INVALID_INPUT", lang, "error.invalid_currency", fmt={"code": ""})
    if is_crypto(base_n) or is_crypto(quote_n):
        return _err("UNSUPPORTED", lang, "error.crypto_not_supported")
    for c in (base_n, quote_n):
        if not is_supported(c) and deprecated_replacement(c) is None:
            return _err("INVALID_INPUT", lang, "error.invalid_currency", fmt={"code": c})
    return None


def _resolve_deprecated(code: str) -> tuple[str, str | None]:
    """Return (normalized_code, replacement_used_for_meta_or_None)."""
    n = normalize_code(code)
    if is_supported(n):
        return n, None
    rep = deprecated_replacement(n)
    if rep is not None:
        return rep, n
    return n, None


def _parse_date(raw: str | None, lang: str) -> tuple[Date | None, ErrorInfo | None]:
    if not raw:
        return None, None
    if isinstance(raw, Date):
        return raw, None
    try:
        return Date.fromisoformat(str(raw).strip()), None
    except ValueError:
        return None, _err("INVALID_INPUT", lang, "error.invalid_date")


def _cache_key(*parts: object) -> tuple:
    return parts


def _cache_get(key: tuple):
    item = _cache.get(key)
    if item is None:
        return None
    expires_at, value = item
    if time.time() > expires_at:
        _cache.pop(key, None)
        return None
    return value


def _cache_set(key: tuple, value: object) -> None:
    _cache[key] = (time.time() + _CACHE_TTL_SECONDS, value)


def _try_providers(
    providers: Iterable,
    method_name: str,
    base: str,
    quote: str | None,
    *args,
    **kwargs,
):
    """Run the named method across providers in order. Return (provider, value)."""
    last_exc: Exception | None = None
    for prov in providers:
        if hasattr(prov, "is_configured") and not prov.is_configured():
            continue
        if quote is not None and not prov.supports(base, quote):
            continue
        if quote is None and not prov.supports(base, base):  # snapshot uses base only
            continue
        try:
            value = getattr(prov, method_name)(*args, **kwargs)
            return prov, value
        except (NetworkTimeout, RateLimited, UpstreamError, ValueError) as exc:
            last_exc = exc
            continue
    return None, last_exc


# ──────────────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────────────
def rate(
    base: str,
    quote: str,
    on: str | Date | None = None,
    *,
    language: str = "en",
    client=None,
) -> Result[Rate]:
    err = _validate_pair(base, quote, language)
    if err:
        return Result(ok=False, error=err)
    base_n, base_dep = _resolve_deprecated(base)
    quote_n, quote_dep = _resolve_deprecated(quote)
    if base_n == quote_n:
        # Same currency - return 1.0 deterministically without hitting the network.
        on_date, derr = _parse_date(on, language)
        if derr:
            return Result(ok=False, error=derr)
        on_date = on_date or Date.today()
        meta: dict = {"source": "identity"}
        if base_dep or quote_dep:
            meta["deprecated"] = [c for c in (base_dep, quote_dep) if c]
        return Result(
            ok=True,
            data=Rate(
                base=base_n, quote=quote_n, value=1.0, on_date=on_date, source="identity"
            ),
            meta=meta,
        )

    on_date, derr = _parse_date(on, language)
    if derr:
        return Result(ok=False, error=derr)

    cache_key = _cache_key("rate", base_n, quote_n, on_date.isoformat() if on_date else "latest")
    cached = _cache_get(cache_key)
    if cached:
        rate_obj, source = cached
        return Result(ok=True, data=rate_obj, meta={"source": source, "cached": True})

    own_client = client is None
    if client is None:
        client = build_client()
    try:
        providers = build_providers(client, env_oxr_app_id())
        prov, value = _try_providers(providers, "rate", base_n, quote_n, base_n, quote_n, on_date)
        if prov is None:
            if isinstance(value, (NetworkTimeout, RateLimited, UpstreamError)):
                return Result(
                    ok=False,
                    error=_err("UPSTREAM_ERROR", language, "error.network", upstream="all"),
                )
            return Result(
                ok=False,
                error=_err(
                    "NOT_FOUND",
                    language,
                    "error.no_provider",
                    fmt={"base": base_n, "quote": quote_n},
                    hint_key="hint.set_oxr_app_id",
                ),
            )
        rate_obj = Rate(
            base=base_n,
            quote=quote_n,
            value=value["value"],
            on_date=value["on_date"],
            source=prov.name,
        )
        _cache_set(cache_key, (rate_obj, prov.name))
        meta: dict = {"source": prov.name}
        if base_dep or quote_dep:
            meta["deprecated"] = [c for c in (base_dep, quote_dep) if c]
        return Result(ok=True, data=rate_obj, meta=meta)
    finally:
        if own_client:
            client.close()


def convert(
    amount: float,
    base: str,
    quote: str,
    on: str | Date | None = None,
    *,
    language: str = "en",
    client=None,
) -> Result[Conversion]:
    if amount is None or not isinstance(amount, (int, float)) or math.isnan(float(amount)):
        return Result(ok=False, error=_err("INVALID_INPUT", language, "error.invalid_amount"))
    if float(amount) < 0 or math.isinf(float(amount)):
        return Result(ok=False, error=_err("INVALID_INPUT", language, "error.invalid_amount"))

    rate_result = rate(base, quote, on=on, language=language, client=client)
    if not rate_result.ok or rate_result.data is None:
        return Result(ok=False, error=rate_result.error, meta=rate_result.meta)
    r = rate_result.data
    return Result(
        ok=True,
        data=Conversion(
            base=r.base,
            quote=r.quote,
            amount=float(amount),
            rate=r.value,
            converted=float(amount) * r.value,
            on_date=r.on_date,
            source=r.source,
        ),
        meta=rate_result.meta,
    )


def snapshot(
    base: str,
    symbols: list[str] | None = None,
    *,
    language: str = "en",
    client=None,
) -> Result[Snapshot]:
    base_n = normalize_code(base)
    if not is_supported(base_n) and deprecated_replacement(base_n) is None:
        return Result(
            ok=False,
            error=_err("INVALID_INPUT", language, "error.invalid_currency", fmt={"code": base_n}),
        )
    base_n, base_dep = _resolve_deprecated(base_n)
    requested = [normalize_code(s) for s in (symbols or DEFAULT_SYMBOLS)]
    requested = [s for s in requested if s and is_supported(s)]
    if not requested:
        return Result(
            ok=False,
            error=_err("INVALID_INPUT", language, "error.invalid_currency", fmt={"code": ""}),
        )

    own_client = client is None
    if client is None:
        client = build_client()
    try:
        providers = build_providers(client, env_oxr_app_id())
        last_exc: Exception | None = None
        for prov in providers:
            if hasattr(prov, "is_configured") and not prov.is_configured():
                continue
            try:
                payload = prov.snapshot(base_n, requested)
            except (NetworkTimeout, RateLimited, UpstreamError, ValueError) as exc:
                last_exc = exc
                continue
            entries = [
                SnapshotEntry(quote=q, rate=v) for q, v in sorted(payload.get("rates", {}).items())
            ]
            if not entries:
                last_exc = ValueError("provider returned empty snapshot")
                continue
            snap = Snapshot(
                base=base_n,
                on_date=payload.get("on_date") or Date.today(),
                rates=entries,
                source=prov.name,
            )
            meta: dict = {"source": prov.name}
            if base_dep:
                meta["deprecated"] = [base_dep]
            return Result(ok=True, data=snap, meta=meta)
        if isinstance(last_exc, (NetworkTimeout, RateLimited, UpstreamError)):
            return Result(
                ok=False,
                error=_err("UPSTREAM_ERROR", language, "error.network", upstream="all"),
            )
        return Result(
            ok=False,
            error=_err(
                "NOT_FOUND",
                language,
                "error.no_provider",
                fmt={"base": base_n, "quote": ",".join(requested[:3]) + "..."},
            ),
        )
    finally:
        if own_client:
            client.close()


def timeseries(
    base: str,
    quote: str,
    start: str | Date,
    end: str | Date,
    *,
    language: str = "en",
    client=None,
) -> Result[TimeSeries]:
    err = _validate_pair(base, quote, language)
    if err:
        return Result(ok=False, error=err)
    base_n, _ = _resolve_deprecated(base)
    quote_n, _ = _resolve_deprecated(quote)
    if base_n == quote_n:
        return Result(ok=False, error=_err("INVALID_INPUT", language, "error.same_currency"))

    start_d, derr = _parse_date(start, language)
    if derr or start_d is None:
        return Result(ok=False, error=derr or _err("INVALID_INPUT", language, "error.invalid_date"))
    end_d, derr = _parse_date(end, language)
    if derr or end_d is None:
        return Result(ok=False, error=derr or _err("INVALID_INPUT", language, "error.invalid_date"))
    if start_d > end_d:
        return Result(ok=False, error=_err("INVALID_INPUT", language, "error.start_after_end"))
    if (end_d - start_d).days > 366:
        return Result(ok=False, error=_err("INVALID_INPUT", language, "error.range_too_large"))

    own_client = client is None
    if client is None:
        client = build_client()
    try:
        providers = build_providers(client, env_oxr_app_id())
        last_exc: Exception | None = None
        for prov in providers:
            if hasattr(prov, "is_configured") and not prov.is_configured():
                continue
            if not prov.supports(base_n, quote_n):
                continue
            try:
                points = prov.timeseries(base_n, quote_n, start_d, end_d)
            except (NetworkTimeout, RateLimited, UpstreamError, ValueError) as exc:
                last_exc = exc
                continue
            if not points:
                last_exc = ValueError("provider returned no points")
                continue
            ts = TimeSeries(
                base=base_n,
                quote=quote_n,
                start=start_d,
                end=end_d,
                points=[TimeSeriesPoint(on_date=p["on_date"], rate=p["rate"]) for p in points],
                source=prov.name,
            )
            return Result(ok=True, data=ts, meta={"source": prov.name})
        if isinstance(last_exc, (NetworkTimeout, RateLimited, UpstreamError)):
            return Result(
                ok=False,
                error=_err("UPSTREAM_ERROR", language, "error.network", upstream="all"),
            )
        return Result(
            ok=False,
            error=_err(
                "NOT_FOUND",
                language,
                "error.no_provider",
                fmt={"base": base_n, "quote": quote_n},
            ),
        )
    finally:
        if own_client:
            client.close()

# === core/render.py ===
def _fmt_number(value: float, lang: str, digits: int = 4) -> str:
    """Format with language-correct thousands/decimal separators."""
    if value is None:
        return "?"
    if abs(value) >= 100:
        digits = 2
    raw = f"{value:,.{digits}f}"  # default en-US: 1,234.5678
    if lang == "tr":
        # Swap separators: 1,234.56 -> 1.234,56
        return raw.replace(",", "X").replace(".", ",").replace("X", ".")
    return raw


def to_markdown(result: Result, lang: str = "en") -> str:
    if not result.ok or result.data is None:
        if result.error is None:
            return f"**Error**: unknown failure (lang={lang})"
        message = result.error.message_tr if lang == "tr" else result.error.message_en
        body = f"**Error** ({result.error.code}): {message}"
        if result.error.hint:
            body += f"\n\n_Hint: {result.error.hint}_"
        return body

    data = result.data
    if isinstance(data, Rate):
        return _render_rate(data, lang)
    if isinstance(data, Conversion):
        return _render_conversion(data, lang)
    if isinstance(data, Snapshot):
        return _render_snapshot(data, lang)
    if isinstance(data, TimeSeries):
        return _render_timeseries(data, lang)
    return f"**Result**: {data}"


def _render_rate(r: Rate, lang: str) -> str:
    return "\n".join(
        [
            f"# {t('title.rate', lang)}",
            "",
            f"- **{t('label.base', lang)}**: `{r.base}`",
            f"- **{t('label.quote', lang)}**: `{r.quote}`",
            f"- **{t('label.rate', lang)}**: `{_fmt_number(r.value, lang)}`",
            f"- **{t('label.on_date', lang)}**: `{r.on_date.isoformat()}`",
            f"- **{t('label.source', lang)}**: `{r.source}`",
            "",
            f"_{t('note.rate', lang)}_",
        ]
    )


def _render_conversion(c: Conversion, lang: str) -> str:
    return "\n".join(
        [
            f"# {t('title.convert', lang)}",
            "",
            f"- **{t('label.amount', lang)}**: `{_fmt_number(c.amount, lang, digits=2)} {c.base}`",
            f"- **{t('label.rate', lang)}**: `{_fmt_number(c.rate, lang)}`",
            f"- **{t('label.converted', lang)}**: "
            f"`{_fmt_number(c.converted, lang, digits=2)} {c.quote}`",
            f"- **{t('label.on_date', lang)}**: `{c.on_date.isoformat()}`",
            f"- **{t('label.source', lang)}**: `{c.source}`",
        ]
    )


def _render_snapshot(s: Snapshot, lang: str) -> str:
    header = "| Quote | Rate |\n|---|---:|"
    rows = [f"| `{e.quote}` | `{_fmt_number(e.rate, lang)}` |" for e in s.rates]
    return "\n".join(
        [
            f"# {t('title.snapshot', lang)}",
            "",
            f"- **{t('label.base', lang)}**: `{s.base}`",
            f"- **{t('label.on_date', lang)}**: `{s.on_date.isoformat()}`",
            f"- **{t('label.source', lang)}**: `{s.source}`",
            "",
            header,
            *rows,
        ]
    )


def _render_timeseries(ts: TimeSeries, lang: str) -> str:
    if not ts.points:
        return f"# {t('title.timeseries', lang)}\n\n_{t('label.no_data', lang)}_"
    header = "| Date | Rate |\n|---|---:|"
    rows = [f"| `{p.on_date.isoformat()}` | `{_fmt_number(p.rate, lang)}` |" for p in ts.points]
    return "\n".join(
        [
            f"# {t('title.timeseries', lang)}",
            "",
            f"- **{t('label.base', lang)}**: `{ts.base}` → `{ts.quote}`",
            f"- {ts.start.isoformat()} → {ts.end.isoformat()} ({len(ts.points)} pts)",
            f"- **{t('label.source', lang)}**: `{ts.source}`",
            "",
            header,
            *rows,
        ]
    )

# === owui/_wrapper.py ===
# Resolved at runtime to either the inlined core symbols (in the bundle) or via
# this synthetic re-export when running from the package tree.


class Tools:
    class Valves(BaseModel):
        DEFAULT_LANGUAGE: str = Field(
            default="en",
            description="Output language. 'en' or 'tr'. Unknown codes fall back to 'en'.",
        )
        DEFAULT_BASE: str = Field(
            default="USD",
            description="Default base currency for snapshot() when caller omits it.",
        )
        DEFAULT_TIMEOUT_SECONDS: int = Field(
            default=10,
            description="HTTP timeout per provider attempt (clamped 2-20).",
        )

    def __init__(self):
        self.valves = self.Valves()
        self.citation = False

    def _lang(self, language: str | None) -> str:
        return (language or self.valves.DEFAULT_LANGUAGE or "en").strip()

    def rate(self, base: str, quote: str, on: str | None = None, language: str | None = None) -> str:
        """
        FX rate (latest or historical) for two ISO 4217 codes.

        Use when: "USD/EUR kuru" / "1 dolar kaç euro". Skip if the user gave
        an amount (use convert), wants many quotes at once (snapshot), or asked
        about crypto / stocks (out of scope).
        """
        lang = self._lang(language)
        result = rate(base, quote, on=on, language=lang)
        return to_markdown(result, lang=lang)

    def convert(
        self,
        amount: float,
        base: str,
        quote: str,
        on: str | None = None,
        language: str | None = None,
    ) -> str:
        """
        Convert an amount between two currencies.

        Use when: "100 USD kaç EUR" / "convert 50 GBP to TRY". Skip if no
        amount was given (use rate). Crypto not supported.
        """
        lang = self._lang(language)
        result = convert(amount, base, quote, on=on, language=lang)
        return to_markdown(result, lang=lang)

    def snapshot(
        self,
        base: str | None = None,
        symbols: list[str] | None = None,
        language: str | None = None,
    ) -> str:
        """
        Latest rates from one base to many quote currencies in one call.

        Use when: "USD against major currencies" / "USD'nin tüm büyük
        paritelere kuru". Skip for single pair (use rate) or historical
        comparison (use timeseries).
        """
        lang = self._lang(language)
        result = snapshot(base or self.valves.DEFAULT_BASE, symbols=symbols, language=lang)
        return to_markdown(result, lang=lang)

    def timeseries(
        self,
        base: str,
        quote: str,
        start: str,
        end: str,
        language: str | None = None,
    ) -> str:
        """
        Daily rates for a pair over a date range (range capped at 366 days).

        Use when: "EUR/USD past 30 days" / "son 30 gün USD/TRY". Skip for a
        single date (use rate with `on`). Range over a year - ask the user
        to narrow before calling.
        """
        lang = self._lang(language)
        result = timeseries(base, quote, start, end, language=lang)
        return to_markdown(result, lang=lang)

