"""
title: FlightHunter
description: Flight search via SerpAPI (Google Flights). Returns ranked options, price insights, and a deep link to the same Google Flights query.
author: Orzed, LLC
version: 1.0.0
required_open_webui_version: 0.5.0
"""

# ────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED BY tools/bundle_owui.py - DO NOT EDIT BY HAND.
# Source of truth: this tool's core/ and owui/_wrapper.py.
# Run `make bundle` (or `python tools/bundle_owui.py <tool>`) to regenerate.
# CI runs `make check-bundle` and fails on drift.
# ────────────────────────────────────────────────────────────────────────────

import httpx
import os
import random
import re
import time
from collections.abc import Iterable
from datetime import date as Date
from pydantic import BaseModel, Field
from typing import Final
from typing import Generic, Literal, TypeVar

# === core/types.py ===
T = TypeVar("T", bound=BaseModel)

ErrorCode = Literal[
    "INVALID_INPUT",
    "NOT_FOUND",
    "RATE_LIMITED",
    "NETWORK_TIMEOUT",
    "UPSTREAM_ERROR",
    "UNSUPPORTED",
    "PARSE_ERROR",
    "TIMEOUT",
    "CANCELLED",
    "INTERNAL",
    "MISSING_API_KEY",
]

TripType = Literal["round_trip", "one_way", "multi_city"]
CabinClass = Literal["economy", "premium_economy", "business", "first"]


class ErrorInfo(BaseModel):
    code: ErrorCode
    message_en: str
    message_tr: str
    hint: str | None = None
    upstream: str | None = None
    retry_after_s: float | None = None


class Result(BaseModel, Generic[T]):
    ok: bool
    data: T | None = None
    error: ErrorInfo | None = None
    meta: dict = Field(default_factory=dict)


class FlightLeg(BaseModel):
    airline: str | None = None
    flight_number: str | None = None
    departure_airport: str | None = None
    arrival_airport: str | None = None
    departure_time: str | None = None
    arrival_time: str | None = None
    duration_minutes: int | None = None
    travel_class: str | None = None
    aircraft: str | None = None


class FlightOption(BaseModel):
    price: float | None = None
    currency: str | None = None
    total_duration_minutes: int | None = None
    stops: int = 0
    layover_airports: list[str] = Field(default_factory=list)
    legs: list[FlightLeg] = Field(default_factory=list)
    booking_token: str | None = None
    type: str | None = None


class PriceInsight(BaseModel):
    lowest: float | None = None
    typical_low: float | None = None
    typical_high: float | None = None
    price_level: str | None = None  # "low" | "typical" | "high"


class FlightSearch(BaseModel):
    origin: str
    destination: str
    departure_date: Date
    return_date: Date | None = None
    trip_type: TripType
    cabin_class: CabinClass
    adults: int
    children: int = 0
    infants: int = 0
    currency: str
    options: list[FlightOption] = Field(default_factory=list)
    price_insight: PriceInsight | None = None
    search_url: str | None = None

# === core/i18n.py ===
STRINGS: Final[dict[str, dict[str, str]]] = {
    "en": {
        "title": "FlightHunter",
        "label.route": "Route",
        "label.dates": "Dates",
        "label.trip_type": "Trip type",
        "label.cabin": "Cabin",
        "label.passengers": "Passengers",
        "label.cheapest": "Cheapest options",
        "label.price_insight": "Price insight",
        "label.no_results": "No flights found.",
        "label.stops": "stops",
        "label.nonstop": "nonstop",
        "label.via": "via",
        "label.adults": "adults",
        "label.children": "children",
        "label.infants": "infants",
        "label.book": "Book on Google Flights",
        "trip.round_trip": "round trip",
        "trip.one_way": "one way",
        "trip.multi_city": "multi-city",
        "cabin.economy": "Economy",
        "cabin.premium_economy": "Premium Economy",
        "cabin.business": "Business",
        "cabin.first": "First",
        "level.low": "below typical",
        "level.typical": "typical",
        "level.high": "above typical",
        "error.missing_api_key": (
            "FLIGHTHUNTER_SERPAPI_KEY environment variable is not set. "
            "Sign up at https://serpapi.com to get one."
        ),
        "error.invalid_iata": "Origin and destination must be 3-letter IATA codes (e.g., IST, LHR).",
        "error.same_origin_destination": "Origin and destination cannot be the same.",
        "error.invalid_date": "Date must be YYYY-MM-DD.",
        "error.return_before_departure": "Return date is before departure date.",
        "error.invalid_passengers": "Total passengers must be 1 to 9; children must be < adults.",
        "error.invalid_cabin": "Cabin class must be economy, premium_economy, business, or first.",
        "error.upstream": "SerpAPI returned an error.",
        "hint.set_key": (
            "Add `FLIGHTHUNTER_SERPAPI_KEY` to your env (Open WebUI Valves or "
            "claude_desktop_config.json env block)."
        ),
        "hint.try_other_dates": "Try a different date or a major airport hub.",
        "note.search": "Prices are SerpAPI snapshots; book directly with the airline for fare guarantees.",
    },
    "tr": {
        "title": "FlightHunter",
        "label.route": "Rota",
        "label.dates": "Tarihler",
        "label.trip_type": "Tip",
        "label.cabin": "Sınıf",
        "label.passengers": "Yolcular",
        "label.cheapest": "En ucuz seçenekler",
        "label.price_insight": "Fiyat seviyesi",
        "label.no_results": "Uçuş bulunamadı.",
        "label.stops": "aktarma",
        "label.nonstop": "aktarmasız",
        "label.via": "üzerinden",
        "label.adults": "yetişkin",
        "label.children": "çocuk",
        "label.infants": "bebek",
        "label.book": "Google Flights'ta Rezerve Et",
        "trip.round_trip": "gidiş-dönüş",
        "trip.one_way": "tek yön",
        "trip.multi_city": "çoklu şehir",
        "cabin.economy": "Ekonomi",
        "cabin.premium_economy": "Premium Ekonomi",
        "cabin.business": "Business",
        "cabin.first": "First",
        "level.low": "tipik altı",
        "level.typical": "tipik",
        "level.high": "tipik üstü",
        "error.missing_api_key": (
            "FLIGHTHUNTER_SERPAPI_KEY env değişkeni ayarlı değil. "
            "https://serpapi.com adresinden ücretsiz alabilirsiniz."
        ),
        "error.invalid_iata": "Origin ve destination 3 harfli IATA kodu olmalı (örn. IST, LHR).",
        "error.same_origin_destination": "Origin ve destination aynı olamaz.",
        "error.invalid_date": "Tarih YYYY-MM-DD formatında olmalı.",
        "error.return_before_departure": "Dönüş tarihi gidişten önce.",
        "error.invalid_passengers": "Yolcu toplamı 1-9; çocuk sayısı yetişkin sayısından az olmalı.",
        "error.invalid_cabin": "Sınıf: economy, premium_economy, business veya first.",
        "error.upstream": "SerpAPI bir hata döndürdü.",
        "hint.set_key": (
            "FLIGHTHUNTER_SERPAPI_KEY'i env'e ekleyin (OWUI Valves veya "
            "claude_desktop_config.json env bloğu)."
        ),
        "hint.try_other_dates": "Farklı bir tarih veya ana havalimanı deneyin.",
        "note.search": (
            "Fiyatlar SerpAPI anlık görüntüsüdür; kesin tarife için havayolu sitesinden rezerve edin."
        ),
    },
}

SUPPORTED: Final[tuple[str, ...]] = ("en", "tr")
DEFAULT: Final[str] = "en"


def normalize_lang(lang: str | None) -> str:
    if not lang:
        return DEFAULT
    base = lang.lower().split("-")[0]
    return base if base in SUPPORTED else DEFAULT


def t(key: str, lang: str = DEFAULT, **kwargs: object) -> str:
    lang = normalize_lang(lang)
    table = STRINGS.get(lang) or STRINGS[DEFAULT]
    template = table.get(key) or STRINGS[DEFAULT].get(key) or key
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError):
        return template

# === core/http.py ===
class RateLimited(Exception):
    def __init__(self, retry_after: float | None = None) -> None:
        self.retry_after = retry_after


class NetworkTimeout(Exception):
    pass


class UpstreamError(Exception):
    def __init__(self, status: int, body: str) -> None:
        self.status = status
        self.body = body


def build_client(
    timeout: float = 30.0, user_agent: str = "orzed-flighthunter/1.0"
) -> httpx.Client:
    return httpx.Client(
        timeout=timeout,
        headers={"User-Agent": user_agent, "Accept": "application/json"},
    )


def get_json_with_retry(
    client: httpx.Client,
    url: str,
    *,
    params: dict | None = None,
    max_attempts: int = 2,
    base_delay: float = 0.5,
) -> dict:
    last_exc: Exception | None = None
    for attempt in range(max_attempts):
        try:
            r = client.get(url, params=params)
        except httpx.TimeoutException:
            last_exc = NetworkTimeout()
        except httpx.RequestError as e:
            last_exc = e
        else:
            if r.status_code == 429:
                ra = r.headers.get("Retry-After")
                last_exc = RateLimited(retry_after=float(ra) if ra else None)
            elif r.status_code in (408, 500, 502, 503, 504):
                last_exc = UpstreamError(r.status_code, r.text[:300])
            elif r.is_success:
                return r.json()
            else:
                raise UpstreamError(r.status_code, r.text[:300])

        if attempt < max_attempts - 1:
            sleep_s = base_delay * (2**attempt) + random.uniform(0, base_delay)
            if isinstance(last_exc, RateLimited) and last_exc.retry_after:
                sleep_s = max(sleep_s, last_exc.retry_after)
            time.sleep(sleep_s)

    if last_exc is not None:
        raise last_exc
    raise UpstreamError(0, "no attempts")

# === core/search.py ===
SERPAPI_ENDPOINT = "https://serpapi.com/search"
IATA_RE = re.compile(r"^[A-Za-z]{3}$")

# SerpAPI travel_class mapping: 1=economy, 2=premium_economy, 3=business, 4=first.
_CABIN_TO_CODE = {"economy": "1", "premium_economy": "2", "business": "3", "first": "4"}
_TRIP_TO_CODE = {"round_trip": "1", "one_way": "2", "multi_city": "3"}


def _err(code: str, lang: str, en_key: str, *, hint_key: str | None = None) -> ErrorInfo:
    return ErrorInfo(
        code=code,
        message_en=t(en_key, "en"),
        message_tr=t(en_key, "tr"),
        hint=t(hint_key, lang) if hint_key else None,
    )


def _parse_date(value, lang: str) -> tuple[Date | None, ErrorInfo | None]:
    if value is None or value == "":
        return None, None
    if isinstance(value, Date):
        return value, None
    try:
        return Date.fromisoformat(str(value).strip()), None
    except ValueError:
        return None, _err("INVALID_INPUT", lang, "error.invalid_date")


def _flatten_options(
    group: Iterable[dict], category: str, fallback_currency: str | None = None
) -> list[FlightOption]:
    out: list[FlightOption] = []
    for item in group or []:
        flights = item.get("flights") or []
        legs = []
        for f in flights:
            legs.append(
                FlightLeg(
                    airline=f.get("airline"),
                    flight_number=f.get("flight_number"),
                    departure_airport=(f.get("departure_airport") or {}).get("id"),
                    arrival_airport=(f.get("arrival_airport") or {}).get("id"),
                    departure_time=(f.get("departure_airport") or {}).get("time"),
                    arrival_time=(f.get("arrival_airport") or {}).get("time"),
                    duration_minutes=f.get("duration"),
                    travel_class=f.get("travel_class"),
                    aircraft=f.get("airplane"),
                )
            )
        layovers = item.get("layovers") or []
        layover_airports = [layover.get("id") for layover in layovers if layover.get("id")]
        out.append(
            FlightOption(
                price=item.get("price"),
                currency=item.get("price_currency") or item.get("currency") or fallback_currency,
                total_duration_minutes=item.get("total_duration"),
                stops=len(layovers),
                layover_airports=[la for la in layover_airports if la],
                legs=legs,
                booking_token=item.get("booking_token"),
                type=category,
            )
        )
    return out


def search_flights(
    origin: str,
    destination: str,
    departure_date: str | Date,
    return_date: str | Date | None = None,
    *,
    cabin_class: str = "economy",
    adults: int = 1,
    children: int = 0,
    infants: int = 0,
    currency: str = "USD",
    language: str = "en",
    api_key: str | None = None,
    client=None,
) -> Result[FlightSearch]:
    lang = normalize_lang(language)

    # ── Inputs ────────────────────────────────────────────────────────────
    if not origin or not IATA_RE.match(origin or "") or not destination or not IATA_RE.match(destination or ""):
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.invalid_iata"))
    origin = origin.upper()
    destination = destination.upper()
    if origin == destination:
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.same_origin_destination"))
    cabin = (cabin_class or "economy").lower()
    if cabin not in _CABIN_TO_CODE:
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.invalid_cabin"))
    if adults < 1 or adults + children + infants > 9 or children > adults:
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.invalid_passengers"))

    departure, derr = _parse_date(departure_date, lang)
    if derr or departure is None:
        return Result(ok=False, error=derr or _err("INVALID_INPUT", lang, "error.invalid_date"))
    return_d, derr = _parse_date(return_date, lang)
    if derr:
        return Result(ok=False, error=derr)
    if return_d and return_d < departure:
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.return_before_departure"))

    trip_type = "round_trip" if return_d else "one_way"

    key = api_key or os.getenv("FLIGHTHUNTER_SERPAPI_KEY") or os.getenv("SERPAPI_API_KEY")
    if not key:
        return Result(
            ok=False,
            error=_err("MISSING_API_KEY", lang, "error.missing_api_key", hint_key="hint.set_key"),
        )

    params = {
        "engine": "google_flights",
        "departure_id": origin,
        "arrival_id": destination,
        "outbound_date": departure.isoformat(),
        "type": _TRIP_TO_CODE[trip_type],
        "travel_class": _CABIN_TO_CODE[cabin],
        "adults": str(adults),
        "currency": currency.upper(),
        "hl": lang,
        "gl": "us" if lang == "en" else lang,
        "api_key": key,
    }
    if children:
        params["children"] = str(children)
    if infants:
        params["infants_in_seat"] = str(infants)
    if return_d:
        params["return_date"] = return_d.isoformat()

    own_client = client is None
    if client is None:
        client = build_client()
    try:
        try:
            payload = get_json_with_retry(client, SERPAPI_ENDPOINT, params=params)
        except (NetworkTimeout, RateLimited, UpstreamError) as exc:
            return Result(
                ok=False,
                error=_err(
                    "RATE_LIMITED" if isinstance(exc, RateLimited) else "UPSTREAM_ERROR",
                    lang,
                    "error.upstream",
                    hint_key="hint.try_other_dates",
                ),
                meta={"upstream": "serpapi"},
            )

        if "error" in payload:
            return Result(
                ok=False,
                error=_err(
                    "UPSTREAM_ERROR",
                    lang,
                    "error.upstream",
                    hint_key="hint.try_other_dates",
                ),
                meta={"serpapi_error": str(payload.get("error"))[:200]},
            )

        best = payload.get("best_flights") or []
        other = payload.get("other_flights") or []
        currency_code = (payload.get("search_parameters") or {}).get("currency") or currency.upper()
        options = (
            _flatten_options(best, "best", fallback_currency=currency_code)
            + _flatten_options(other, "other", fallback_currency=currency_code)
        )

        insight_raw = payload.get("price_insights") or {}
        typical = insight_raw.get("typical_price_range") or [None, None]
        insight = PriceInsight(
            lowest=insight_raw.get("lowest_price"),
            typical_low=typical[0] if isinstance(typical, list) and len(typical) >= 1 else None,
            typical_high=typical[1] if isinstance(typical, list) and len(typical) >= 2 else None,
            price_level=insight_raw.get("price_level"),
        )

        search = FlightSearch(
            origin=origin,
            destination=destination,
            departure_date=departure,
            return_date=return_d,
            trip_type=trip_type,  # type: ignore[arg-type]
            cabin_class=cabin,  # type: ignore[arg-type]
            adults=adults,
            children=children,
            infants=infants,
            currency=currency.upper(),
            options=options,
            price_insight=insight,
            search_url=(payload.get("search_metadata") or {}).get("google_flights_url"),
        )
        return Result(
            ok=True,
            data=search,
            meta={
                "option_count": len(options),
                "best_count": len(best),
                "credits_left": (payload.get("search_metadata") or {}).get("credits_left"),
            },
        )
    finally:
        if own_client:
            client.close()

# === core/render.py ===
def _fmt_duration(minutes: int | None) -> str:
    if not minutes:
        return "?"
    h, m = divmod(int(minutes), 60)
    return f"{h}h{m:02d}m" if h else f"{m}m"


def _fmt_price(value: float | None, currency: str | None) -> str:
    if value is None:
        return "-"
    return f"{value:.0f} {currency or ''}".strip()


def to_markdown(result: Result[FlightSearch], lang: str = "en") -> str:
    if not result.ok or result.data is None:
        if result.error is None:
            return f"**Error**: unknown failure (lang={lang})"
        msg = result.error.message_tr if lang == "tr" else result.error.message_en
        body = f"**Error** ({result.error.code}): {msg}"
        if result.error.hint:
            body += f"\n\n_Hint: {result.error.hint}_"
        return body

    s = result.data
    parts: list[str] = [
        f"# {t('title', lang)}",
        "",
        f"**{t('label.route', lang)}**: `{s.origin}` → `{s.destination}`",
        f"**{t('label.dates', lang)}**: `{s.departure_date.isoformat()}`"
        + (f" ↺ `{s.return_date.isoformat()}`" if s.return_date else ""),
        f"**{t('label.trip_type', lang)}**: {t(f'trip.{s.trip_type}', lang)}  •  "
        f"**{t('label.cabin', lang)}**: {t(f'cabin.{s.cabin_class}', lang)}",
        f"**{t('label.passengers', lang)}**: {s.adults} {t('label.adults', lang)}"
        + (f", {s.children} {t('label.children', lang)}" if s.children else "")
        + (f", {s.infants} {t('label.infants', lang)}" if s.infants else ""),
    ]

    if s.price_insight and s.price_insight.lowest is not None:
        level = s.price_insight.price_level
        parts.append(
            f"**{t('label.price_insight', lang)}**: "
            f"`{_fmt_price(s.price_insight.lowest, s.currency)}`"
            + (f"  ({t(f'level.{level}', lang)})" if level else "")
        )

    parts += ["", f"## {t('label.cheapest', lang)}"]
    if not s.options:
        parts.append(f"_{t('label.no_results', lang)}_")
    else:
        for i, opt in enumerate(s.options[:8], start=1):
            stops_str = (
                t("label.nonstop", lang) if opt.stops == 0 else f"{opt.stops} {t('label.stops', lang)}"
            )
            via = (
                f" ({t('label.via', lang)} {', '.join(opt.layover_airports)})"
                if opt.layover_airports
                else ""
            )
            airlines = ", ".join({leg.airline or "?" for leg in opt.legs})
            parts.append(
                f"{i}. **{_fmt_price(opt.price, opt.currency or s.currency)}** · "
                f"{_fmt_duration(opt.total_duration_minutes)} · {stops_str}{via} · {airlines}"
            )

    if s.search_url:
        parts += ["", f"[{t('label.book', lang)}]({s.search_url})"]

    parts += ["", f"_{t('note.search', lang)}_"]
    return "\n".join(parts)

# === owui/_wrapper.py ===
class Tools:
    class Valves(BaseModel):
        DEFAULT_LANGUAGE: str = Field(
            default="en", description="Output language. 'en' or 'tr'."
        )
        DEFAULT_CURRENCY: str = Field(
            default="USD", description="ISO 4217 currency code for displayed prices."
        )
        SERPAPI_API_KEY: str = Field(
            default="",
            description=(
                "SerpAPI key. If blank, the tool falls back to the "
                "FLIGHTHUNTER_SERPAPI_KEY environment variable."
            ),
        )

    def __init__(self):
        self.valves = self.Valves()
        self.citation = False

    def _lang(self, language: str | None) -> str:
        return (language or self.valves.DEFAULT_LANGUAGE or "en").strip()

    def _api_key(self) -> str | None:
        return self.valves.SERPAPI_API_KEY or os.getenv("FLIGHTHUNTER_SERPAPI_KEY") or None

    def search_flights(
        self,
        origin: str,
        destination: str,
        departure_date: str,
        return_date: str | None = None,
        cabin_class: str = "economy",
        adults: int = 1,
        children: int = 0,
        infants: int = 0,
        currency: str | None = None,
        language: str | None = None,
    ) -> str:
        """
        Search flights via SerpAPI Google Flights.

        Use when: "find flights IST to LHR Sep 1" / "İstanbul Londra uçuş bul
        1 eylül". Skip if origin/destination are city names without IATA codes
        (ask the user first), for trains / buses / hotels, or generic travel
        advice without dates. Each call costs 1 SerpAPI credit.
        """
        lang = self._lang(language)
        result = search_flights(
            origin,
            destination,
            departure_date,
            return_date=return_date,
            cabin_class=cabin_class,
            adults=adults,
            children=children,
            infants=infants,
            currency=currency or self.valves.DEFAULT_CURRENCY,
            language=lang,
            api_key=self._api_key(),
        )
        return to_markdown(result, lang=lang)

