"""
title: QRForge
description: Generate QR codes for arbitrary text, URLs, Wi-Fi credentials, and vCard contacts. Local rendering by default; opt-in remote fallback for non-sensitive payloads.
author: Orzed, LLC
version: 1.0.0
required_open_webui_version: 0.5.0
"""

# ────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED BY tools/bundle_owui.py — DO NOT EDIT BY HAND.
# Source of truth: this tool's core/ and owui/_wrapper.py.
# Run `make bundle` (or `python tools/bundle_owui.py <tool>`) to regenerate.
# CI runs `make check-bundle` and fails on drift.
# ────────────────────────────────────────────────────────────────────────────

import base64
import io
import re
import urllib.parse
from pydantic import BaseModel, Field
from typing import Final
from typing import Generic, Literal, TypeVar

# === core/types.py ===
T = TypeVar("T", bound=BaseModel)

ErrorCode = Literal[
    "INVALID_INPUT",
    "NOT_FOUND",
    "RATE_LIMITED",
    "NETWORK_TIMEOUT",
    "UPSTREAM_ERROR",
    "UNSUPPORTED",
    "PARSE_ERROR",
    "TIMEOUT",
    "CANCELLED",
    "INTERNAL",
]

PayloadKind = Literal["text", "url", "wifi", "vcard"]
EcLevel = Literal["L", "M", "Q", "H"]
WifiEncryption = Literal["WPA", "WEP", "NOPASS"]
ImageSource = Literal["local", "remote"]


class ErrorInfo(BaseModel):
    code: ErrorCode
    message_en: str
    message_tr: str
    hint: str | None = None
    upstream: str | None = None
    retry_after_s: float | None = None


class Result(BaseModel, Generic[T]):
    ok: bool
    data: T | None = None
    error: ErrorInfo | None = None
    meta: dict = Field(default_factory=dict)


class QrImage(BaseModel):
    """Represents a generated QR code image plus its metadata."""

    format: Literal["png"] = "png"
    source: ImageSource
    data_b64: str | None = Field(
        default=None,
        description="Base64-encoded PNG bytes when source=='local'.",
    )
    remote_url: str | None = Field(
        default=None,
        description="Full URL pointing to a remote QR rendering service when source=='remote'.",
    )
    byte_length: int = Field(
        default=0,
        description="Decoded PNG byte length (0 for remote-only images).",
    )
    pixel_size: int
    border: int
    ec_level: EcLevel
    payload_kind: PayloadKind
    payload_preview: str = Field(
        description="First 80 characters of the encoded payload, for inspection.",
    )

# === core/i18n.py ===
STRINGS: Final[dict[str, dict[str, str]]] = {
    "en": {
        "title": "QRForge",
        "label.size": "Size",
        "label.payload_chars": "Payload length",
        "label.ec_level": "Error correction",
        "label.kind": "Kind",
        "label.source": "Source",
        "kind.text": "Text",
        "kind.url": "URL",
        "kind.wifi": "Wi-Fi",
        "kind.vcard": "vCard",
        "source.local": "local (in-process)",
        "source.remote": "remote (api.qrserver.com)",
        "note.local": "Generated locally. Payload was not sent to any third party.",
        "note.remote": (
            "Generated via remote service. The payload was sent to api.qrserver.com — "
            "do not use remote rendering for sensitive data."
        ),
        "warning.remote_used": "Remote rendering was used.",
        "error.empty_payload": "QR payload is empty.",
        "error.invalid_url": "Input does not look like a valid URL (expected http(s)://...).",
        "error.invalid_email": "Email address looks invalid.",
        "error.invalid_phone": "Phone number looks invalid.",
        "error.invalid_ec_level": "Error-correction level must be one of L, M, Q, H.",
        "error.invalid_encryption": "Wi-Fi encryption must be one of WPA, WEP, NOPASS.",
        "error.invalid_size": "Image size must be between 64 and 4096 pixels.",
        "error.invalid_border": "Border must be between 0 and 16 modules.",
        "error.qrcode_missing": "Local 'qrcode' library is not installed.",
        "error.remote_disabled_for_sensitive": (
            "Remote fallback is not allowed for {kind} payloads (security)."
        ),
        "error.remote_disabled": "Remote fallback is disabled (USE_REMOTE_FALLBACK=False).",
        "error.payload_too_large": (
            "Payload exceeds the QR capacity at the requested error-correction level."
        ),
        "error.internal": "Unexpected error: {detail}",
        "hint.install_qrcode": (
            "Install with `pip install qrcode[pil]`. Inside an OWUI container: "
            "`docker exec -it open-webui pip install qrcode[pil]` then restart the container."
        ),
        "hint.try_lower_ec": "Try a lower error-correction level (L) or shorten the payload.",
        "hint.use_local_for_secrets": (
            "Generate Wi-Fi/vCard QR codes locally only — install `qrcode[pil]`."
        ),
        "hint.url_scheme": "Add an explicit scheme such as https:// to the URL.",
    },
    "tr": {
        "title": "QRForge",
        "label.size": "Boyut",
        "label.payload_chars": "Veri uzunluğu",
        "label.ec_level": "Hata düzeltme",
        "label.kind": "Tür",
        "label.source": "Kaynak",
        "kind.text": "Metin",
        "kind.url": "URL",
        "kind.wifi": "Wi-Fi",
        "kind.vcard": "vCard",
        "source.local": "yerel (süreç içi)",
        "source.remote": "uzak (api.qrserver.com)",
        "note.local": "Yerelde üretildi. Veri üçüncü tarafa gönderilmedi.",
        "note.remote": (
            "Uzak servis ile üretildi. Veri api.qrserver.com'a gönderildi — "
            "hassas verilerde uzak üretim kullanmayın."
        ),
        "warning.remote_used": "Uzak üretim kullanıldı.",
        "error.empty_payload": "QR verisi boş.",
        "error.invalid_url": "URL geçerli görünmüyor (http(s)://... bekleniyor).",
        "error.invalid_email": "E-posta adresi geçerli görünmüyor.",
        "error.invalid_phone": "Telefon numarası geçerli görünmüyor.",
        "error.invalid_ec_level": "Hata düzeltme seviyesi L, M, Q veya H olmalı.",
        "error.invalid_encryption": "Wi-Fi şifreleme WPA, WEP veya NOPASS olmalı.",
        "error.invalid_size": "Görsel boyutu 64 ile 4096 piksel arasında olmalı.",
        "error.invalid_border": "Kenar (border) 0 ile 16 modül arasında olmalı.",
        "error.qrcode_missing": "'qrcode' kütüphanesi yüklü değil.",
        "error.remote_disabled_for_sensitive": (
            "{kind} verileri için uzak üretim güvenlik nedeniyle kapalı."
        ),
        "error.remote_disabled": "Uzak fallback kapalı (USE_REMOTE_FALLBACK=False).",
        "error.payload_too_large": (
            "Veri, seçilen hata düzeltme seviyesinde QR kapasitesini aşıyor."
        ),
        "error.internal": "Beklenmeyen hata: {detail}",
        "hint.install_qrcode": (
            "Kurulum: `pip install qrcode[pil]`. OWUI container içinde: "
            "`docker exec -it open-webui pip install qrcode[pil]`, sonra container'ı yeniden başlatın."
        ),
        "hint.try_lower_ec": "Daha düşük hata düzeltme (L) deneyin veya veriyi kısaltın.",
        "hint.use_local_for_secrets": (
            "Wi-Fi/vCard QR kodlarını yalnızca yerel üretim ile alın — `qrcode[pil]` kurun."
        ),
        "hint.url_scheme": "URL'e açık bir şema ekleyin (örneğin https://).",
    },
}

SUPPORTED: Final[tuple[str, ...]] = ("en", "tr")
DEFAULT: Final[str] = "en"


def normalize_lang(lang: str | None) -> str:
    """Map any language tag to a supported code; unknown -> DEFAULT ('en')."""
    if not lang:
        return DEFAULT
    base = lang.lower().split("-")[0]
    return base if base in SUPPORTED else DEFAULT


def t(key: str, lang: str = DEFAULT, **kwargs: object) -> str:
    """Look up a string for `lang`; fall back to en, then to the key itself.

    Missing format placeholders are tolerated (returns the unformatted template),
    so a typo in a kwarg shows up as visible debug text instead of an exception.
    """
    lang = normalize_lang(lang)
    table = STRINGS.get(lang) or STRINGS[DEFAULT]
    template = table.get(key) or STRINGS[DEFAULT].get(key) or key
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError):
        return template

# === core/qr.py ===
_DEFAULT_REMOTE_BASE = "https://api.qrserver.com/v1/create-qr-code/"
_VCARD_FIELD_PATTERN = re.compile(r"[\r\n]+")
_PHONE_PATTERN = re.compile(r"^[+]?[\d\-\s().]{4,}$")
_EMAIL_PATTERN = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
_URL_PATTERN = re.compile(r"^https?://[^\s]+$", re.IGNORECASE)
_VALID_EC_LEVELS = ("L", "M", "Q", "H")
_VALID_ENCRYPTIONS = ("WPA", "WEP", "NOPASS")


def _err(
    code: str,
    lang: str,
    en_key: str,
    tr_key: str | None = None,
    *,
    hint_key: str | None = None,
    fmt: dict | None = None,
) -> ErrorInfo:
    fmt = fmt or {}
    return ErrorInfo(
        code=code,
        message_en=t(en_key, "en", **fmt),
        message_tr=t(tr_key or en_key, "tr", **fmt),
        hint=t(hint_key, lang, **fmt) if hint_key else None,
    )


def _wifi_payload(ssid: str, password: str, encryption: WifiEncryption, hidden: bool) -> str:
    def esc(value: str) -> str:
        return (
            value.replace("\\", "\\\\")
            .replace(";", "\\;")
            .replace(",", "\\,")
            .replace(":", "\\:")
            .replace('"', '\\"')
        )

    hidden_token = "true" if hidden else "false"
    if encryption == "NOPASS":
        return f"WIFI:T:nopass;S:{esc(ssid)};H:{hidden_token};;"
    return f"WIFI:T:{encryption};S:{esc(ssid)};P:{esc(password)};H:{hidden_token};;"


def _vcard_payload(
    full_name: str,
    phone: str,
    email: str,
    org: str,
    title: str,
    url: str,
) -> str:
    def clean(value: str) -> str:
        return _VCARD_FIELD_PATTERN.sub(" ", value).replace(";", "\\;").replace(",", "\\,")

    lines = [
        "BEGIN:VCARD",
        "VERSION:3.0",
        f"FN:{clean(full_name)}",
    ]
    if org:
        lines.append(f"ORG:{clean(org)}")
    if title:
        lines.append(f"TITLE:{clean(title)}")
    if phone:
        lines.append(f"TEL:{clean(phone)}")
    if email:
        lines.append(f"EMAIL:{clean(email)}")
    if url:
        lines.append(f"URL:{clean(url)}")
    lines.append("END:VCARD")
    return "\r\n".join(lines)


def _remote_qr_url(data: str, size: int, base_url: str) -> str:
    encoded = urllib.parse.urlencode({"size": f"{size}x{size}", "data": data})
    return f"{base_url}?{encoded}"


def _generate_local_png(data: str, size: int, border: int, ec_level: EcLevel) -> bytes | None:
    """Return PNG bytes via the `qrcode` library, or None if it's not installed.

    Raises on payload-too-large; the caller must classify that into a Result error.
    """
    try:
        import qrcode
        from qrcode.constants import (
            ERROR_CORRECT_H,
            ERROR_CORRECT_L,
            ERROR_CORRECT_M,
            ERROR_CORRECT_Q,
        )
    except ImportError:
        return None

    correction_map = {
        "L": ERROR_CORRECT_L,
        "M": ERROR_CORRECT_M,
        "Q": ERROR_CORRECT_Q,
        "H": ERROR_CORRECT_H,
    }
    qr = qrcode.QRCode(
        version=None,
        error_correction=correction_map[ec_level],
        box_size=10,
        border=border,
    )
    qr.add_data(data)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white").convert("RGB")
    img = img.resize((size, size))
    with io.BytesIO() as buffer:
        img.save(buffer, format="PNG")
        return buffer.getvalue()


def _build_image(
    payload: str,
    payload_kind: PayloadKind,
    size: int,
    border: int,
    ec_level: EcLevel,
    use_remote_fallback: bool,
    remote_base_url: str,
    language: str,
) -> Result[QrImage]:
    if not payload:
        return Result(ok=False, error=_err("INVALID_INPUT", language, "error.empty_payload"))
    if ec_level not in _VALID_EC_LEVELS:
        return Result(ok=False, error=_err("INVALID_INPUT", language, "error.invalid_ec_level"))
    if not (64 <= size <= 4096):
        return Result(ok=False, error=_err("INVALID_INPUT", language, "error.invalid_size"))
    if not (0 <= border <= 16):
        return Result(ok=False, error=_err("INVALID_INPUT", language, "error.invalid_border"))

    try:
        png_bytes = _generate_local_png(payload, size=size, border=border, ec_level=ec_level)
    except Exception as exc:  # qrcode raises on capacity overflow, etc.
        message = str(exc).lower()
        if "data" in message and ("too" in message or "long" in message or "exceed" in message):
            return Result(
                ok=False,
                error=_err(
                    "INVALID_INPUT",
                    language,
                    "error.payload_too_large",
                    hint_key="hint.try_lower_ec",
                ),
            )
        return Result(
            ok=False,
            error=_err(
                "INTERNAL",
                language,
                "error.internal",
                fmt={"detail": str(exc)[:120]},
            ),
        )

    if png_bytes is not None:
        b64 = base64.b64encode(png_bytes).decode("ascii")
        image = QrImage(
            source="local",
            data_b64=b64,
            byte_length=len(png_bytes),
            pixel_size=size,
            border=border,
            ec_level=ec_level,
            payload_kind=payload_kind,
            payload_preview=payload[:80],
        )
        return Result(ok=True, data=image, meta={"source": "local"})

    # Local generation unavailable. Decide whether to fall back to remote.
    sensitive = payload_kind in ("wifi", "vcard")
    if sensitive:
        return Result(
            ok=False,
            error=_err(
                "UNSUPPORTED",
                language,
                "error.remote_disabled_for_sensitive",
                hint_key="hint.use_local_for_secrets",
                fmt={"kind": payload_kind},
            ),
        )
    if not use_remote_fallback:
        return Result(
            ok=False,
            error=_err(
                "UNSUPPORTED",
                language,
                "error.qrcode_missing",
                hint_key="hint.install_qrcode",
            ),
        )

    remote_url = _remote_qr_url(payload, size=size, base_url=remote_base_url)
    image = QrImage(
        source="remote",
        remote_url=remote_url,
        byte_length=0,
        pixel_size=size,
        border=border,
        ec_level=ec_level,
        payload_kind=payload_kind,
        payload_preview=payload[:80],
    )
    return Result(
        ok=True,
        data=image,
        meta={
            "source": "remote",
            "warning": "remote_fallback_used",
            "warning_message": t("warning.remote_used", language),
        },
    )


def qr_text(
    text: str,
    *,
    size: int = 512,
    border: int = 4,
    ec_level: EcLevel = "M",
    use_remote_fallback: bool = False,
    remote_base_url: str = _DEFAULT_REMOTE_BASE,
    language: str = "en",
) -> Result[QrImage]:
    """Encode arbitrary text as a QR code."""
    return _build_image(
        payload=(text or "").strip(),
        payload_kind="text",
        size=size,
        border=border,
        ec_level=ec_level,
        use_remote_fallback=use_remote_fallback,
        remote_base_url=remote_base_url,
        language=language,
    )


def qr_url(
    url: str,
    *,
    size: int = 512,
    border: int = 4,
    ec_level: EcLevel = "M",
    use_remote_fallback: bool = False,
    remote_base_url: str = _DEFAULT_REMOTE_BASE,
    language: str = "en",
) -> Result[QrImage]:
    """Encode a URL as a QR code; rejects anything missing an http(s) scheme."""
    cleaned = (url or "").strip()
    if not cleaned:
        return Result(ok=False, error=_err("INVALID_INPUT", language, "error.empty_payload"))
    if not _URL_PATTERN.match(cleaned):
        return Result(
            ok=False,
            error=_err(
                "INVALID_INPUT",
                language,
                "error.invalid_url",
                hint_key="hint.url_scheme",
            ),
        )
    return _build_image(
        payload=cleaned,
        payload_kind="url",
        size=size,
        border=border,
        ec_level=ec_level,
        use_remote_fallback=use_remote_fallback,
        remote_base_url=remote_base_url,
        language=language,
    )


def qr_wifi(
    ssid: str,
    *,
    password: str = "",
    encryption: WifiEncryption = "WPA",
    hidden: bool = False,
    size: int = 512,
    border: int = 4,
    ec_level: EcLevel = "M",
    language: str = "en",
) -> Result[QrImage]:
    """Encode Wi-Fi credentials as a QR code. Remote fallback is forbidden."""
    cleaned_ssid = (ssid or "").strip()
    if not cleaned_ssid:
        return Result(ok=False, error=_err("INVALID_INPUT", language, "error.empty_payload"))
    enc = (encryption or "WPA").upper()
    if enc not in _VALID_ENCRYPTIONS:
        return Result(ok=False, error=_err("INVALID_INPUT", language, "error.invalid_encryption"))
    payload = _wifi_payload(
        ssid=cleaned_ssid,
        password=password or "",
        encryption=enc,  # type: ignore[arg-type]
        hidden=bool(hidden),
    )
    return _build_image(
        payload=payload,
        payload_kind="wifi",
        size=size,
        border=border,
        ec_level=ec_level,
        use_remote_fallback=False,  # explicit: never remote for wifi
        remote_base_url=_DEFAULT_REMOTE_BASE,
        language=language,
    )


def qr_vcard(
    full_name: str,
    *,
    phone: str = "",
    email: str = "",
    org: str = "",
    title: str = "",
    url: str = "",
    size: int = 512,
    border: int = 4,
    ec_level: EcLevel = "M",
    language: str = "en",
) -> Result[QrImage]:
    """Encode contact details as a QR code (vCard 3.0). Remote fallback is forbidden."""
    cleaned_name = (full_name or "").strip()
    if not cleaned_name:
        return Result(ok=False, error=_err("INVALID_INPUT", language, "error.empty_payload"))
    if phone and not _PHONE_PATTERN.match(phone.strip()):
        return Result(ok=False, error=_err("INVALID_INPUT", language, "error.invalid_phone"))
    if email and not _EMAIL_PATTERN.match(email.strip()):
        return Result(ok=False, error=_err("INVALID_INPUT", language, "error.invalid_email"))
    if url and not _URL_PATTERN.match(url.strip()):
        return Result(ok=False, error=_err("INVALID_INPUT", language, "error.invalid_url"))

    payload = _vcard_payload(
        full_name=cleaned_name,
        phone=phone or "",
        email=email or "",
        org=org or "",
        title=title or "",
        url=url or "",
    )
    return _build_image(
        payload=payload,
        payload_kind="vcard",
        size=size,
        border=border,
        ec_level=ec_level,
        use_remote_fallback=False,  # explicit: never remote for vcard
        remote_base_url=_DEFAULT_REMOTE_BASE,
        language=language,
    )

# === core/render.py ===
def to_markdown(result: Result[QrImage], lang: str = "en") -> str:
    """Render a Result[QrImage] as a markdown block suitable for chat display."""
    if not result.ok or result.data is None:
        if result.error is None:
            return f"**Error**: unknown failure (lang={lang})"
        message = result.error.message_tr if lang == "tr" else result.error.message_en
        body = f"**Error** ({result.error.code}): {message}"
        if result.error.hint:
            body += f"\n\n_Hint: {result.error.hint}_"
        return body

    img = result.data
    title = t("title", lang)
    kind_label = t(f"kind.{img.payload_kind}", lang)
    source_label = t(f"source.{img.source}", lang)
    note_key = "note.local" if img.source == "local" else "note.remote"

    if img.source == "local" and img.data_b64:
        embed = f"data:image/png;base64,{img.data_b64}"
    elif img.remote_url:
        embed = img.remote_url
    else:
        embed = ""

    lines = [
        f"# {title}",
        "",
        f"- **{t('label.kind', lang)}**: {kind_label}",
        f"- **{t('label.size', lang)}**: `{img.pixel_size}x{img.pixel_size}`",
        f"- **{t('label.ec_level', lang)}**: `{img.ec_level}`",
        f"- **{t('label.payload_chars', lang)}**: `{len(img.payload_preview)}"
        + ("+` (truncated)" if len(img.payload_preview) >= 80 else "`"),
        f"- **{t('label.source', lang)}**: {source_label}",
        "",
        f"![QR Code]({embed})" if embed else "_(no image)_",
        "",
        f"_{t(note_key, lang)}_",
    ]
    return "\n".join(lines)

# === owui/_wrapper.py ===
class Tools:
    class Valves(BaseModel):
        DEFAULT_LANGUAGE: str = Field(
            default="en",
            description="Output language for messages. 'en' or 'tr'. Unknown codes fall back to 'en'.",
        )
        DEFAULT_SIZE: int = Field(
            default=512,
            description="Default QR image edge length in pixels. Range 64-4096.",
        )
        DEFAULT_BORDER: int = Field(
            default=4,
            description="Default QR quiet-zone border (modules). Range 0-16.",
        )
        DEFAULT_EC_LEVEL: str = Field(
            default="M",
            description="Default error correction level. One of L, M, Q, H. Higher is more robust but denser.",
        )
        USE_REMOTE_FALLBACK: bool = Field(
            default=False,
            description=(
                "If the local 'qrcode' library is missing, fall back to api.qrserver.com "
                "for text/URL payloads only. Wi-Fi and vCard always require local rendering."
            ),
        )

    def __init__(self):
        self.valves = self.Valves()
        self.citation = False

    def _lang(self, language: str | None) -> str:
        return (language or self.valves.DEFAULT_LANGUAGE or "en").strip()

    def qr_text(
        self,
        text: str,
        size: int | None = None,
        border: int | None = None,
        ec_level: str | None = None,
        language: str | None = None,
    ) -> str:
        """
        Generate a QR code for arbitrary text or any payload.

        :param text: Payload to encode.
        :param size: Image edge length in pixels (64-4096).
        :param border: Quiet-zone width in modules (0-16).
        :param ec_level: Error correction level: L, M, Q, or H.
        :param language: Output language ('en' or 'tr').
        """
        lang = self._lang(language)
        result = qr_text(
            text,
            size=size or self.valves.DEFAULT_SIZE,
            border=border if border is not None else self.valves.DEFAULT_BORDER,
            ec_level=(ec_level or self.valves.DEFAULT_EC_LEVEL).upper(),
            use_remote_fallback=self.valves.USE_REMOTE_FALLBACK,
            language=lang,
        )
        return to_markdown(result, lang=lang)

    def qr_url(
        self,
        url: str,
        size: int | None = None,
        border: int | None = None,
        ec_level: str | None = None,
        language: str | None = None,
    ) -> str:
        """
        Generate a QR code for an HTTP(S) URL. Rejects schemeless inputs.

        :param url: Full URL including http:// or https://.
        """
        lang = self._lang(language)
        result = qr_url(
            url,
            size=size or self.valves.DEFAULT_SIZE,
            border=border if border is not None else self.valves.DEFAULT_BORDER,
            ec_level=(ec_level or self.valves.DEFAULT_EC_LEVEL).upper(),
            use_remote_fallback=self.valves.USE_REMOTE_FALLBACK,
            language=lang,
        )
        return to_markdown(result, lang=lang)

    def qr_wifi(
        self,
        ssid: str,
        password: str = "",
        encryption: str = "WPA",
        hidden: bool = False,
        size: int | None = None,
        border: int | None = None,
        ec_level: str | None = None,
        language: str | None = None,
    ) -> str:
        """
        Generate a Wi-Fi connection QR code (WIFI:... payload).
        Remote fallback is forbidden for Wi-Fi credentials.

        :param ssid: Wi-Fi network name.
        :param password: Wi-Fi password (empty for NOPASS).
        :param encryption: One of WPA, WEP, NOPASS.
        :param hidden: True if the network is hidden.
        """
        lang = self._lang(language)
        result = qr_wifi(
            ssid,
            password=password,
            encryption=encryption.upper(),
            hidden=hidden,
            size=size or self.valves.DEFAULT_SIZE,
            border=border if border is not None else self.valves.DEFAULT_BORDER,
            ec_level=(ec_level or self.valves.DEFAULT_EC_LEVEL).upper(),
            language=lang,
        )
        return to_markdown(result, lang=lang)

    def qr_vcard(
        self,
        full_name: str,
        phone: str = "",
        email: str = "",
        org: str = "",
        title: str = "",
        url: str = "",
        size: int | None = None,
        border: int | None = None,
        ec_level: str | None = None,
        language: str | None = None,
    ) -> str:
        """
        Generate a vCard 3.0 contact QR code.
        Remote fallback is forbidden — contact data should not leave the host.

        :param full_name: Full name.
        :param phone: Phone number.
        :param email: Email address.
        :param org: Organization / company.
        :param title: Job title.
        :param url: Website URL.
        """
        lang = self._lang(language)
        result = qr_vcard(
            full_name,
            phone=phone,
            email=email,
            org=org,
            title=title,
            url=url,
            size=size or self.valves.DEFAULT_SIZE,
            border=border if border is not None else self.valves.DEFAULT_BORDER,
            ec_level=(ec_level or self.valves.DEFAULT_EC_LEVEL).upper(),
            language=lang,
        )
        return to_markdown(result, lang=lang)

