"""
title: PageSignal
description: Audit a URL for SEO and AI-answer-readiness (GEO). Returns meta tags, headings, readability, schema/JSON-LD types, and a prioritized issue list.
author: Orzed, LLC
version: 1.0.0
required_open_webui_version: 0.5.0
"""

# ────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED BY tools/bundle_owui.py — DO NOT EDIT BY HAND.
# Source of truth: this tool's core/ and owui/_wrapper.py.
# Run `make bundle` (or `python tools/bundle_owui.py <tool>`) to regenerate.
# CI runs `make check-bundle` and fails on drift.
# ────────────────────────────────────────────────────────────────────────────

import httpx
import json
import random
import re
import time
from html.parser import HTMLParser
from pydantic import BaseModel, Field
from typing import Final
from typing import Generic, Literal, TypeVar

# === core/types.py ===
T = TypeVar("T", bound=BaseModel)

ErrorCode = Literal[
    "INVALID_INPUT",
    "NOT_FOUND",
    "RATE_LIMITED",
    "NETWORK_TIMEOUT",
    "UPSTREAM_ERROR",
    "UNSUPPORTED",
    "PARSE_ERROR",
    "TIMEOUT",
    "CANCELLED",
    "INTERNAL",
]

IssueSeverity = Literal["info", "warning", "error"]


class ErrorInfo(BaseModel):
    code: ErrorCode
    message_en: str
    message_tr: str
    hint: str | None = None
    upstream: str | None = None
    retry_after_s: float | None = None


class Result(BaseModel, Generic[T]):
    ok: bool
    data: T | None = None
    error: ErrorInfo | None = None
    meta: dict = Field(default_factory=dict)


class MetaTags(BaseModel):
    title: str | None = None
    title_length: int = 0
    description: str | None = None
    description_length: int = 0
    canonical: str | None = None
    robots: str | None = None
    og_title: str | None = None
    og_description: str | None = None
    og_image: str | None = None
    twitter_card: str | None = None
    lang: str | None = None
    charset: str | None = None


class HeadingsInfo(BaseModel):
    h1_count: int = 0
    h1_texts: list[str] = Field(default_factory=list)
    h2_count: int = 0
    h2_texts: list[str] = Field(default_factory=list)
    h3_count: int = 0
    skipped_levels: list[str] = Field(default_factory=list)


class Readability(BaseModel):
    word_count: int = 0
    sentence_count: int = 0
    avg_sentence_length: float = 0.0
    detected_language: str | None = None


class GeoSignals(BaseModel):
    """Signals that indicate AI-answer readiness (GEO = generative engine optimization)."""

    has_faq_schema: bool = False
    has_question_schema: bool = False
    has_howto_schema: bool = False
    has_article_schema: bool = False
    schema_types: list[str] = Field(default_factory=list)
    question_headings: list[str] = Field(default_factory=list)
    answers_first_mode: bool = False  # Heading immediately followed by direct answer text
    keywords_found: dict[str, int] = Field(default_factory=dict)


class Performance(BaseModel):
    bytes_total: int = 0
    bytes_html: int = 0
    response_time_ms: int = 0
    redirect_count: int = 0
    final_url: str | None = None
    status_code: int = 0


class Issue(BaseModel):
    severity: IssueSeverity
    code: str
    message_en: str
    message_tr: str


class PageAudit(BaseModel):
    url: str
    final_url: str
    meta_tags: MetaTags
    headings: HeadingsInfo
    readability: Readability
    geo_signals: GeoSignals
    performance: Performance
    issues: list[Issue]

# === core/i18n.py ===
STRINGS: Final[dict[str, dict[str, str]]] = {
    "en": {
        "title": "PageSignal",
        "section.meta": "Meta Tags",
        "section.headings": "Headings",
        "section.readability": "Readability",
        "section.geo": "AI-Answer Signals (GEO)",
        "section.performance": "Performance",
        "section.issues": "Issues",
        "label.url": "URL",
        "label.final_url": "Final URL",
        "label.title": "Title",
        "label.description": "Description",
        "label.canonical": "Canonical",
        "label.robots": "Robots",
        "label.lang": "Language",
        "label.h1_count": "H1 count",
        "label.h2_count": "H2 count",
        "label.word_count": "Word count",
        "label.sentence_count": "Sentence count",
        "label.avg_sentence_length": "Avg sentence length",
        "label.detected_language": "Detected language",
        "label.schema_types": "Schema types",
        "label.question_headings": "Question-style headings",
        "label.bytes": "Bytes",
        "label.response_time": "Response time",
        "label.status": "Status code",
        "label.redirects": "Redirects",
        "label.no_issues": "No issues found.",
        "issue.empty_title": "Title tag is missing or empty.",
        "issue.title_too_short": "Title is shorter than 30 characters.",
        "issue.title_too_long": "Title exceeds 65 characters; may be truncated by search engines.",
        "issue.empty_description": "Meta description is missing.",
        "issue.description_too_short": "Meta description is shorter than 70 characters.",
        "issue.description_too_long": "Meta description exceeds 160 characters.",
        "issue.no_h1": "Page has no H1 heading.",
        "issue.multiple_h1": "Page has multiple H1 headings; pick one canonical title.",
        "issue.skipped_heading_levels": "Heading hierarchy skipped levels: {levels}",
        "issue.no_canonical": "No canonical link element.",
        "issue.no_open_graph": "Open Graph tags are missing — social previews will be generic.",
        "issue.noindex": "Page is marked noindex; it will not be indexed.",
        "issue.no_lang": "<html> has no lang attribute.",
        "issue.no_schema": "No structured data (JSON-LD) detected.",
        "issue.javascript_heavy": "Body contains very little text — looks JS-rendered. AI crawlers may see less.",
        "issue.large_response": "HTML payload exceeds {kb} KB.",
        "issue.slow_response": "Response time {ms} ms exceeds the 1500 ms target.",
        "error.url_required": "URL is required.",
        "error.invalid_url": "URL must include http:// or https://.",
        "error.unreachable": "Could not fetch the page (network or server error).",
        "error.unsupported_content_type": "Unsupported content type: {ct}.",
        "hint.try_https": "Try the https:// variant of the URL.",
        "hint.spa": "Look for a server-rendered route or test with a headless browser.",
        "note.audit": (
            "PageSignal audits a single URL. For domain-level health (DNS, SSL, RDAP) "
            "see sitepulse."
        ),
    },
    "tr": {
        "title": "PageSignal",
        "section.meta": "Meta Etiketleri",
        "section.headings": "Başlıklar",
        "section.readability": "Okunabilirlik",
        "section.geo": "Yapay Zekâ Cevap Sinyalleri (GEO)",
        "section.performance": "Performans",
        "section.issues": "Bulgular",
        "label.url": "URL",
        "label.final_url": "Son URL",
        "label.title": "Başlık",
        "label.description": "Açıklama",
        "label.canonical": "Canonical",
        "label.robots": "Robots",
        "label.lang": "Dil",
        "label.h1_count": "H1 sayısı",
        "label.h2_count": "H2 sayısı",
        "label.word_count": "Kelime",
        "label.sentence_count": "Cümle",
        "label.avg_sentence_length": "Ortalama cümle uzunluğu",
        "label.detected_language": "Tespit edilen dil",
        "label.schema_types": "Schema türleri",
        "label.question_headings": "Soru biçimli başlıklar",
        "label.bytes": "Bayt",
        "label.response_time": "Yanıt süresi",
        "label.status": "Durum kodu",
        "label.redirects": "Yönlendirmeler",
        "label.no_issues": "Bulgu yok.",
        "issue.empty_title": "Başlık etiketi yok veya boş.",
        "issue.title_too_short": "Başlık 30 karakterden kısa.",
        "issue.title_too_long": "Başlık 65 karakteri aşıyor; arama sonucunda kesilebilir.",
        "issue.empty_description": "Meta açıklama yok.",
        "issue.description_too_short": "Meta açıklama 70 karakterden kısa.",
        "issue.description_too_long": "Meta açıklama 160 karakteri aşıyor.",
        "issue.no_h1": "Sayfada H1 başlığı yok.",
        "issue.multiple_h1": "Birden fazla H1 var; tek canonical başlık tercih edin.",
        "issue.skipped_heading_levels": "Başlık seviyeleri atlanmış: {levels}",
        "issue.no_canonical": "Canonical bağlantısı yok.",
        "issue.no_open_graph": "Open Graph etiketleri eksik — sosyal medya önizlemeleri sade olur.",
        "issue.noindex": "Sayfa noindex olarak işaretli; arama motoru indekslemez.",
        "issue.no_lang": "<html> etiketinde lang yok.",
        "issue.no_schema": "Yapılandırılmış veri (JSON-LD) bulunamadı.",
        "issue.javascript_heavy": "Gövdede metin çok az; JS ile render ediliyor olabilir. AI tarayıcılar daha az görür.",
        "issue.large_response": "HTML yükü {kb} KB'yi aşıyor.",
        "issue.slow_response": "Yanıt süresi {ms} ms; 1500 ms hedefini aşıyor.",
        "error.url_required": "URL zorunlu.",
        "error.invalid_url": "URL http:// veya https:// içermeli.",
        "error.unreachable": "Sayfa çekilemedi (ağ veya sunucu hatası).",
        "error.unsupported_content_type": "Desteklenmeyen içerik türü: {ct}.",
        "hint.try_https": "URL'in https:// varyantını deneyin.",
        "hint.spa": "Sunucu render eden bir varyant deneyin veya headless browser kullanın.",
        "note.audit": (
            "PageSignal tek bir URL'i denetler. Alan adı sağlığı (DNS, SSL, RDAP) "
            "için sitepulse'ı kullanın."
        ),
    },
}

SUPPORTED: Final[tuple[str, ...]] = ("en", "tr")
DEFAULT: Final[str] = "en"


def normalize_lang(lang: str | None) -> str:
    if not lang:
        return DEFAULT
    base = lang.lower().split("-")[0]
    return base if base in SUPPORTED else DEFAULT


def t(key: str, lang: str = DEFAULT, **kwargs: object) -> str:
    lang = normalize_lang(lang)
    table = STRINGS.get(lang) or STRINGS[DEFAULT]
    template = table.get(key) or STRINGS[DEFAULT].get(key) or key
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError):
        return template

# === core/lexicons.py ===
QUESTION_WORDS: dict[str, frozenset[str]] = {
    "en": frozenset(
        {
            "what", "why", "how", "when", "where", "who", "which", "whose",
            "is", "are", "do", "does", "did", "can", "could", "should",
            "would", "will",
        }
    ),
    "tr": frozenset(
        {
            "ne", "nedir", "neden", "niye", "niçin", "nasıl", "nasil", "ne zaman",
            "nerede", "kim", "kimdir", "hangi", "hangisi", "kaç", "kac",
        }
    ),
    "de": frozenset(
        {
            "was", "warum", "wieso", "weshalb", "wie", "wann", "wo", "woher",
            "wohin", "wer", "wessen", "welche", "welcher", "welches",
        }
    ),
    "es": frozenset(
        {
            "qué", "que", "por qué", "porqué", "cómo", "como", "cuándo", "cuando",
            "dónde", "donde", "quién", "quien", "cuál", "cual", "cuáles", "cuales",
        }
    ),
    "fr": frozenset(
        {
            "que", "quoi", "pourquoi", "comment", "quand", "où", "ou", "qui",
            "quel", "quelle", "quels", "quelles",
        }
    ),
    "it": frozenset(
        {
            "che", "cosa", "perché", "perche", "come", "quando", "dove",
            "chi", "quale", "quali",
        }
    ),
    "pt": frozenset(
        {
            "que", "o que", "por que", "porque", "como", "quando", "onde", "quem",
            "qual", "quais",
        }
    ),
    "ar": frozenset(
        {
            "ما", "ماذا", "لماذا", "كيف", "متى", "أين", "اين", "من", "أي", "اي",
        }
    ),
}


def is_question(text: str, language: str) -> bool:
    """True if the text begins with a question-word in the given language, or ends with '?'."""
    if not text:
        return False
    stripped = text.strip()
    if stripped.endswith("?") or stripped.endswith("؟"):
        return True
    lower = stripped.lower()
    words = QUESTION_WORDS.get(language) or set()
    for w in words:
        if lower.startswith(w + " ") or lower == w:
            return True
    return False

# === core/http.py ===
class RateLimited(Exception):
    def __init__(self, retry_after: float | None = None) -> None:
        self.retry_after = retry_after


class NetworkTimeout(Exception):
    pass


class UpstreamError(Exception):
    def __init__(self, status: int, body: str) -> None:
        self.status = status
        self.body = body


def build_client(
    timeout: float = 10.0, user_agent: str = "orzed-mcp-essentials/1.0"
) -> httpx.Client:
    return httpx.Client(
        timeout=timeout,
        headers={"User-Agent": user_agent},
        follow_redirects=True,
    )


def get_with_retry(
    client: httpx.Client,
    url: str,
    *,
    params: dict | None = None,
    max_attempts: int = 3,
    base_delay: float = 0.5,
) -> httpx.Response:
    """Return the full Response object; caller decides text/bytes/json."""
    last_exc: Exception | None = None
    for attempt in range(max_attempts):
        try:
            r = client.get(url, params=params)
        except httpx.TimeoutException:
            last_exc = NetworkTimeout()
        except httpx.RequestError as e:
            last_exc = e
        else:
            if r.status_code == 429:
                ra = r.headers.get("Retry-After")
                last_exc = RateLimited(retry_after=float(ra) if ra else None)
            elif r.status_code in (408, 500, 502, 503, 504):
                last_exc = UpstreamError(r.status_code, r.text[:500])
            else:
                return r

        if attempt < max_attempts - 1:
            sleep_s = base_delay * (2**attempt) + random.uniform(0, base_delay)
            if isinstance(last_exc, RateLimited) and last_exc.retry_after:
                sleep_s = max(sleep_s, last_exc.retry_after)
            time.sleep(sleep_s)

    if last_exc is not None:
        raise last_exc
    raise UpstreamError(0, "no attempts succeeded")

# === core/parse.py ===
WORD_RE = re.compile(r"\w+", re.UNICODE)
SENTENCE_SPLIT_RE = re.compile(r"[.!?؟]+")
WHITESPACE_RE = re.compile(r"\s+")


class PageDocument(HTMLParser):
    """Single-pass HTML walker that collects everything pagesignal needs."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.title_parts: list[str] = []
        self._in_title = False

        self.meta_description: str | None = None
        self.canonical: str | None = None
        self.robots: str | None = None
        self.og_title: str | None = None
        self.og_description: str | None = None
        self.og_image: str | None = None
        self.twitter_card: str | None = None
        self.html_lang: str | None = None
        self.charset: str | None = None

        self.h1: list[str] = []
        self.h2: list[str] = []
        self.h3: list[str] = []
        self._heading_stack: list[tuple[str, list[str]]] = []
        self.heading_sequence: list[str] = []  # h1, h2, ...

        self.body_text_parts: list[str] = []
        self._in_body = False
        self._suppress_depth = 0  # script/style nesting

        self.jsonld_blobs: list[str] = []
        self._in_jsonld = False
        self._current_jsonld: list[str] = []

    # ── boilerplate handlers ─────────────────────────────────────────────
    def handle_starttag(self, tag, attrs):
        tag = tag.lower()
        attr_dict = {k.lower(): v for k, v in attrs}

        if tag == "html":
            self.html_lang = attr_dict.get("lang") or self.html_lang
        elif tag == "title":
            self._in_title = True
        elif tag == "meta":
            self._handle_meta(attr_dict)
        elif tag == "link" and attr_dict.get("rel", "").lower() == "canonical":
            self.canonical = attr_dict.get("href") or self.canonical
        elif tag in ("h1", "h2", "h3"):
            self._heading_stack.append((tag, []))
            self.heading_sequence.append(tag)
        elif tag == "body":
            self._in_body = True
        elif tag in ("script", "style", "noscript"):
            self._suppress_depth += 1
            if tag == "script" and (attr_dict.get("type") or "").lower() == "application/ld+json":
                self._in_jsonld = True
                self._current_jsonld = []

    def handle_endtag(self, tag):
        tag = tag.lower()
        if tag == "title":
            self._in_title = False
        elif tag in ("h1", "h2", "h3") and self._heading_stack:
            level, parts = self._heading_stack.pop()
            text = WHITESPACE_RE.sub(" ", "".join(parts)).strip()
            if level == "h1":
                self.h1.append(text)
            elif level == "h2":
                self.h2.append(text)
            elif level == "h3":
                self.h3.append(text)
        elif tag in ("script", "style", "noscript"):
            self._suppress_depth = max(0, self._suppress_depth - 1)
            if self._in_jsonld:
                self.jsonld_blobs.append("".join(self._current_jsonld))
                self._in_jsonld = False
                self._current_jsonld = []

    def handle_data(self, data: str) -> None:
        if self._in_title:
            self.title_parts.append(data)
        if self._heading_stack:
            self._heading_stack[-1][1].append(data)
        if self._in_jsonld:
            self._current_jsonld.append(data)
        if self._in_body and self._suppress_depth == 0:
            self.body_text_parts.append(data)

    # ── meta detail ──────────────────────────────────────────────────────
    def _handle_meta(self, attrs: dict[str, str]) -> None:
        name = (attrs.get("name") or "").lower()
        prop = (attrs.get("property") or "").lower()
        content = attrs.get("content") or ""
        charset = attrs.get("charset")
        if charset and self.charset is None:
            self.charset = charset
        if not content:
            return
        if name == "description":
            self.meta_description = content
        elif name == "robots":
            self.robots = content
        elif prop == "og:title":
            self.og_title = content
        elif prop == "og:description":
            self.og_description = content
        elif prop == "og:image":
            self.og_image = content
        elif name == "twitter:card":
            self.twitter_card = content

    # ── derived ──────────────────────────────────────────────────────────
    @property
    def title(self) -> str | None:
        text = WHITESPACE_RE.sub(" ", "".join(self.title_parts)).strip()
        return text or None

    @property
    def body_text(self) -> str:
        return WHITESPACE_RE.sub(" ", "".join(self.body_text_parts)).strip()


def parse_jsonld_types(blobs: list[str]) -> list[str]:
    out: list[str] = []
    for blob in blobs:
        try:
            data = json.loads(blob)
        except (json.JSONDecodeError, ValueError):
            continue

        def visit(obj):
            if isinstance(obj, dict):
                t = obj.get("@type")
                if isinstance(t, str):
                    out.append(t)
                elif isinstance(t, list):
                    out.extend(x for x in t if isinstance(x, str))
                for v in obj.values():
                    visit(v)
            elif isinstance(obj, list):
                for v in obj:
                    visit(v)

        visit(data)
    # Stable, deduped, lowercase hint preserved.
    seen: set[str] = set()
    dedup: list[str] = []
    for t in out:
        if t.lower() in seen:
            continue
        seen.add(t.lower())
        dedup.append(t)
    return dedup


def word_count(text: str) -> int:
    return len(WORD_RE.findall(text))


def sentence_count(text: str) -> int:
    parts = [p.strip() for p in SENTENCE_SPLIT_RE.split(text) if p.strip()]
    return max(1, len(parts)) if text.strip() else 0

# === core/audit.py ===
DEFAULT_USER_AGENT = "orzed-pagesignal/1.0 (+https://orzed.com)"
LARGE_RESPONSE_KB = 1024
SLOW_RESPONSE_MS = 1500


def _err(code: str, lang: str, en_key: str, *, fmt: dict | None = None,
         hint_key: str | None = None) -> ErrorInfo:
    fmt = fmt or {}
    return ErrorInfo(
        code=code,
        message_en=t(en_key, "en", **fmt),
        message_tr=t(en_key, "tr", **fmt),
        hint=t(hint_key, lang, **fmt) if hint_key else None,
    )


def _make_issue(severity: str, code: str, lang: str, en_key: str,
                 fmt: dict | None = None) -> Issue:
    fmt = fmt or {}
    return Issue(
        severity=severity,  # type: ignore[arg-type]
        code=code,
        message_en=t(en_key, "en", **fmt),
        message_tr=t(en_key, "tr", **fmt),
    )


def _detect_skipped_levels(sequence: list[str]) -> list[str]:
    """Return a list of "h1->h3" style strings for any heading that skipped a level."""
    skips: list[str] = []
    last_level = 0
    for h in sequence:
        level = int(h[1])
        if last_level and level - last_level > 1:
            skips.append(f"{['h0','h1','h2','h3'][last_level]}->{h}")
        last_level = level
    return skips


def _detect_language_hint(html_lang: str | None) -> str | None:
    if not html_lang:
        return None
    return html_lang.lower().split("-")[0][:5]


def audit_page(
    url: str,
    target_keywords: list[str] | None = None,
    *,
    language: str = "en",
    timeout_seconds: float = 10.0,
    user_agent: str = DEFAULT_USER_AGENT,
    client=None,
) -> Result[PageAudit]:
    lang = normalize_lang(language)

    if not url or not isinstance(url, str):
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.url_required"))
    cleaned = url.strip()
    if not (cleaned.startswith("http://") or cleaned.startswith("https://")):
        return Result(
            ok=False,
            error=_err(
                "INVALID_INPUT",
                lang,
                "error.invalid_url",
                hint_key="hint.try_https",
            ),
        )

    own_client = client is None
    if client is None:
        client = build_client(timeout=timeout_seconds, user_agent=user_agent)

    started = time.monotonic()
    try:
        try:
            response = get_with_retry(client, cleaned)
        except (NetworkTimeout, RateLimited, UpstreamError) as exc:
            upstream = getattr(exc, "status", None)
            return Result(
                ok=False,
                error=_err(
                    "UPSTREAM_ERROR" if isinstance(exc, UpstreamError) else "NETWORK_TIMEOUT",
                    lang,
                    "error.unreachable",
                    fmt={"detail": str(exc)},
                ),
                meta={"upstream_status": upstream} if upstream else {},
            )
        elapsed_ms = int((time.monotonic() - started) * 1000)

        content_type = (response.headers.get("Content-Type") or "").lower()
        if content_type and "html" not in content_type and "xml" not in content_type:
            return Result(
                ok=False,
                error=_err(
                    "UNSUPPORTED",
                    lang,
                    "error.unsupported_content_type",
                    fmt={"ct": content_type},
                ),
            )

        body_bytes = response.content or b""
        try:
            text = body_bytes.decode(response.encoding or "utf-8", errors="replace")
        except (LookupError, AttributeError):
            text = body_bytes.decode("utf-8", errors="replace")
    finally:
        if own_client:
            client.close()

    doc = PageDocument()
    try:
        doc.feed(text)
    except Exception as exc:  # html.parser is permissive; this is rare
        return Result(
            ok=False,
            error=_err("PARSE_ERROR", lang, "error.unreachable", fmt={"detail": str(exc)}),
        )

    issues: list[Issue] = []

    # ── Meta tags ────────────────────────────────────────────────────────
    title = doc.title or ""
    description = doc.meta_description or ""
    meta = MetaTags(
        title=title or None,
        title_length=len(title),
        description=description or None,
        description_length=len(description),
        canonical=doc.canonical,
        robots=doc.robots,
        og_title=doc.og_title,
        og_description=doc.og_description,
        og_image=doc.og_image,
        twitter_card=doc.twitter_card,
        lang=doc.html_lang,
        charset=doc.charset,
    )
    if not title:
        issues.append(_make_issue("error", "empty_title", lang, "issue.empty_title"))
    elif len(title) < 30:
        issues.append(_make_issue("warning", "title_too_short", lang, "issue.title_too_short"))
    elif len(title) > 65:
        issues.append(_make_issue("warning", "title_too_long", lang, "issue.title_too_long"))
    if not description:
        issues.append(_make_issue("warning", "empty_description", lang, "issue.empty_description"))
    elif len(description) < 70:
        issues.append(
            _make_issue("info", "description_too_short", lang, "issue.description_too_short")
        )
    elif len(description) > 160:
        issues.append(
            _make_issue("warning", "description_too_long", lang, "issue.description_too_long")
        )
    if not doc.canonical:
        issues.append(_make_issue("info", "no_canonical", lang, "issue.no_canonical"))
    if not (doc.og_title or doc.og_description):
        issues.append(_make_issue("info", "no_open_graph", lang, "issue.no_open_graph"))
    if not doc.html_lang:
        issues.append(_make_issue("info", "no_lang", lang, "issue.no_lang"))
    if doc.robots and "noindex" in doc.robots.lower():
        issues.append(_make_issue("error", "noindex", lang, "issue.noindex"))

    # ── Headings ─────────────────────────────────────────────────────────
    skipped = _detect_skipped_levels(doc.heading_sequence)
    headings = HeadingsInfo(
        h1_count=len(doc.h1),
        h1_texts=doc.h1[:5],
        h2_count=len(doc.h2),
        h2_texts=doc.h2[:10],
        h3_count=len(doc.h3),
        skipped_levels=skipped,
    )
    if len(doc.h1) == 0:
        issues.append(_make_issue("warning", "no_h1", lang, "issue.no_h1"))
    elif len(doc.h1) > 1:
        issues.append(_make_issue("warning", "multiple_h1", lang, "issue.multiple_h1"))
    if skipped:
        issues.append(
            _make_issue(
                "info",
                "skipped_heading_levels",
                lang,
                "issue.skipped_heading_levels",
                fmt={"levels": ", ".join(skipped)},
            )
        )

    # ── Readability ──────────────────────────────────────────────────────
    body_text = doc.body_text
    wc = word_count(body_text)
    sc = sentence_count(body_text)
    avg = (wc / sc) if sc else 0.0
    detected_lang = _detect_language_hint(doc.html_lang) or lang
    readability = Readability(
        word_count=wc,
        sentence_count=sc,
        avg_sentence_length=round(avg, 1),
        detected_language=detected_lang,
    )
    # Heuristic: very short body text on a non-trivial page suggests JS rendering.
    if wc < 50 and len(body_bytes) > 4_000:
        issues.append(
            _make_issue("warning", "javascript_heavy", lang, "issue.javascript_heavy")
        )

    # ── GEO signals ──────────────────────────────────────────────────────
    schema_types = parse_jsonld_types(doc.jsonld_blobs)
    schema_lower = {t.lower() for t in schema_types}
    detection_lang = detected_lang if detected_lang in ("en", "tr", "de", "es", "fr", "it", "pt", "ar") else "en"
    question_headings = [h for h in (*doc.h1, *doc.h2, *doc.h3) if is_question(h, detection_lang)]
    keywords_found: dict[str, int] = {}
    if target_keywords:
        haystack = (title + " " + description + " " + body_text).lower()
        for kw in target_keywords:
            if not kw:
                continue
            keywords_found[kw] = haystack.count(kw.lower())
    geo = GeoSignals(
        has_faq_schema="faqpage" in schema_lower,
        has_question_schema="question" in schema_lower,
        has_howto_schema="howto" in schema_lower,
        has_article_schema="article" in schema_lower or "newsarticle" in schema_lower,
        schema_types=schema_types,
        question_headings=question_headings[:8],
        answers_first_mode=bool(question_headings),
        keywords_found=keywords_found,
    )
    if not schema_types:
        issues.append(_make_issue("info", "no_schema", lang, "issue.no_schema"))

    # ── Performance ──────────────────────────────────────────────────────
    perf = Performance(
        bytes_total=len(body_bytes),
        bytes_html=len(body_bytes),
        response_time_ms=elapsed_ms,
        redirect_count=len(response.history),
        final_url=str(response.url),
        status_code=response.status_code,
    )
    if len(body_bytes) > LARGE_RESPONSE_KB * 1024:
        issues.append(
            _make_issue(
                "info",
                "large_response",
                lang,
                "issue.large_response",
                fmt={"kb": LARGE_RESPONSE_KB},
            )
        )
    if elapsed_ms > SLOW_RESPONSE_MS:
        issues.append(
            _make_issue(
                "info",
                "slow_response",
                lang,
                "issue.slow_response",
                fmt={"ms": elapsed_ms},
            )
        )

    audit = PageAudit(
        url=cleaned,
        final_url=str(response.url),
        meta_tags=meta,
        headings=headings,
        readability=readability,
        geo_signals=geo,
        performance=perf,
        issues=issues,
    )
    return Result(ok=True, data=audit, meta={"final_url": str(response.url)})

# === core/render.py ===
def to_markdown(result: Result[PageAudit], lang: str = "en") -> str:
    if not result.ok or result.data is None:
        if result.error is None:
            return f"**Error**: unknown failure (lang={lang})"
        msg = result.error.message_tr if lang == "tr" else result.error.message_en
        body = f"**Error** ({result.error.code}): {msg}"
        if result.error.hint:
            body += f"\n\n_Hint: {result.error.hint}_"
        return body

    a = result.data
    title = t("title", lang)
    parts: list[str] = [
        f"# {title}",
        "",
        f"**{t('label.url', lang)}**: `{a.url}`",
    ]
    if a.final_url and a.final_url != a.url:
        parts.append(f"**{t('label.final_url', lang)}**: `{a.final_url}`")

    parts += [
        "",
        f"## {t('section.meta', lang)}",
        f"- **{t('label.title', lang)}** ({a.meta_tags.title_length} chars): "
        f"{a.meta_tags.title or '_(missing)_'}",
        f"- **{t('label.description', lang)}** ({a.meta_tags.description_length} chars): "
        f"{a.meta_tags.description or '_(missing)_'}",
        f"- **{t('label.canonical', lang)}**: `{a.meta_tags.canonical or '—'}`",
        f"- **{t('label.robots', lang)}**: `{a.meta_tags.robots or '—'}`",
        f"- **{t('label.lang', lang)}**: `{a.meta_tags.lang or '—'}`",
    ]
    parts += [
        "",
        f"## {t('section.headings', lang)}",
        f"- **{t('label.h1_count', lang)}**: {a.headings.h1_count}"
        + (f" — _{', '.join(a.headings.h1_texts[:3])}_" if a.headings.h1_texts else ""),
        f"- **{t('label.h2_count', lang)}**: {a.headings.h2_count}",
    ]
    parts += [
        "",
        f"## {t('section.readability', lang)}",
        f"- **{t('label.word_count', lang)}**: {a.readability.word_count}",
        f"- **{t('label.sentence_count', lang)}**: {a.readability.sentence_count}",
        f"- **{t('label.avg_sentence_length', lang)}**: {a.readability.avg_sentence_length}",
        f"- **{t('label.detected_language', lang)}**: `{a.readability.detected_language or '—'}`",
    ]
    parts += [
        "",
        f"## {t('section.geo', lang)}",
        f"- FAQ: {'✓' if a.geo_signals.has_faq_schema else '—'}  "
        f"HowTo: {'✓' if a.geo_signals.has_howto_schema else '—'}  "
        f"Article: {'✓' if a.geo_signals.has_article_schema else '—'}  "
        f"Question: {'✓' if a.geo_signals.has_question_schema else '—'}",
        f"- **{t('label.schema_types', lang)}**: "
        f"{', '.join(f'`{s}`' for s in a.geo_signals.schema_types) or '—'}",
        f"- **{t('label.question_headings', lang)}** "
        f"({len(a.geo_signals.question_headings)}): "
        + (
            ", ".join(f"_{q}_" for q in a.geo_signals.question_headings[:5])
            or "—"
        ),
    ]
    if a.geo_signals.keywords_found:
        kw_lines = ", ".join(
            f"`{k}`: {v}" for k, v in a.geo_signals.keywords_found.items()
        )
        parts.append(f"- Keyword hits: {kw_lines}")

    parts += [
        "",
        f"## {t('section.performance', lang)}",
        f"- **{t('label.status', lang)}**: `{a.performance.status_code}`  "
        f"**{t('label.redirects', lang)}**: {a.performance.redirect_count}",
        f"- **{t('label.bytes', lang)}**: {a.performance.bytes_total}",
        f"- **{t('label.response_time', lang)}**: `{a.performance.response_time_ms} ms`",
    ]

    parts += ["", f"## {t('section.issues', lang)}"]
    if not a.issues:
        parts.append(f"_{t('label.no_issues', lang)}_")
    else:
        emoji = {"info": "ℹ︎", "warning": "⚠︎", "error": "✗"}
        for issue in a.issues:
            mark = emoji.get(issue.severity, "•")
            msg = issue.message_tr if lang == "tr" else issue.message_en
            parts.append(f"- {mark} **{issue.severity}** `{issue.code}` — {msg}")

    parts += ["", f"_{t('note.audit', lang)}_"]
    return "\n".join(parts)

# === owui/_wrapper.py ===
class Tools:
    class Valves(BaseModel):
        DEFAULT_LANGUAGE: str = Field(
            default="en",
            description="Output language. 'en' or 'tr'. Unknown codes fall back to 'en'.",
        )
        TIMEOUT_SECONDS: float = Field(
            default=10.0,
            description="HTTP timeout (seconds).",
        )
        USER_AGENT: str = Field(
            default="orzed-pagesignal/1.0 (+https://orzed.com)",
            description="User-Agent sent to the audited site.",
        )

    def __init__(self):
        self.valves = self.Valves()
        self.citation = False

    def _lang(self, language: str | None) -> str:
        return (language or self.valves.DEFAULT_LANGUAGE or "en").strip()

    def audit_page(
        self,
        url: str,
        target_keywords: list[str] | None = None,
        language: str | None = None,
    ) -> str:
        """
        Audit a URL: SEO + AI-answer-readiness signals.

        :param url: Full http(s) URL.
        :param target_keywords: Optional keyword list to count in body+title+desc.
        :param language: 'en' or 'tr'.
        """
        lang = self._lang(language)
        result = audit_page(
            url,
            target_keywords=target_keywords,
            language=lang,
            timeout_seconds=self.valves.TIMEOUT_SECONDS,
            user_agent=self.valves.USER_AGENT,
        )
        return to_markdown(result, lang=lang)

