"""
title: TubeScript
description: Fetch YouTube transcripts as text, SRT, VTT, or JSON. Auto-detects video ID from any URL variant. Honors prefer_lang ordering and YouTube's translation feature.
author: Orzed, LLC
version: 1.0.0
required_open_webui_version: 0.5.0
"""

# ────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED BY tools/bundle_owui.py — DO NOT EDIT BY HAND.
# Source of truth: this tool's core/ and owui/_wrapper.py.
# Run `make bundle` (or `python tools/bundle_owui.py <tool>`) to regenerate.
# CI runs `make check-bundle` and fails on drift.
# ────────────────────────────────────────────────────────────────────────────

import json as json_module
import re
import urllib.parse
from pydantic import BaseModel, Field
from typing import Final
from typing import Generic, Literal, TypeVar

# === core/types.py ===
T = TypeVar("T", bound=BaseModel)

ErrorCode = Literal[
    "INVALID_INPUT",
    "NOT_FOUND",
    "RATE_LIMITED",
    "NETWORK_TIMEOUT",
    "UPSTREAM_ERROR",
    "UNSUPPORTED",
    "PARSE_ERROR",
    "TIMEOUT",
    "CANCELLED",
    "INTERNAL",
]

TranscriptFormat = Literal["text", "srt", "vtt", "json"]


class ErrorInfo(BaseModel):
    code: ErrorCode
    message_en: str
    message_tr: str
    hint: str | None = None
    upstream: str | None = None
    retry_after_s: float | None = None


class Result(BaseModel, Generic[T]):
    ok: bool
    data: T | None = None
    error: ErrorInfo | None = None
    meta: dict = Field(default_factory=dict)


class AvailableTrack(BaseModel):
    language: str
    language_code: str
    is_generated: bool = False
    is_translatable: bool = False


class TranscriptList(BaseModel):
    video_id: str
    tracks: list[AvailableTrack]


class TranscriptEntry(BaseModel):
    start: float
    duration: float
    text: str


class Transcript(BaseModel):
    video_id: str
    language_code: str
    is_generated: bool
    translated_to: str | None = None
    format: TranscriptFormat
    text: str = Field(description="The formatted transcript content (text/srt/vtt or JSON string).")
    entries: list[TranscriptEntry] = Field(default_factory=list)
    truncated: bool = False
    char_count: int = 0

# === core/i18n.py ===
STRINGS: Final[dict[str, dict[str, str]]] = {
    "en": {
        "title.list": "Transcript Tracks",
        "title.transcript": "Transcript",
        "label.video_id": "Video ID",
        "label.language": "Language",
        "label.is_generated": "Auto-generated",
        "label.translated_to": "Translated to",
        "label.format": "Format",
        "label.chars": "Characters",
        "label.entries": "Entries",
        "label.tracks": "Available tracks",
        "error.empty_input": "URL or video ID is required.",
        "error.invalid_id": "Could not extract a YouTube video ID from the input.",
        "error.no_transcripts": "No transcripts are available for this video.",
        "error.transcripts_disabled": "Transcripts are disabled for this video.",
        "error.video_unavailable": (
            "Video is unavailable (private, deleted, region-blocked, or age-restricted)."
        ),
        "error.translation_unavailable": "Requested translation language is not available.",
        "error.preferred_unavailable": "None of the preferred languages are available.",
        "error.invalid_format": "Format must be one of: text, srt, vtt, json.",
        "error.upstream": "YouTube returned an unexpected error.",
        "hint.try_translate_to": "Try setting translate_to to en/tr if a language pair is supported.",
        "hint.list_first": "Call list_transcripts first to see which languages are available.",
        "note.truncated": "Output truncated at the word boundary nearest max_chars.",
    },
    "tr": {
        "title.list": "Transkript Kanalları",
        "title.transcript": "Transkript",
        "label.video_id": "Video ID",
        "label.language": "Dil",
        "label.is_generated": "Otomatik üretilmiş",
        "label.translated_to": "Çevrildiği dil",
        "label.format": "Biçim",
        "label.chars": "Karakter",
        "label.entries": "Giriş",
        "label.tracks": "Mevcut kanallar",
        "error.empty_input": "URL veya video ID zorunlu.",
        "error.invalid_id": "Girdiden YouTube video ID çıkarılamadı.",
        "error.no_transcripts": "Bu video için transkript yok.",
        "error.transcripts_disabled": "Bu videoda transkript devre dışı.",
        "error.video_unavailable": (
            "Video mevcut değil (özel, silinmiş, bölge kısıtlı veya yaş kısıtlı)."
        ),
        "error.translation_unavailable": "İstenen çeviri dili mevcut değil.",
        "error.preferred_unavailable": "Tercih edilen dillerin hiçbiri yok.",
        "error.invalid_format": "Biçim şunlardan biri olmalı: text, srt, vtt, json.",
        "error.upstream": "YouTube beklenmeyen bir hata döndürdü.",
        "hint.try_translate_to": "Desteklenen dil çiftleri için translate_to=en/tr deneyin.",
        "hint.list_first": "Hangi dillerin mevcut olduğunu görmek için list_transcripts'i çağırın.",
        "note.truncated": "Çıktı, max_chars'a en yakın kelime sınırında kesildi.",
    },
}

SUPPORTED: Final[tuple[str, ...]] = ("en", "tr")
DEFAULT: Final[str] = "en"


def normalize_lang(lang: str | None) -> str:
    if not lang:
        return DEFAULT
    base = lang.lower().split("-")[0]
    return base if base in SUPPORTED else DEFAULT


def t(key: str, lang: str = DEFAULT, **kwargs: object) -> str:
    lang = normalize_lang(lang)
    table = STRINGS.get(lang) or STRINGS[DEFAULT]
    template = table.get(key) or STRINGS[DEFAULT].get(key) or key
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError):
        return template

# === core/extract.py ===
_ID_RE = re.compile(r"^[A-Za-z0-9_-]{11}$")
_PATTERNS = [
    re.compile(r"(?:v=|/v/|youtu\.be/|/embed/|/shorts/|/live/)([A-Za-z0-9_-]{11})"),
]


def extract_video_id(input_str: str) -> str | None:
    """Return the 11-char YouTube ID from a URL or raw ID. None on failure."""
    if not input_str:
        return None
    raw = input_str.strip()
    if _ID_RE.match(raw):
        return raw
    if "://" not in raw:
        # Try common short forms first.
        m = _PATTERNS[0].search(raw)
        if m:
            return m.group(1)
        return None
    try:
        parsed = urllib.parse.urlparse(raw)
    except ValueError:
        return None
    host = (parsed.netloc or "").lower()
    if "youtube.com" in host or "youtu.be" in host or "youtube-nocookie.com" in host:
        # /watch?v=ID
        qs = urllib.parse.parse_qs(parsed.query)
        if "v" in qs and qs["v"]:
            cand = qs["v"][0]
            if _ID_RE.match(cand):
                return cand
        m = _PATTERNS[0].search(raw)
        if m:
            return m.group(1)
    return None

# === core/format.py ===
def _ts(seconds: float, sep: str = ",") -> str:
    """SRT-style HH:MM:SS,mmm (sep=',') or VTT-style HH:MM:SS.mmm (sep='.')."""
    if seconds is None or seconds < 0:
        seconds = 0.0
    total_ms = int(round(seconds * 1000))
    h, rem = divmod(total_ms, 3_600_000)
    m, rem = divmod(rem, 60_000)
    s, ms = divmod(rem, 1000)
    return f"{h:02d}:{m:02d}:{s:02d}{sep}{ms:03d}"


def format_transcript(entries: list[dict], fmt: str) -> str:
    """Render the entry list to text/srt/vtt/json.

    `entries` items: {start, duration, text}.
    """
    if fmt == "text":
        return "\n".join(e["text"] for e in entries if e.get("text")).strip()

    if fmt == "json":
        return json_module.dumps(entries, ensure_ascii=False, indent=2)

    if fmt == "srt":
        out = []
        for i, e in enumerate(entries, start=1):
            start = float(e.get("start", 0.0))
            dur = float(e.get("duration", 0.0))
            text = (e.get("text") or "").strip()
            if not text:
                continue
            out.append(str(i))
            out.append(f"{_ts(start, ',')} --> {_ts(start + dur, ',')}")
            out.append(text)
            out.append("")
        return "\n".join(out).strip()

    if fmt == "vtt":
        out = ["WEBVTT", ""]
        for e in entries:
            start = float(e.get("start", 0.0))
            dur = float(e.get("duration", 0.0))
            text = (e.get("text") or "").strip()
            if not text:
                continue
            out.append(f"{_ts(start, '.')} --> {_ts(start + dur, '.')}")
            out.append(text)
            out.append("")
        return "\n".join(out).strip()

    raise ValueError(f"unknown format: {fmt}")


def truncate_at_word_boundary(text: str, max_chars: int) -> tuple[str, bool]:
    """Cut text at the last whitespace ≤ max_chars. Returns (truncated_text, was_truncated)."""
    if max_chars is None or max_chars <= 0 or len(text) <= max_chars:
        return text, False
    cut = text[:max_chars]
    last_space = max(cut.rfind(" "), cut.rfind("\n"))
    if last_space > 0:
        cut = cut[:last_space]
    return cut.rstrip() + "\n…(truncated)", True

# === core/transcript.py ===
def _err(code: str, lang: str, en_key: str, *, hint_key: str | None = None,
         fmt: dict | None = None) -> ErrorInfo:
    fmt = fmt or {}
    return ErrorInfo(
        code=code,
        message_en=t(en_key, "en", **fmt),
        message_tr=t(en_key, "tr", **fmt),
        hint=t(hint_key, lang, **fmt) if hint_key else None,
    )


def _make_api():
    """Lazy import so monkeypatching for tests is straightforward."""
    from youtube_transcript_api import YouTubeTranscriptApi

    return YouTubeTranscriptApi()


def _classify_exception(exc: Exception, lang: str) -> ErrorInfo:
    """Map a youtube-transcript-api exception to a typed Result error.

    Classifies on the class name *or* the exception message so we don't have to
    import every concrete exception type from the library (which churns) and so
    tests can simulate them with plain RuntimeErrors.
    """
    name = exc.__class__.__name__
    text = str(exc)
    fingerprint = f"{name} {text}"
    if "TranscriptsDisabled" in fingerprint:
        return _err("UNSUPPORTED", lang, "error.transcripts_disabled", hint_key="hint.list_first")
    if "NoTranscriptFound" in fingerprint or "NoTranscriptAvailable" in fingerprint:
        return _err("NOT_FOUND", lang, "error.preferred_unavailable", hint_key="hint.list_first")
    if (
        "VideoUnavailable" in fingerprint
        or "AgeRestricted" in fingerprint
        or "RegionBlocked" in fingerprint
    ):
        return _err("UNSUPPORTED", lang, "error.video_unavailable")
    if "TranslationLanguageNotAvailable" in fingerprint:
        return _err(
            "UNSUPPORTED", lang, "error.translation_unavailable", hint_key="hint.list_first"
        )
    return _err("UPSTREAM_ERROR", lang, "error.upstream", hint_key="hint.list_first")


def list_transcripts(input_str: str, *, language: str = "en", api=None) -> Result[TranscriptList]:
    lang = normalize_lang(language)
    if not input_str:
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.empty_input"))
    vid = extract_video_id(input_str)
    if not vid:
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.invalid_id"))

    if api is None:
        try:
            api = _make_api()
        except ImportError:
            return Result(
                ok=False,
                error=_err("UNSUPPORTED", lang, "error.upstream"),
            )
    try:
        listing = api.list(vid)
    except Exception as exc:
        return Result(ok=False, error=_classify_exception(exc, lang), meta={"video_id": vid})

    tracks: list[AvailableTrack] = []
    try:
        for tr in listing:
            tracks.append(
                AvailableTrack(
                    language=getattr(tr, "language", "") or "",
                    language_code=getattr(tr, "language_code", "") or "",
                    is_generated=bool(getattr(tr, "is_generated", False)),
                    is_translatable=bool(getattr(tr, "is_translatable", False)),
                )
            )
    except Exception as exc:
        return Result(ok=False, error=_classify_exception(exc, lang), meta={"video_id": vid})

    if not tracks:
        return Result(ok=False, error=_err("NOT_FOUND", lang, "error.no_transcripts"))
    return Result(
        ok=True,
        data=TranscriptList(video_id=vid, tracks=tracks),
        meta={"video_id": vid, "track_count": len(tracks)},
    )


def get_transcript(
    input_str: str,
    prefer_lang: list[str] | None = None,
    translate_to: str | None = None,
    format: str = "text",
    max_chars: int | None = None,
    *,
    language: str = "en",
    api=None,
) -> Result[Transcript]:
    lang = normalize_lang(language)
    if not input_str:
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.empty_input"))
    vid = extract_video_id(input_str)
    if not vid:
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.invalid_id"))

    if format not in ("text", "srt", "vtt", "json"):
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.invalid_format"))

    preferred = [str(p) for p in (prefer_lang or ["en"]) if p]

    if api is None:
        try:
            api = _make_api()
        except ImportError:
            return Result(ok=False, error=_err("UNSUPPORTED", lang, "error.upstream"))

    # Pick the best available track honoring prefer_lang order.
    try:
        listing = api.list(vid)
    except Exception as exc:
        return Result(ok=False, error=_classify_exception(exc, lang), meta={"video_id": vid})

    chosen = None
    chosen_lang = None
    is_generated = False
    try:
        # First try human-curated tracks in the preferred order.
        chosen = listing.find_manually_created_transcript(preferred)
    except Exception:
        chosen = None
    if chosen is None:
        try:
            chosen = listing.find_generated_transcript(preferred)
            is_generated = True
        except Exception:
            chosen = None
    if chosen is None:
        return Result(
            ok=False,
            error=_err(
                "NOT_FOUND",
                lang,
                "error.preferred_unavailable",
                hint_key="hint.list_first",
            ),
            meta={"video_id": vid},
        )

    chosen_lang = getattr(chosen, "language_code", "") or ""
    is_generated = bool(getattr(chosen, "is_generated", is_generated))

    if translate_to:
        try:
            chosen = chosen.translate(translate_to)
            chosen_lang = translate_to
        except Exception as exc:
            return Result(
                ok=False,
                error=_classify_exception(exc, lang),
                meta={"video_id": vid},
            )

    try:
        fetched = chosen.fetch()
    except Exception as exc:
        return Result(ok=False, error=_classify_exception(exc, lang), meta={"video_id": vid})

    raw_entries: list[dict] = []
    for snippet in fetched:
        # Library returns an iterable of FetchedTranscriptSnippet (or dict on older versions).
        text_val = getattr(snippet, "text", None)
        if text_val is None and isinstance(snippet, dict):
            text_val = snippet.get("text")
        start_val = getattr(snippet, "start", None)
        if start_val is None and isinstance(snippet, dict):
            start_val = snippet.get("start", 0.0)
        dur_val = getattr(snippet, "duration", None)
        if dur_val is None and isinstance(snippet, dict):
            dur_val = snippet.get("duration", 0.0)
        raw_entries.append(
            {
                "text": text_val or "",
                "start": float(start_val or 0.0),
                "duration": float(dur_val or 0.0),
            }
        )

    formatted = format_transcript(raw_entries, format)
    truncated = False
    if max_chars and max_chars > 0:
        formatted, truncated = truncate_at_word_boundary(formatted, max_chars)

    transcript = Transcript(
        video_id=vid,
        language_code=chosen_lang,
        is_generated=is_generated,
        translated_to=translate_to or None,
        format=format,  # type: ignore[arg-type]
        text=formatted,
        entries=[TranscriptEntry(**e) for e in raw_entries],
        truncated=truncated,
        char_count=len(formatted),
    )
    return Result(
        ok=True,
        data=transcript,
        meta={
            "video_id": vid,
            "language_code": chosen_lang,
            "is_generated": is_generated,
            "truncated": truncated,
        },
    )

# === core/render.py ===
def to_markdown(result: Result, lang: str = "en") -> str:
    if not result.ok or result.data is None:
        if result.error is None:
            return f"**Error**: unknown failure (lang={lang})"
        msg = result.error.message_tr if lang == "tr" else result.error.message_en
        body = f"**Error** ({result.error.code}): {msg}"
        if result.error.hint:
            body += f"\n\n_Hint: {result.error.hint}_"
        return body

    data = result.data
    if isinstance(data, TranscriptList):
        return _render_list(data, lang)
    if isinstance(data, Transcript):
        return _render_transcript(data, lang)
    return f"**Result**: {data}"


def _render_list(tl: TranscriptList, lang: str) -> str:
    lines = [
        f"# {t('title.list', lang)}",
        "",
        f"- **{t('label.video_id', lang)}**: `{tl.video_id}`",
        f"- **{t('label.tracks', lang)}**: {len(tl.tracks)}",
        "",
        "| Code | Language | Auto | Translatable |",
        "|---|---|:---:|:---:|",
    ]
    for tr in tl.tracks:
        lines.append(
            f"| `{tr.language_code}` | {tr.language} | "
            f"{'✓' if tr.is_generated else '—'} | {'✓' if tr.is_translatable else '—'} |"
        )
    return "\n".join(lines)


def _render_transcript(tr: Transcript, lang: str) -> str:
    parts = [
        f"# {t('title.transcript', lang)}",
        "",
        f"- **{t('label.video_id', lang)}**: `{tr.video_id}`",
        f"- **{t('label.language', lang)}**: `{tr.language_code}`"
        f"{' (auto)' if tr.is_generated else ''}",
        f"- **{t('label.format', lang)}**: `{tr.format}`",
        f"- **{t('label.chars', lang)}**: {tr.char_count}"
        + (f"  •  **{t('label.entries', lang)}**: {len(tr.entries)}" if tr.entries else ""),
    ]
    if tr.translated_to:
        parts.append(f"- **{t('label.translated_to', lang)}**: `{tr.translated_to}`")
    if tr.truncated:
        parts.append(f"\n_{t('note.truncated', lang)}_")
    parts.append("")
    parts.append("```" + (tr.format if tr.format != "text" else ""))
    parts.append(tr.text)
    parts.append("```")
    return "\n".join(parts)

# === owui/_wrapper.py ===
class Tools:
    class Valves(BaseModel):
        DEFAULT_LANGUAGE: str = Field(
            default="en",
            description="Output language. 'en' or 'tr'.",
        )
        DEFAULT_PREFER_LANG: str = Field(
            default="en,tr",
            description="Comma-separated preferred transcript languages, in order.",
        )
        MAX_CHARS: int = Field(
            default=0,
            description="Hard cap on transcript output. 0 disables truncation.",
        )

    def __init__(self):
        self.valves = self.Valves()
        self.citation = False

    def _lang(self, language: str | None) -> str:
        return (language or self.valves.DEFAULT_LANGUAGE or "en").strip()

    def _prefer(self, prefer_lang: list[str] | None) -> list[str]:
        if prefer_lang:
            return prefer_lang
        return [x.strip() for x in (self.valves.DEFAULT_PREFER_LANG or "en").split(",") if x.strip()]

    def list_transcripts(self, url_or_id: str, language: str | None = None) -> str:
        """List available transcript tracks for a YouTube video.

        Use when: user wants to see which subtitle languages exist before
        fetching one. Skip if they just want the transcript - go to get_transcript.
        Non-YouTube URLs are not supported.
        """
        lang = self._lang(language)
        result = list_transcripts(url_or_id, language=lang)
        return to_markdown(result, lang=lang)

    def get_transcript(
        self,
        url_or_id: str,
        prefer_lang: list[str] | None = None,
        translate_to: str | None = None,
        format: str = "text",
        max_chars: int | None = None,
        language: str | None = None,
    ) -> str:
        """Fetch a YouTube transcript in text/srt/vtt/json.

        Use when: "transcript of this YouTube link" / "şu YouTube videosunun
        transkripti" / "subtitle this video as SRT". Skip for non-YouTube
        videos, audio-only podcasts, or when the user just wants a video
        summary without the raw transcript.
        """
        lang = self._lang(language)
        cap = max_chars if max_chars is not None else (self.valves.MAX_CHARS or None)
        result = get_transcript(
            url_or_id,
            prefer_lang=self._prefer(prefer_lang),
            translate_to=translate_to,
            format=format,
            max_chars=cap,
            language=lang,
        )
        return to_markdown(result, lang=lang)

