"""
title: TripWeather
description: Open-Meteo geocoding and travel-day weather forecast. Three tools: geocode (find candidates), forecast (by lat/lon), forecast_by_query (convenience).
author: Orzed, LLC
version: 1.0.0
required_open_webui_version: 0.5.0
"""

# ────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED BY tools/bundle_owui.py — DO NOT EDIT BY HAND.
# Source of truth: this tool's core/ and owui/_wrapper.py.
# Run `make bundle` (or `python tools/bundle_owui.py <tool>`) to regenerate.
# CI runs `make check-bundle` and fails on drift.
# ────────────────────────────────────────────────────────────────────────────

import httpx
import random
import time
from datetime import date as Date
from datetime import timedelta
from pydantic import BaseModel, Field
from typing import Final
from typing import Generic, Literal, TypeVar

# === core/types.py ===
T = TypeVar("T", bound=BaseModel)

ErrorCode = Literal[
    "INVALID_INPUT",
    "NOT_FOUND",
    "RATE_LIMITED",
    "NETWORK_TIMEOUT",
    "UPSTREAM_ERROR",
    "UNSUPPORTED",
    "PARSE_ERROR",
    "TIMEOUT",
    "CANCELLED",
    "INTERNAL",
]

Units = Literal["metric", "imperial"]


class ErrorInfo(BaseModel):
    code: ErrorCode
    message_en: str
    message_tr: str
    hint: str | None = None
    upstream: str | None = None
    retry_after_s: float | None = None


class Result(BaseModel, Generic[T]):
    ok: bool
    data: T | None = None
    error: ErrorInfo | None = None
    meta: dict = Field(default_factory=dict)


class GeocodeCandidate(BaseModel):
    name: str
    country_code: str | None = None
    country: str | None = None
    admin1: str | None = None
    admin2: str | None = None
    latitude: float
    longitude: float
    timezone: str | None = None
    population: int | None = None
    elevation: float | None = None
    score: float = 0.0


class GeocodeResult(BaseModel):
    query: str
    candidates: list[GeocodeCandidate]


class ForecastDay(BaseModel):
    date: Date
    weather_code: int | None = None
    weather_label: str | None = None
    max_temp: float | None = None
    min_temp: float | None = None
    precipitation: float | None = None
    precipitation_probability: int | None = None
    wind_speed: float | None = None
    humidity: int | None = None
    sunrise: str | None = None
    sunset: str | None = None
    uv_index: float | None = None


class ForecastResult(BaseModel):
    latitude: float
    longitude: float
    timezone: str | None = None
    units: Units
    days: list[ForecastDay]
    place_name: str | None = None
    country_code: str | None = None

# === core/i18n.py ===
STRINGS: Final[dict[str, dict[str, str]]] = {
    "en": {
        "title.geocode": "Locations matching “{query}”",
        "title.forecast": "Forecast",
        "label.coords": "Coordinates",
        "label.timezone": "Timezone",
        "label.units": "Units",
        "label.population": "Population",
        "label.elevation": "Elevation",
        "label.score": "Score",
        "label.no_candidates": "No matching locations.",
        "label.no_days": "No forecast days returned.",
        "label.disambiguation": (
            "Multiple equally-confident matches; passing latitude/longitude is "
            "the deterministic fix."
        ),
        "header.day": "Day",
        "header.weather": "Weather",
        "header.temp": "Temp (°{unit})",
        "header.precip": "Precip",
        "header.wind": "Wind",
        "header.humidity": "Humidity",
        "error.empty_query": "Query cannot be empty.",
        "error.invalid_coords": (
            "Latitude must be in [-90, 90], longitude in [-180, 180]."
        ),
        "error.invalid_days": "days must be 1-16.",
        "error.invalid_units": "units must be 'metric' or 'imperial'.",
        "error.invalid_date": "start_date must be YYYY-MM-DD.",
        "error.network": "Open-Meteo did not respond.",
        "error.no_results": "Geocoding returned no results.",
        "hint.use_coords": "Pass `latitude` and `longitude` directly to skip geocoding.",
        "note.forecast": "Forecast data: Open-Meteo (CC-BY 4.0).",
    },
    "tr": {
        "title.geocode": "“{query}” için konumlar",
        "title.forecast": "Tahmin",
        "label.coords": "Koordinatlar",
        "label.timezone": "Saat dilimi",
        "label.units": "Birim",
        "label.population": "Nüfus",
        "label.elevation": "Rakım",
        "label.score": "Skor",
        "label.no_candidates": "Eşleşen konum yok.",
        "label.no_days": "Tahmin günü döndürülmedi.",
        "label.disambiguation": (
            "Eşit güvenilirlikte birden fazla eşleşme; lat/lon vermek belirleyici."
        ),
        "header.day": "Gün",
        "header.weather": "Hava",
        "header.temp": "Sıcaklık (°{unit})",
        "header.precip": "Yağış",
        "header.wind": "Rüzgar",
        "header.humidity": "Nem",
        "error.empty_query": "Sorgu boş olamaz.",
        "error.invalid_coords": "Enlem [-90, 90], boylam [-180, 180] aralığında olmalı.",
        "error.invalid_days": "days 1-16 aralığında olmalı.",
        "error.invalid_units": "units 'metric' veya 'imperial' olmalı.",
        "error.invalid_date": "start_date YYYY-MM-DD biçiminde olmalı.",
        "error.network": "Open-Meteo yanıt vermedi.",
        "error.no_results": "Geocoding hiç sonuç döndürmedi.",
        "hint.use_coords": "Geocoding atlamak için latitude/longitude doğrudan verin.",
        "note.forecast": "Tahmin verisi: Open-Meteo (CC-BY 4.0).",
    },
}

SUPPORTED: Final[tuple[str, ...]] = ("en", "tr")
DEFAULT: Final[str] = "en"


def normalize_lang(lang: str | None) -> str:
    if not lang:
        return DEFAULT
    base = lang.lower().split("-")[0]
    return base if base in SUPPORTED else DEFAULT


def t(key: str, lang: str = DEFAULT, **kwargs: object) -> str:
    lang = normalize_lang(lang)
    table = STRINGS.get(lang) or STRINGS[DEFAULT]
    template = table.get(key) or STRINGS[DEFAULT].get(key) or key
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError):
        return template

# === core/wmo.py ===
WMO_LABELS: dict[int, dict[str, str]] = {
    0: {"en": "Clear sky", "tr": "Açık"},
    1: {"en": "Mainly clear", "tr": "Çoğunlukla açık"},
    2: {"en": "Partly cloudy", "tr": "Parçalı bulutlu"},
    3: {"en": "Overcast", "tr": "Kapalı"},
    45: {"en": "Fog", "tr": "Sis"},
    48: {"en": "Depositing rime fog", "tr": "Kırağılı sis"},
    51: {"en": "Light drizzle", "tr": "Hafif çisenti"},
    53: {"en": "Moderate drizzle", "tr": "Orta çisenti"},
    55: {"en": "Dense drizzle", "tr": "Yoğun çisenti"},
    56: {"en": "Light freezing drizzle", "tr": "Hafif donan çisenti"},
    57: {"en": "Dense freezing drizzle", "tr": "Yoğun donan çisenti"},
    61: {"en": "Slight rain", "tr": "Hafif yağmur"},
    63: {"en": "Moderate rain", "tr": "Orta yağmur"},
    65: {"en": "Heavy rain", "tr": "Şiddetli yağmur"},
    66: {"en": "Light freezing rain", "tr": "Hafif donan yağmur"},
    67: {"en": "Heavy freezing rain", "tr": "Şiddetli donan yağmur"},
    71: {"en": "Slight snow", "tr": "Hafif kar"},
    73: {"en": "Moderate snow", "tr": "Orta kar"},
    75: {"en": "Heavy snow", "tr": "Yoğun kar"},
    77: {"en": "Snow grains", "tr": "Kar taneleri"},
    80: {"en": "Slight rain showers", "tr": "Hafif yağmur sağanağı"},
    81: {"en": "Moderate rain showers", "tr": "Orta yağmur sağanağı"},
    82: {"en": "Violent rain showers", "tr": "Şiddetli yağmur sağanağı"},
    85: {"en": "Slight snow showers", "tr": "Hafif kar sağanağı"},
    86: {"en": "Heavy snow showers", "tr": "Şiddetli kar sağanağı"},
    95: {"en": "Thunderstorm", "tr": "Gök gürültülü fırtına"},
    96: {"en": "Thunderstorm with slight hail", "tr": "Hafif dolu ile fırtına"},
    99: {"en": "Thunderstorm with heavy hail", "tr": "Şiddetli dolu ile fırtına"},
}


def label(code: int | None, lang: str) -> str:
    if code is None:
        return ""
    entry = WMO_LABELS.get(int(code))
    if not entry:
        return f"WMO {code}"
    return entry.get(lang) or entry.get("en") or ""

# === core/http.py ===
class RateLimited(Exception):
    def __init__(self, retry_after: float | None = None) -> None:
        self.retry_after = retry_after


class NetworkTimeout(Exception):
    pass


class UpstreamError(Exception):
    def __init__(self, status: int, body: str) -> None:
        self.status = status
        self.body = body


def build_client(
    timeout: float = 10.0, user_agent: str = "orzed-tripweather/1.0"
) -> httpx.Client:
    return httpx.Client(
        timeout=timeout,
        headers={"User-Agent": user_agent, "Accept": "application/json"},
    )


def get_json_with_retry(
    client: httpx.Client,
    url: str,
    *,
    params: dict | None = None,
    max_attempts: int = 3,
    base_delay: float = 0.5,
) -> dict:
    last_exc: Exception | None = None
    for attempt in range(max_attempts):
        try:
            r = client.get(url, params=params)
        except httpx.TimeoutException:
            last_exc = NetworkTimeout()
        except httpx.RequestError as e:
            last_exc = e
        else:
            if r.status_code == 429:
                ra = r.headers.get("Retry-After")
                last_exc = RateLimited(retry_after=float(ra) if ra else None)
            elif r.status_code in (408, 500, 502, 503, 504):
                last_exc = UpstreamError(r.status_code, r.text[:300])
            elif r.is_success:
                return r.json()
            else:
                raise UpstreamError(r.status_code, r.text[:300])

        if attempt < max_attempts - 1:
            sleep_s = base_delay * (2**attempt) + random.uniform(0, base_delay)
            if isinstance(last_exc, RateLimited) and last_exc.retry_after:
                sleep_s = max(sleep_s, last_exc.retry_after)
            time.sleep(sleep_s)

    if last_exc is not None:
        raise last_exc
    raise UpstreamError(0, "no attempts")

# === core/geocode.py ===
GEOCODING_URL = "https://geocoding-api.open-meteo.com/v1/search"


def _err(code: str, lang: str, en_key: str, *, hint_key: str | None = None,
         fmt: dict | None = None) -> ErrorInfo:
    fmt = fmt or {}
    return ErrorInfo(
        code=code,
        message_en=t(en_key, "en", **fmt),
        message_tr=t(en_key, "tr", **fmt),
        hint=t(hint_key, lang, **fmt) if hint_key else None,
    )


def _to_candidate(raw: dict) -> GeocodeCandidate:
    return GeocodeCandidate(
        name=raw.get("name") or "",
        country_code=raw.get("country_code"),
        country=raw.get("country"),
        admin1=raw.get("admin1"),
        admin2=raw.get("admin2"),
        latitude=float(raw.get("latitude", 0.0)),
        longitude=float(raw.get("longitude", 0.0)),
        timezone=raw.get("timezone"),
        population=raw.get("population"),
        elevation=raw.get("elevation"),
        score=float(raw.get("ranking_score") or 0.0),
    )


def geocode(
    query: str,
    country: str | None = None,
    max_results: int = 5,
    *,
    language: str = "en",
    client=None,
) -> Result[GeocodeResult]:
    lang = normalize_lang(language)
    if not query or not query.strip():
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.empty_query"))

    own_client = client is None
    if client is None:
        client = build_client()
    params = {
        "name": query.strip(),
        "count": str(max(1, min(max_results, 25))),
        "language": lang,
        "format": "json",
    }
    if country and len(country) == 2:
        params["country_code"] = country.upper()

    try:
        try:
            payload = get_json_with_retry(client, GEOCODING_URL, params=params)
        except (NetworkTimeout, RateLimited, UpstreamError):
            return Result(
                ok=False,
                error=_err("UPSTREAM_ERROR", lang, "error.network"),
                meta={"upstream": "open-meteo"},
            )

        results = payload.get("results") or []
        if not results:
            return Result(
                ok=False,
                error=_err("NOT_FOUND", lang, "error.no_results"),
                meta={"query": query},
            )

        candidates = [_to_candidate(r) for r in results]
        # Open-Meteo's ranking_score is monotonic — keep its order; no country bias.
        return Result(
            ok=True,
            data=GeocodeResult(query=query, candidates=candidates),
            meta={"count": len(candidates)},
        )
    finally:
        if own_client:
            client.close()

# === core/forecast.py ===
FORECAST_URL = "https://api.open-meteo.com/v1/forecast"


def _err(code: str, lang: str, en_key: str, *, hint_key: str | None = None) -> ErrorInfo:
    return ErrorInfo(
        code=code,
        message_en=t(en_key, "en"),
        message_tr=t(en_key, "tr"),
        hint=t(hint_key, lang) if hint_key else None,
    )


def _parse_date(value, lang: str) -> tuple[Date | None, ErrorInfo | None]:
    if value is None or value == "":
        return None, None
    if isinstance(value, Date):
        return value, None
    try:
        return Date.fromisoformat(str(value).strip()), None
    except ValueError:
        return None, _err("INVALID_INPUT", lang, "error.invalid_date")


def forecast(
    latitude: float,
    longitude: float,
    *,
    start_date: str | Date | None = None,
    days: int = 3,
    units: str = "metric",
    language: str = "en",
    client=None,
) -> Result[ForecastResult]:
    lang = normalize_lang(language)

    try:
        lat = float(latitude)
        lon = float(longitude)
    except (TypeError, ValueError):
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.invalid_coords"))
    if not (-90 <= lat <= 90) or not (-180 <= lon <= 180):
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.invalid_coords"))
    if days < 1 or days > 16:
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.invalid_days"))
    if units not in ("metric", "imperial"):
        return Result(ok=False, error=_err("INVALID_INPUT", lang, "error.invalid_units"))

    start, derr = _parse_date(start_date, lang)
    if derr:
        return Result(ok=False, error=derr)

    own_client = client is None
    if client is None:
        client = build_client()
    daily = (
        "weather_code,temperature_2m_max,temperature_2m_min,"
        "precipitation_sum,precipitation_probability_max,wind_speed_10m_max,"
        "uv_index_max,sunrise,sunset"
    )
    params = {
        "latitude": str(lat),
        "longitude": str(lon),
        "daily": daily,
        "timezone": "auto",
        "temperature_unit": "fahrenheit" if units == "imperial" else "celsius",
        "wind_speed_unit": "mph" if units == "imperial" else "kmh",
        "precipitation_unit": "inch" if units == "imperial" else "mm",
    }
    if start:
        params["start_date"] = start.isoformat()
        params["end_date"] = (start + timedelta(days=days - 1)).isoformat()
    else:
        params["forecast_days"] = str(days)

    try:
        try:
            payload = get_json_with_retry(client, FORECAST_URL, params=params)
        except (NetworkTimeout, RateLimited, UpstreamError):
            return Result(
                ok=False,
                error=_err("UPSTREAM_ERROR", lang, "error.network"),
                meta={"upstream": "open-meteo"},
            )

        d = payload.get("daily") or {}
        dates = d.get("time") or []
        codes = d.get("weather_code") or []
        tmax = d.get("temperature_2m_max") or []
        tmin = d.get("temperature_2m_min") or []
        precip = d.get("precipitation_sum") or []
        precip_prob = d.get("precipitation_probability_max") or []
        wind = d.get("wind_speed_10m_max") or []
        uv = d.get("uv_index_max") or []
        sunrise = d.get("sunrise") or []
        sunset = d.get("sunset") or []

        out_days: list[ForecastDay] = []
        for i, ds in enumerate(dates):
            try:
                dt = Date.fromisoformat(ds)
            except ValueError:
                continue
            code = codes[i] if i < len(codes) else None
            out_days.append(
                ForecastDay(
                    date=dt,
                    weather_code=code,
                    weather_label=wmo_label(code, lang),
                    max_temp=tmax[i] if i < len(tmax) else None,
                    min_temp=tmin[i] if i < len(tmin) else None,
                    precipitation=precip[i] if i < len(precip) else None,
                    precipitation_probability=(
                        int(precip_prob[i]) if i < len(precip_prob) and precip_prob[i] is not None else None
                    ),
                    wind_speed=wind[i] if i < len(wind) else None,
                    humidity=None,
                    sunrise=sunrise[i] if i < len(sunrise) else None,
                    sunset=sunset[i] if i < len(sunset) else None,
                    uv_index=uv[i] if i < len(uv) else None,
                )
            )

        result = ForecastResult(
            latitude=lat,
            longitude=lon,
            timezone=payload.get("timezone"),
            units="metric" if units == "metric" else "imperial",
            days=out_days,
        )
        return Result(ok=True, data=result, meta={"count": len(out_days)})
    finally:
        if own_client:
            client.close()


def forecast_by_query(
    query: str,
    country: str | None = None,
    *,
    start_date: str | Date | None = None,
    days: int = 3,
    units: str = "metric",
    language: str = "en",
    client=None,
) -> Result[ForecastResult]:
    """Convenience: geocode → top candidate → forecast.

    Surfaces a `meta.disambiguation_warning` flag when multiple high-score
    matches exist so the LLM knows the choice was non-deterministic.
    """
    lang = normalize_lang(language)
    g = geocode(query, country=country, max_results=5, language=lang, client=client)
    if not g.ok or g.data is None:
        return Result(ok=False, error=g.error, meta=g.meta)

    candidates = g.data.candidates
    if not candidates:
        return Result(
            ok=False,
            error=_err("NOT_FOUND", lang, "error.no_results", hint_key="hint.use_coords"),
        )
    top = candidates[0]
    disambiguation = (
        len(candidates) > 1
        and abs((candidates[1].score or 0) - (top.score or 0)) < 1.0
    )

    res = forecast(
        top.latitude,
        top.longitude,
        start_date=start_date,
        days=days,
        units=units,
        language=lang,
        client=client,
    )
    if res.ok and res.data is not None:
        res.data.place_name = top.name
        res.data.country_code = top.country_code
        meta = dict(res.meta)
        meta["matched"] = {
            "name": top.name,
            "country": top.country_code,
            "score": top.score,
        }
        if disambiguation:
            meta["disambiguation_warning"] = True
            meta["hint"] = t("hint.use_coords", lang)
        return Result(ok=True, data=res.data, meta=meta)
    return res

# === core/render.py ===
def to_markdown(result: Result, lang: str = "en") -> str:
    if not result.ok or result.data is None:
        if result.error is None:
            return f"**Error**: unknown failure (lang={lang})"
        msg = result.error.message_tr if lang == "tr" else result.error.message_en
        body = f"**Error** ({result.error.code}): {msg}"
        if result.error.hint:
            body += f"\n\n_Hint: {result.error.hint}_"
        return body

    data = result.data
    if isinstance(data, GeocodeResult):
        return _render_geocode(data, lang)
    if isinstance(data, ForecastResult):
        return _render_forecast(data, lang)
    return f"**Result**: {data}"


def _render_geocode(g: GeocodeResult, lang: str) -> str:
    parts: list[str] = [f"# {t('title.geocode', lang, query=g.query)}", ""]
    if not g.candidates:
        parts.append(f"_{t('label.no_candidates', lang)}_")
        return "\n".join(parts)
    for i, c in enumerate(g.candidates, start=1):
        admin = ", ".join(x for x in (c.admin1, c.country) if x)
        parts.append(
            f"{i}. **{c.name}** — {admin or c.country_code or ''}  "
            f"`({c.latitude:.4f}, {c.longitude:.4f})`"
            + (f" · {t('label.population', lang)}: {c.population:,}" if c.population else "")
            + (f" · {t('label.timezone', lang)}: `{c.timezone}`" if c.timezone else "")
        )
    return "\n".join(parts)


def _render_forecast(f: ForecastResult, lang: str) -> str:
    unit = "F" if f.units == "imperial" else "C"
    parts: list[str] = [
        f"# {t('title.forecast', lang)}",
        "",
    ]
    header = f"**{t('label.coords', lang)}**: `({f.latitude:.4f}, {f.longitude:.4f})`"
    if f.place_name:
        header = f"**{f.place_name}**" + (f" ({f.country_code})" if f.country_code else "") + " · " + header
    parts.append(header)
    parts.append(
        f"**{t('label.timezone', lang)}**: `{f.timezone or '?'}`  •  "
        f"**{t('label.units', lang)}**: `{f.units}`"
    )
    parts.append("")
    if not f.days:
        parts.append(f"_{t('label.no_days', lang)}_")
        return "\n".join(parts)

    parts.append(
        f"| {t('header.day', lang)} | {t('header.weather', lang)} | "
        f"{t('header.temp', lang, unit=unit)} | "
        f"{t('header.precip', lang)} | {t('header.wind', lang)} |"
    )
    parts.append("|---|---|---|---|---|")
    for d in f.days:
        temp = (
            f"{d.min_temp:.0f}/{d.max_temp:.0f}"
            if d.max_temp is not None and d.min_temp is not None
            else "?"
        )
        precip = (
            f"{d.precipitation:.1f}"
            + (f" ({d.precipitation_probability}%)" if d.precipitation_probability is not None else "")
            if d.precipitation is not None
            else "—"
        )
        wind = f"{d.wind_speed:.0f}" if d.wind_speed is not None else "—"
        parts.append(
            f"| `{d.date.isoformat()}` | {d.weather_label or '—'} | {temp} | {precip} | {wind} |"
        )

    parts += ["", f"_{t('note.forecast', lang)}_"]
    return "\n".join(parts)

# === owui/_wrapper.py ===
class Tools:
    class Valves(BaseModel):
        DEFAULT_LANGUAGE: str = Field(
            default="en",
            description="Output language. 'en' or 'tr'.",
        )
        DEFAULT_UNITS: str = Field(
            default="metric",
            description="'metric' (°C, km/h, mm) or 'imperial' (°F, mph, in).",
        )
        DEFAULT_DAYS: int = Field(default=3, description="Default forecast horizon (1-16).")

    def __init__(self):
        self.valves = self.Valves()
        self.citation = False

    def _lang(self, language: str | None) -> str:
        return (language or self.valves.DEFAULT_LANGUAGE or "en").strip()

    def geocode(
        self,
        query: str,
        country: str | None = None,
        max_results: int = 5,
        language: str | None = None,
    ) -> str:
        """Look up geographic candidates for a place name.

        Use when: "where is Springfield" / "Cambridge'in koordinatları". Skip
        if the user wants weather (forecast_by_query) or already has lat/lon
        (forecast). Reverse geocoding (lat/lon -> name) is not supported.
        """
        lang = self._lang(language)
        return to_markdown(
            geocode(query, country=country, max_results=max_results, language=lang),
            lang=lang,
        )

    def forecast(
        self,
        latitude: float,
        longitude: float,
        start_date: str | None = None,
        days: int | None = None,
        units: str | None = None,
        language: str | None = None,
    ) -> str:
        """Daily forecast for explicit lat/lon (Open-Meteo).

        Use when: user already has coordinates, or you geocoded first and now
        have a chosen candidate. Skip if the user gave a place name (use
        forecast_by_query instead). Past dates not supported (forecast only).
        """
        lang = self._lang(language)
        return to_markdown(
            forecast(
                latitude,
                longitude,
                start_date=start_date,
                days=days if days is not None else self.valves.DEFAULT_DAYS,
                units=(units or self.valves.DEFAULT_UNITS),
                language=lang,
            ),
            lang=lang,
        )

    def forecast_by_query(
        self,
        query: str,
        country: str | None = None,
        start_date: str | None = None,
        days: int | None = None,
        units: str | None = None,
        language: str | None = None,
    ) -> str:
        """Geocode + forecast in one call. The default for plain-language requests.

        Use when: "İstanbul hava durumu" / "weather in Tokyo next 5 days" /
        "yarın Paris'te yağmur var mı". Skip if the user gave lat/lon (use
        forecast). Climate / historical weather and past dates are out of scope.
        Sets meta.disambiguation_warning=True when two equally-scored candidates
        exist so the LLM can ask which city.
        """
        lang = self._lang(language)
        return to_markdown(
            forecast_by_query(
                query,
                country=country,
                start_date=start_date,
                days=days if days is not None else self.valves.DEFAULT_DAYS,
                units=(units or self.valves.DEFAULT_UNITS),
                language=lang,
            ),
            lang=lang,
        )

